Main banners
Studio-Yandex-Practicum/lubimovka_frontend pull request #108
Opened 2021-11-01 21:00 UTC by andpigge

## Описание
Компонент Main banners
Пока без данных. Если данные делать, нужно знать приходят ли они все, то есть открывается ли скрытое содержимое или нет. 

## Ссылка на задачу
[main-banners](https://www.notion.so/main-banners-87585ff522a74ff6829197b1f8e865b2)

2021-11-02 16:34 UTC, PyotrGrogorchenko submitted a review, later dismissed

2021-11-03 19:15 UTC, k-ermolova requested changes

2021-11-03 19:15 UTC, k-ermolova commented on src/components/main-page/banners/main-banners.module.css
> +  padding: 0 32px;
Scale тут и дальше в случае с px

2021-11-03 19:15 UTC, k-ermolova commented on src/components/main-page/banners/main-banners.module.css
> +    margin-bottom: 28px;
Будет правильнее сократить `margin` до 1 свойства.

2021-11-03 20:05 UTC, andpigge commented on src/components/main-page/banners/main-banners.module.css
> +    margin-bottom: 28px;
нэт)) мне тут нужно обнулить, в после только снизу margin добавить

2021-11-03 21:44 UTC, whodef approved these changes
Approved

2021-11-03 22:07 UTC, k-ermolova commented on src/components/main-page/banners/main-banners.module.css
> +    margin-bottom: 28px;
Почему ты не можешь сделать так: `margin: 0 0 scale(28px) 0` ?

2021-11-03 22:14 UTC, k-ermolova requested changes

2021-11-03 22:14 UTC, k-ermolova commented on src/components/main-page/banners/main-banners.module.css
> +  margin: scale(0);
Запись `scale(0)` здесь и далее не имеет смысла, это нужно убрать.

2021-11-03 22:14 UTC, k-ermolova commented on src/components/main-page/banners/main-banners.module.css
> +    margin-bottom: scale(28px);
Посмотри коммент, пожалуйста 🙂

2021-11-03 22:43 UTC, gremwiz1 approved these changes

2021-11-04 08:17 UTC, andpigge commented on src/components/main-page/banners/main-banners.module.css
> +    margin-bottom: 28px;
Мне не удобно

2021-11-04 08:19 UTC, andpigge commented on src/components/main-page/banners/main-banners.module.css
> +  margin: scale(0);
Имеет. Поможет избежать ошибок в будущем если я допишу что-то, у меня сразу scale стоит

2021-11-04 09:22 UTC, PyotrGrogorchenko commented on src/components/main-page/banners/main-banners.module.css
> +    margin-bottom: 28px;
`Мне не удобно` - это не аргумент. Почему две строки вместо одной?

2021-11-04 09:24 UTC, PyotrGrogorchenko commented on src/components/main-page/banners/main-banners.module.css
> +  margin: scale(0);
Уверен что в будущем здесь px будет и что вообще что-то поменяется? Зачем лишнее действие?

2021-11-04 09:48 UTC, andpigge commented on src/components/main-page/banners/main-banners.module.css
> +    margin-bottom: 28px;
Ок. Тогда так.
В первый раз я обнулил свойства, так как в десктопной версии есть margin которые не нужны.
Другой человек придет, и сразу будет знать что margin обнулен. В случае с одной строки это не имеет смысл потому, что при сборке код все равно модифицируется, и тут важна читаемость кода.
Если все будет в одну строку, это сложнее читать. 
Вот я приведу пример плохого кода и хорошего.
**Плохой код**

```
img {
  margin-top: 5px;
  margin-right: 10px;
  margin-bottom: 5px;
  margin-left: 10px;
}
button {
  padding: 0 0 0 20px;
}
```

**Хороший код**

```
img {
  margin: 5px 10px;
}
button {
  padding-left: 20px;
}
```

Как вы видите из примера, использование одного свойства в одной строки плохой код, так как сложно читать такой код.

2021-11-04 09:58 UTC, andpigge commented on src/components/main-page/banners/main-banners.module.css
> +  margin: scale(0);
Петр. Лично мое мнение.
Когда всматриваешься в код, как не крути видишь пиксели. Это 0 px. Мы их договорились не использовать.
Это немного запутывает. Особенно того кто придет после нас. Нужно думать не только о себе.
Я согласен с тобой что это лишнее ненужное действие. 
Поэтому предлагаю там где 0px использовать 0rem. Так код будет понятным не только для нас. Раз мы отказались от px, давайте откажемся от него.

2021-11-04 10:12 UTC, PyotrGrogorchenko approved these changes

2021-11-04 10:15 UTC, k-ermolova approved these changes

2021-11-04 10:26 UTC, merged