basic-play-card: рендеринг нескольких авторов
Studio-Yandex-Practicum/lubimovka_frontend pull request #128
Opened 2021-11-04 19:06 UTC by anecheka

## Описание
Добавление функционала в BasicPlayCard для рендеринга нескольких авторов пьесы 
Предполагаю, что авторы приходят в массиве объектов, состоящим из id + имя. 

<img width="154" alt="Снимок экрана 2021-11-04 в 22 01 47" src="https://user-images.githubusercontent.com/76454288/140403220-0b5a46e9-8e6b-4c3d-a49c-7d0c6ccbb6e3.png">

## Комментарий
@borodulex Илья, так как появился дополнительный элемент (список авторов со своей шириной), для корректного отображения вернула ширину в стили .container. Знаю, что много обсуждала. Но сегодня на демо также поняла, что ширина компонента часто не совсем верная, а хотелось бы контролировать. Все комментарии принимаю 🙌

2021-11-05 07:17 UTC, Anastasia-Belik requested changes
По-моему все выглядит отлично! Надо только поправить иерархию списка (отметила в коде). 

Данные с бэка будут прихоить в таком формате: 
```
{
  "count": 123,
  "next": "http://api.example.org/accounts/?offset=400&limit=100",
  "previous": "http://api.example.org/accounts/?offset=200&limit=100",
  "results": [
    {
      "id": 0,
      "name": "string",
      "authors": [
        {
          "name": "string"
        }
      ],
      "city": "string",
      "year": 2021,
      "url_download": "string",
      "url_reading": "string"
    }
  ]
}
```
Пока тут только вариант с одним автором, надо будет посмотреть как будет выглядеть с несколькими.

2021-11-05 07:17 UTC, Anastasia-Belik commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +  const authorsHiddenLabel = (
Здорово, что ты подумала о правильной логике даже для скрытых элементов!

2021-11-05 07:17 UTC, Anastasia-Belik commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +          />
Чтобы соблюсти иерархию списка терминов надо каждый InfoLink обернуть в `dd`

2021-11-05 16:21 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +          />
@Anastasia-Belik поправила!

2021-11-05 17:54 UTC, whodef commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +  padding: 2px 4px;
Привет!
А такого формата `padding: calc(var(--scale) * 2) calc(var(--scale) * 4;` не нужно добавлять? Просто вопрос, вдруг так и задумано. :)

2021-11-06 18:46 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +  padding: 2px 4px;
@whodef Привет! Пока хотелось бы эти пэддинги на ховер оставить без скейлинга. На мой взгляд выглядит ок, небольшое дополнительное выделение на ховер.

2021-11-07 09:31 UTC, Anastasia-Belik submitted a review, later dismissed

2021-11-07 10:38 UTC, whodef submitted a review, later dismissed

2021-11-08 20:05 UTC, anecheka commented
@whodef @Anastasia-Belik Всем привет! Решила, так как связанное, поправить наименования свойств интерфейса в соответствием со схемой от backend-команды. id автора обещают добавить. Вот такой дом коммит: https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/128/commits/f9037bea02497d88b2783a1ec1eeeb6ddca27c8b
Пожалуйста, посмотрите.

2021-11-09 07:03 UTC, Anastasia-Belik approved these changes
Хорошо!

2021-11-14 16:05 UTC, whodef commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +        play.authors.length > 1 ?
Привет! Тут где-то закралась ошибка в типах. Пробовала запустить код у себя с твоей ветки, а он...

![Screenshot from 2021-11-14 17-52-40](https://user-images.githubusercontent.com/7266512/141688656-895a269a-f9a4-4f5c-a7a3-cc59996ea64d.png)

2021-11-16 22:05 UTC, whodef approved these changes
Я разобралась, что везде на проекте необходимо будет поменять структуру как в компонентах, так в json-файлах. 
Сам компонент не имеет ошибок, просто всё остальное, что понаписать уже успели нужно будет поменять после мерджа этого ПР )) там много где.

Но зато приведём в соответствие с API бэкенда!
Не забыть бы сделать объявление в чате по фронту. Если хочешь, я смогу сделать.

2021-11-17 06:55 UTC, anecheka commented
@whodef Таня, привет! Спасибо! Мерджу тогда, пишу в общий чат и жду, какие будут вопросы

2021-11-17 07:08 UTC, merged