Добавление мобильной верстки страницы спектакля
Studio-Yandex-Practicum/lubimovka_frontend pull request #133
Opened 2021-11-09 03:34 UTC by naumch1k

## Описание
Добавила стили для мобилок
Добавила scale, где был пропущен
Добавила недостающие блоки: dateTime, details, video, share..

*в блоке share не очень уверена, кроме того возможно все равно потребуется рефакторинг (в проекте похожих блоков 3, еще не вынесены в отдельный компонент)

*не закончила логику блокировки обеих ручек слайдера компонента отзывов (desktop) для тех случаев, когда количество уже отображаемых отзывов равно всем отзывам

## Ссылка на задачу
[Закончить страницу спектакля](https://www.notion.so/2b42f74a849f43b9ac28c913a5e39e18)

2021-11-10 07:31 UTC, rkostyuchenko reviewed
Го поправим мелкие замечания, в целом все ок 💪

2021-11-10 07:31 UTC, rkostyuchenko commented on src/mocks/data/performance.ts
> +  date: '12 мая 20:00', /* ISO data */
Давай сразу будем использовать дату в ISO, кажется, будет так `2021-05-12T07:04:00.000Z`

2021-11-10 07:31 UTC, rkostyuchenko commented on src/pages/performance/[id].tsx
> +            <PerformancePlay>
Эта обертка не лишняя?

2021-11-10 07:31 UTC, rkostyuchenko commented on src/pages/performance/[id].tsx
> +            title='Заголовок блока с&nbsp;фотографиями'
Вот тут, как мне кажется, баг дизайна и заголовка быть не должно. Во всяком случае бекенд сейчас не планирует нам его отдавать. Нужно или убрать заголовок, или обсудить с беком, в каком виде мы будем получать блок с видео.

2021-11-10 07:31 UTC, rkostyuchenko commented on src/components/review-carousel/review-carousel.tsx
> +        {carousel && <SliderDots
Этот блок и блок ниже рендерятся по одному условию, их можно объединить

2021-11-10 07:31 UTC, rkostyuchenko commented on src/components/review-carousel/review-carousel.module.css
> +.arrow:nth-of-type(1) {
Чтобы стили проще читались, можно чутка поправить композицию, добавив блок-контейнер для кнопок навигации

2021-11-10 07:34 UTC, rkostyuchenko commented
И лучше не делать все одним коммитом (я понимаю, что все в спешке). Если хочется попрактиковать работу с гитом, хорошо бы переразбить на коммиты поменьше и по смыслу.

2021-11-13 15:39 UTC, naumch1k commented on src/pages/performance/[id].tsx
> +            <PerformancePlay>
@rkostyuchenko моя проблема тут в том, что <BasicPlayCard /> тянется на 100%. Если ограничивать ширину  <PerformanceLayout.Play /> (как было раньше) - то заголовок тоже ограничивается.

Как вариант, сейчас пробую добавить проп  type для <BasicPlayCard /> , и с его помощью управлять шириной карточки

2021-11-13 20:22 UTC, naumch1k commented on src/components/review-carousel/review-carousel.module.css
> +.keenSlider {
@rkostyuchenko это я пытаюсь победить инлайновые стили слайдера. Почему-то 100% на разрешении 414 равняются не 414px, а 500 с гаком и растягиваются всю страницу

![Screen Shot 2021-11-13 at 2 06 05 PM](https://user-images.githubusercontent.com/76534205/141657748-de0cb077-e98d-4ee5-809f-4b46bd3161d7.png)

2021-11-13 20:30 UTC, naumch1k commented on src/components/review-carousel/review-carousel.tsx
> +  const carouselClassName = `keen-slider ${cx('keenSlider')}`;
🤔 если использовать `container` получится `review-carousel_container`, что как будто бы контейнер всего компонента.. 
может покуда у нас уже есть `slide`, это будет `slider`?

2021-11-14 01:41 UTC, naumch1k commented on src/components/critique-card/critique-card.tsx
> +          /* href='' */
Убрала

2021-11-14 01:41 UTC, naumch1k commented on src/components/performance-layout/video/performance-layout-video.module.css
> +    padding: scale(24px 24px);
Сократила

2021-11-14 01:42 UTC, naumch1k commented on src/components/performance-share/performance-share.tsx
> +      <h4 className={cx('title')}>
Переделала. Надеюсь, не перемудрила

2021-11-14 01:42 UTC, naumch1k commented on src/components/performance-layout/video/performance-layout-video.module.css
> +    padding: scale(24px 24px);
Сократила

2021-11-14 01:43 UTC, naumch1k commented on src/components/performance-share/performance-share.tsx
> +      <h4 className={cx('title')}>
Переделала в компонент, общий для таких же блоков на страницах новости и блога
Надеюсь, не перемудрила

2021-11-14 01:44 UTC, naumch1k commented on src/components/performance-video/performance-video.tsx
> +export const PerformanceVideo = (props: IPerformanceVideoProps): JSX.Element => {
Терерь просто `Video`

2021-11-14 01:45 UTC, naumch1k commented on src/mocks/data/performance.ts
> +  date: '12 мая 20:00', /* ISO data */
А тут нужна помощь. Не понимаю, как распарсить

2021-11-14 01:45 UTC, naumch1k commented on src/pages/performance/[id].tsx
> +            title='Заголовок блока с&nbsp;фотографиями'
Убрала

2021-11-14 01:46 UTC, naumch1k commented on src/components/review-carousel/review-carousel.tsx
> +        {carousel && <SliderDots
Объединила

2021-11-14 01:46 UTC, naumch1k commented on src/components/review-carousel/review-carousel.module.css
> +.arrow:nth-of-type(1) {
Поправила

2021-11-14 12:46 UTC, rkostyuchenko commented on src/components/share/share.module.css
> +.s .span {
Можно использовать вложенность для селекторов, например,
```
.s {
  .span { ... }
  .links { ... }
}
```

2021-11-14 12:46 UTC, rkostyuchenko commented on src/components/share/share.tsx
> +        <span className={cx('span')}></span>
Давай переименуем `span` во что-то более осмысленное 🙂

2021-11-14 12:46 UTC, rkostyuchenko commented on src/components/share/share.tsx
> +        <span className={cx('span')}></span>
Может лучше использовать, например, такую структуру пропсов: `<Share firstLine="Рассказать" secondLine="о спектакле"/>`, как думаешь?

2021-11-14 12:46 UTC, rkostyuchenko commented on src/mocks/data/performance.ts
> +  date: '12 мая 20:00', /* ISO data */
https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/86#pullrequestreview-790801000 тут Илья уже отвечал 👀

2021-11-14 12:46 UTC, rkostyuchenko commented on src/components/review-carousel/review-carousel.tsx
> +
Лишний пробел

2021-11-15 09:50 UTC, borodulex requested changes
Хорошо! Я бы одобрил, но есть вопросы к компоненту Video ;(

PS Еще заметил, что по макету карточка рецензии имеет высоту по контенту, нужно бы исправить, но не уверен, что в этом ПР
![image](https://user-images.githubusercontent.com/72004032/141757517-9dbcc9e2-2a38-4da1-b53a-f6a54b897d04.png)

2021-11-15 09:50 UTC, borodulex commented on src/components/critique-card/critique-card.tsx
> +            isOutsideLink={true}
Можно просто isOutsideLink использовать. По хорошему такое должен линтер править автоматом

2021-11-15 09:50 UTC, borodulex commented on src/components/performance-layout/share/performance-layout-share.tsx
> +    <div className={cx('share')}>
Я бы еще добавил семантики в виде тега `<section>`, касается всех блоков на странице. К задаче конечно не относится, просто отметил

2021-11-15 09:50 UTC, borodulex commented on src/components/performance-details/performance-details.module.css
> +  gap: scale(33px);
Хоть и у gap для флексбокса поддержка уже приличная, но он не работает в safari 14, например
https://caniuse.com/?search=flex-gap

2021-11-15 09:50 UTC, borodulex commented on src/components/performance-details/performance-details.module.css
> +  gap: scale(33px);
Я бы пока избегал его использования

2021-11-15 09:50 UTC, borodulex commented on src/components/performance-details/performance-details.tsx
> +        <span>+</span>
Можно было просто в шаблонную строку все обернуть

2021-11-15 09:50 UTC, borodulex commented on src/components/share/share.stories.tsx
> +const customViewports = {
Не знаю зачем это нужно, если в них действительно есть необходимость, то стоит их задать во всем сторибуке 🤷‍♂️

2021-11-15 09:50 UTC, borodulex commented on src/components/video/video.module.css
> +  width: scale(691px);
Что-то пошло не так)
Во-первых, `.performance` — видимо опечатка, во-вторых, фиксированный размер у компонента.

2021-11-15 09:50 UTC, borodulex commented on src/components/video/video.tsx
> +export const Video = (props: IVideoProps): JSX.Element => {
А точно нужен этот компонент?

2021-11-15 14:19 UTC, naumch1k commented on src/components/video/video.module.css
> +  width: scale(691px);
@borodulex я такое решение подглядела у компонента [`Section`](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/tree/main/src/components/section):
передаю проп type - место, где используется компонент, записываю в класс, стилизую тут же на месте.

Таким образом, фиксированный размер - не у компонента, а этого конкретного видео

Что я могла бы сделать, поправить лэйаут блока на странице, так чтобы ширина была 100%

2021-11-15 14:29 UTC, naumch1k commented on src/components/video/video.tsx
> +export const Video = (props: IVideoProps): JSX.Element => {
в противном случае, я не знаю, где прописывать разметку для iframe и стилизовать его: прямо в лэйауте блока страницы? Но он ж на то и лэйаут, чтобы там выполнять только свою задачу? 

@rkostyuchenko оставляем компонент `Video` или нужно какое-то другое решение?

2021-11-15 14:32 UTC, naumch1k commented on src/components/share/share.stories.tsx
> +const customViewports = {
Прав. Убрать или уже оставить?

2021-11-15 15:13 UTC, naumch1k commented on src/components/performance-details/performance-details.module.css
> +  gap: scale(33px);
Исправила

2021-11-15 15:13 UTC, naumch1k commented on src/components/critique-card/critique-card.tsx
> +            isOutsideLink={true}
Исправила

2021-11-15 20:05 UTC, naumch1k commented on src/components/video/video.tsx
> +export const Video = (props: IVideoProps): JSX.Element => {
Оставляем компонент `Video`

2021-11-15 20:05 UTC, naumch1k commented on src/components/video/video.module.css
> +  width: scale(691px);
Переделала

2021-11-16 17:56 UTC, borodulex commented on src/components/share/share.stories.tsx
> +const customViewports = {
Я бы убрал

2021-11-16 18:14 UTC, borodulex commented on src/components/video/video.tsx
> +export const Video = (props: IVideoProps): JSX.Element => {
Я засомневался в надобности этого компонента, потому что особых стилей и логики у айфрема нет. Ему можно задать относительный размер при помощи атрибутов `width='100%' height='100%'`. А при помощи `<PerformanceLayout.Video />` задать уже необходимый фиксированный размер.

2021-11-16 18:16 UTC, borodulex commented on src/components/video/video.tsx
> +export const Video = (props: IVideoProps): JSX.Element => {
А разметку прям во вьюхе можно прописать

2021-11-16 18:19 UTC, borodulex approved these changes
Хорошечно)

2021-11-16 19:07 UTC, rkostyuchenko approved these changes

2021-11-16 19:07 UTC, merged