feat: добавлена возможность утсановки кнопки НАЗАД
Studio-Yandex-Practicum/lubimovka_frontend pull request #134
Opened 2021-11-10 18:32 UTC by Kerjanoid

## Описание
Добавлена возможность установки кнопки "назад" через пропы компонента AppLayout

## Ссылка на задачу
[Добавить в шапку кнопку](https://www.notion.so/9758ed6412ff4aa2927a8491e43c3ef5)

2021-11-14 02:42 UTC, naumch1k reviewed
Оставила пару комментариев

а еще думаю, не должен ли компонент `BackButton` быть в /components/ui ?  🤔

2021-11-14 02:42 UTC, naumch1k commented on src/components/back-button/back-button.tsx
> +    <div className={cx('buttonWrapper')}>
Можно без button, а то получается `back-button_buttonWrapper`

2021-11-14 02:42 UTC, naumch1k commented on src/components/back-button/back-button.module.css
> +  display: flex;
а для чего этот стиль нужен?

2021-11-14 07:03 UTC, Kerjanoid commented
По комментам внутри - поправлю.
Не думаю, что данный компонент надо хранить в ui, т.к. он уже наследует в себя UIную кнопку и имеет стили для позиционирования на странице.
@rkostyuchenko @borodulex лучше так оставить или в ui засунуть?

2021-11-14 07:18 UTC, Kerjanoid commented
А может и в UI можно. В общем жду "совет старейшин")

2021-11-14 12:17 UTC, rkostyuchenko requested changes
- Нужно исправить опечатки в коммит-месседжах и заголовке ПР
- Сча непонятно, как смотреть результат, давай сразу добавим кнопки на все страницы, где они нужны

2021-11-14 12:17 UTC, rkostyuchenko commented on src/components/app-layout/app-layout.tsx
> +      {backButton && <BackButton label={backButton.text} href={backButton.path} />}
Лучше добавить кнопке обертку, например Page.Breadcrumb

2021-11-14 12:17 UTC, rkostyuchenko commented on src/components/back-button/back-button.tsx
> +export const BackButton: FC<IBackButtonProps> = (props) => {
А вот отсюда обертку надо убрать. В целом весь этот компонент кажется лишним.

2021-11-14 12:17 UTC, rkostyuchenko commented on src/components/back-button/back-button.module.css
> +  position: absolute;
А почему мы хотим позицировать кнопку абсолютно?

2021-11-14 12:19 UTC, rkostyuchenko commented
> По комментам внутри - поправлю. Не думаю, что данный компонент надо хранить в ui, т.к. он уже наследует в себя UIную кнопку и имеет стили для позиционирования на странице. @rkostyuchenko @borodulex лучше так оставить или в ui засунуть?

На самом деле этот компонент вообще не нужен. Непонятно, что мешает использовать кнопку прямо в AppLayout без лишних оберток

2021-11-14 12:27 UTC, Kerjanoid commented
В AppLayout у нас полностью отсутствуют какие-либо стили, не хотелось захламлять компонент стилями только для позиционирования кнопки.
Поэтому сделал её отдельным компонентом, спозиционированным абсолютно, чтоб она не влияла на положение других компонентов на странице

2021-11-15 18:57 UTC, Kerjanoid reviewed
Нужна помощь с данным компонентом. 
Не имею представления как при текущем состоянии спозиционировать всё согласно макету.
![image](https://user-images.githubusercontent.com/76227328/141838511-5fe4586c-55b8-4c65-bc54-5d3c018ee958.png)

2021-11-16 19:50 UTC, borodulex requested changes
Есть пара важных исправлений, а так гуд :)

2021-11-16 19:50 UTC, borodulex commented on .env.local
> +MOCKS=true
Этого в ПР быть не должно. Недавно влили ПР с удалением этого файла из основной ветки. Нужно стянуть последние изменения из основной ветки с ребейзом.

2021-11-16 19:50 UTC, borodulex commented on src/components/author-page/author.module.css
> +  margin-top: -3rem;
А зачем использовать rem?

2021-11-16 19:50 UTC, borodulex commented on src/pages/blog/article/index.tsx
>        <ArticlePage metaTitle={metaTitle} isBlog={true}/>
У новостей тоже есть article, там так же нужно добавить кнопку

2021-11-16 19:50 UTC, borodulex commented on src/pages/blog/article/index.tsx
> +    <AppLayout backButton={{path: '/blog',text: 'блог'}}>
Ультра мелочь, но отсутствие пробела после запятой затрагивает мои чувства)

2021-11-17 09:19 UTC, Anastasia-Belik commented
Ребята, привет! Ворвусь в ваше обсуждение. У меня в компоненте Article-Page тоже есть эта кнопка НАЗАД. И я не совсем понимаю, как она у вас реализована и встает на страницу. 

У меня на странице следующая логика: 
- кнопка находится в шапке статьи и позиционируется всегда относительно шапки
- когда меняется вьюпорт, кнопка сдвигается вправо на размер лого

При такой реализации, если бы у хедера на страницах, где есть такая кнопка, было бы абсолютное позиционирование, блок с шапкой статьи поднимался бы к началу страницы и кнопка вставала бы на один уровень с лого. Чем плох такой вариант? Не будет ли он проще?

На страницу ArticlePage можно посмотреть [тут](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/135).

2021-11-17 14:02 UTC, Kerjanoid commented
> Ребята, привет! Ворвусь в ваше обсуждение. У меня в компоненте Article-Page тоже есть эта кнопка НАЗАД. И я не совсем понимаю, как она у вас реализована и встает на страницу.
> 
> У меня на странице следующая логика:
> 
> * кнопка находится в шапке статьи и позиционируется всегда относительно шапки
> * когда меняется вьюпорт, кнопка сдвигается вправо на размер лого
> 
> При такой реализации, если бы у хедера на страницах, где есть такая кнопка, было бы абсолютное позиционирование, блок с шапкой статьи поднимался бы к началу страницы и кнопка вставала бы на один уровень с лого. Чем плох такой вариант? Не будет ли он проще?
> 
> На страницу ArticlePage можно посмотреть [тут](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/135).

Привет =)))
Поскольку данная кнопка имеется на многих страницах, то решили сделать её частью <AppLayout>...Ты просто в обертку(AppLayout) добавляешь проп таки образом <AppLayout backButton={{path: 'адрес',text: 'текс_кнопки'}}>.
А дальше работаешь со страницей на которой уже есть кнопка =)

2021-11-17 14:45 UTC, Anastasia-Belik commented
Ок, как смержите, посмотрю-попробую)

2021-11-24 07:56 UTC, Anastasia-Belik commented
Ребята, привет! Сейчас в стайлгайде заметила такую фразу про кнопку: 

> Кнопка, ведущая на назад, имеет лейбл с названием страницы, откуда пришел пользователь. 

На статью блога или новости можно попасть не только со страниц /blog или /news, но и с главной страницы. Как я понимаю из стайлгайда, в таком случае кнопка должна вести на главную страницу. Можем заложить такую логику?
![Screenshot from 2021-11-24 10-54-56](https://user-images.githubusercontent.com/79516696/143197264-0de5aca1-e660-4719-b05e-ff4f8d014d5e.png)

2022-05-19 07:14 UTC, rkostyuchenko commented
ПР не актуален

2022-05-19 07:14 UTC, closed without merging