feat/Добавил submenu
Studio-Yandex-Practicum/lubimovka_frontend pull request #140
Opened 2021-11-12 20:09 UTC by andpigge

## Описание
Добавил общий компонент submenu, использовал у себя на странице what-we-do.

## Ссылка на задачу
[Вынести submenu](https://www.notion.so/submenu-bf46366bb5f4478e9c4fc1a8413fc0e8)

2021-11-12 20:53 UTC, SidorovN submitted a review, later dismissed

2021-11-12 21:12 UTC, EvgeniiaZu8ova commented
Подскажите, почему мы выносим Submenu в отдельный компонент? Почему мы не можем просто использовать компонент Menu разновидности general-submenu? Другие разновидности Menu мы ведь не выносим в отдельные компоненты. Например, я использую компонент Menu разновидности history на своей странице таким образом:

`<div className={styles.menu}>
    <Menu type='history'>
      <Menu.Item
        href='/library'
      >
  Пьесы
      </Menu.Item>
      <Menu.Item
        href='/library/authors'
      >
  Авторы
      </Menu.Item>
    </Menu>
</div>`

То есть передаю значение в prop type и контент в children. Почему мы не можем сделать то же самое для других разновидностей? Тогда надо делать отдельные компоненты для всех кейсов. Или я что-то не понимаю?

2021-11-13 16:00 UTC, PyotrGrogorchenko approved these changes

2021-11-14 11:12 UTC, rkostyuchenko requested changes
- Компонент `submenu` нужно унести из другого компонента в собственную директорию
- Нейминг сейчас сбивает с толку, от компонента ждешь, что он рендерит абстрактное подменю, а он вместо это рендерит захардкоженные пункты. Нужно или переименовать `submenu`, например, в `about-menu` или подумать над другой композицией страниц раздела о фестивале
- Пункты меню лучше унести в константы

2021-11-14 11:12 UTC, rkostyuchenko commented on src/components/ui/menu/submenu/submenu.tsx
> +import submenuData from 'components/ui/menu/submenu/submenu-data.json';
Почему мы хотим класть один компонент в другой, да еще и какие-то данные рядом класть?

2021-11-14 11:12 UTC, rkostyuchenko commented on src/components/ui/menu/submenu/submenu.tsx
> +      {submenuData.map((submenu: ISubmenu, i) => (
Не стоит использовать индексы в качестве ключа

2021-11-14 11:12 UTC, rkostyuchenko commented on src/components/ui/menu/submenu/submenu.tsx
> +// data json
Комментарии лучше убрать

2021-11-14 11:12 UTC, rkostyuchenko commented on src/components/ui/menu/submenu/submenu.tsx
> +interface ISubmenu {
Этот интерфейс точно нужен? Почему мы не хотим использовать типы из компонента меню, раз это просто обертка над ним. Плюс мы забыли про необходимость выделять активный пункт

2021-11-24 20:30 UTC, whodef approved these changes

2021-11-25 06:53 UTC, PyotrGrogorchenko approved these changes

2021-11-25 10:35 UTC, rkostyuchenko approved these changes

2021-11-25 12:39 UTC, merged