for-press-press-releases-view - WIP
Studio-Yandex-Practicum/lubimovka_frontend pull request #142
Opened 2021-11-14 19:27 UTC by anecheka

## Описание
Верстка компонента с подгрузкой пресс-релиза на странице "Для прессы"

## Ссылка на задачу
[for-press-press-releases-view](https://www.notion.so/for-press-press-releases-view-e6af89eb07ef470697bbd78c66f18d0b)

TO DO 
1. исправить ошибки typescript (их много :(
2. поправить верстку десктопа в соответствии с макетом (зависимость: необходимо уточнить с дизайнером по отступам всех видов компонентов) 
3. верстка мобильной версии 
4. исправить названия полей в соотвествии с тем, как будут приходить с бэка (зависимость: ожидаю API от команды бэка) 
5. придумать, как не передавать значение года для кнопки "Скачать пресс-релиз" в мобильной версии

2021-11-17 15:29 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +  const [pressReleaseYear, setPressReleaseYear] = useState<string[] | number>(pressReleaseDefaultYear);
лучше назвать переменную pressReleaseYearSelected, ведь в нее записывается выбранный год.

2021-11-17 15:46 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +        }
в мобильной версии меняется только лейбл, можно не дублировать код всей кнопки:
<Button
              view='primary'
              className={cx('button')}
              align='center'
              gap='11px'
              size='s'
              border='bottomLeft'
              iconPlace='right'
              icon='arrow-down'
              label={isMobile ? 'Скачать пресс-релиз в .pdf' : `Скачать пресс-релиз ${pressReleaseYear} года в .pdf`}
              isLink
              href={pressReleaseSelected.downloadLink}
            />

2021-11-17 16:07 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +  const isMobile = useMediaQuery(`(max-width: ${breakpoints['tablet-portrait']})`);
Результатом pressReleases.find(i => i.year == pressReleaseYearSelected) теоритечески может быть undefined, из-за этого возникает синтаксическая ошибка TS. Чтобы ее избежать можно использовать такую констуркцию. Если пресс-релиз не найден, код ниже нее не будет исполнен.

```
const pressReleaseSelected = data.pressReleases.find(i => i.year == pressReleaseYear);

if(pressReleaseSelected === undefined) {
    return <p>Пресс-релиз за этот год не найден</p>;
  }

const isMobile = useMediaQuery(`(max-width: ${breakpoints['tablet-portrait']})`);
```

2021-11-17 17:23 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +}
Записать типы лучше вот так, причем лучше сами типы (то что начинается с type) вынести в папку type (где лежит тип url): 
```
export interface IForPressPressReleasesViewProps {
  data: {
    cover: Url,
    pressReleases: PressRelease[],
  },
}

type PressRelease = {
  year: number,
  downloadLink: Url,
  contents: Content[]
}

type Content = {
  content_type: ContentType;
  content_item: Record<ContentType, string | string[]>;
}

type ContentType = 'text' | 'title' | 'preamble' | 'list';
```
Единственное, это схема будет работать если с бэка список будет приходить в таком формате, надо обсудить это с ребятами с бэка:
```
{
          "content_type": "list",
          "content_item": {
            "list": [
              "«Цикл индекса» Екатерины Августеняк (Санкт-Петербург) — серия наблюдений о том, как все неустойчиво развивается;",
              "«Страна Вась» Викентия Брызя (Владивосток) — пьеса-поэма, исследующая массовое бессознательное жителей Приморья;",
              "«Я танцую как дебил» Игоря Витренко (Рязань) — история обыкновенного мужика, который бросает глупости и начинает заниматься делом: мастерит модельки машин;",
              "«Дыры» Лидии Головановой (Санкт-Петербург) — незначительный разговор о деньгах и космосе, благодаря которому раскрывается жизнь;",
              "«deinosдина» Даниила Гурского (Санкт-Петербург) — трип внутрь сознания, где скрываются чудовища, так похожие на нас самих;",
              "«Республика» Сергея Давыдова (Самара) — воспоминание в стихах о гражданской войне в Таджикистане и разрушении Вавилонской башни;"
            ]
          }
        }
```

2021-11-17 17:27 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +                </ul>);
Если указать типы, как я написала выше, то тут будет вот такой код:
```
return (
                <ul key={idx}>
                  {
                    Array.isArray(item.content_item.list) &&
                    item.content_item.list.map((listItem, idx) => {
                      return(<li key={idx}>{listItem}</li>);
                    })
                  }
                </ul>);
```
Здесь ошибка возникала, потому что согласно указанным типам list мог бы быть и не массивом, что не допустимо для map. Такмы делаем проверку и код с map выполняется только если `item.content_item.list` массив

2021-11-18 08:11 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +}
Если сюда добавить` z-index: 2` - список будет выпадать поверх контента.
На мобилке дроплист выходит за края экрана, предлагаю пофиксить это задав wrapper grip-template-columns

2021-11-18 08:12 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +}
на мобилке текст в макете headline6

2021-11-18 08:15 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +    "  .        text";
Я бы вынесла в отдельный блок лейбл, дроплист и кнопку, например в элемент navigation, и этот элемент тоже можно сделать гридом, тогда на мобилке будет удобнее задавать ему отсутпы побокам, сейчас выглядит кривовато.

2021-11-18 08:16 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +        <Droplist
Когда мы выбираем значение в дроплисте пресс-релиз меняется, но точка выбора всегда остается на первом элементе списка. Пока не поняла, как это пофиксить, возможно это баг в дроплисте.

2021-11-21 18:00 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +  const [pressReleaseYear, setPressReleaseYear] = useState<string[] | number>(pressReleaseDefaultYear);
готово

2021-11-21 18:00 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +        }
супер, спасибо
готово

2021-11-21 18:03 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +  const isMobile = useMediaQuery(`(max-width: ${breakpoints['tablet-portrait']})`);
Настя, комментарий отличный. Реализовала, как подумалось верно: прописала состояния для свойств элементов в случае, если pressReleaseSelected === undefined (возможно, нужно привлечь дизайнера.). Но это теоретическая конструкция: не могу придумать, как мой вариант протестировать, как поправить json на состояние undefined или сделать иначе. Можешь посоветовать? 

```
 <Button
          view='primary'
          className={cx('button')}
          align='center'
          gap='11px'
          size='s'
          border='bottomLeft'
          iconPlace='right'
          icon='arrow-down'
          label={
            pressReleaseSelected === undefined ?
              'Пресс-релиз не найден'
              : pressReleaseSelected !== undefined && isMobile
                ? 'Скачать пресс-релиз в .pdf'
                : `Скачать пресс-релиз ${pressReleaseYearSelected} года в .pdf`}
          isLink={pressReleaseSelected !== undefined ? true : false}
          disabled={pressReleaseSelected !== undefined ? false : true}
          href={pressReleaseSelected !== undefined ? pressReleaseSelected.downloadLink : ''}
        />
      </nav>
      <img className={cx('cover')} src={data.cover}/>
      <article className={cx('pressReleaseText')}>
        {pressReleaseSelected === undefined ?
          <p>Пресс-релиз этого года не найден</p>
          : pressReleaseSelected.contents.map((item, idx) => {
            switch (item.content_type) {
            case 'preamble':
              return(<h6 key={idx}>{item.content_item.preamble}</h6>);
```

2021-11-21 18:04 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +}
Спасибо! Сделано с оговорками: в папку type пока не выношу, хочу дождаться API и понять, что все именно так к нам и будет приходить. Список пока с бэк командой не обсуждала.

2021-11-21 18:04 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +                </ul>);
ага, класс. спасибо! готово

2021-11-21 18:04 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +}
готово 
🙏

2021-11-21 18:04 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +}
готово

2021-11-21 18:07 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +    "  .        text";
готово
но осталась проблема с отступами в мобильной версии. есть небольшой доп отступ справа сверх заданного 24px. Пока не разобралась, откуда он возникает 

![Снимок экрана 2021-11-21 в 21 05 47](https://user-images.githubusercontent.com/76454288/142773778-aeac63cd-0f59-4f5d-a010-0275d68ff8fe.png)

2021-11-21 18:07 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +        <Droplist
Если кликнуть два раза, то точка переносится. Пока не делаю по этому пункту ничего, посмотрю и подожду правки текущие по droplist

2021-11-21 18:38 UTC, yar83 submitted a review, later dismissed
Я посмотрел, вроде никакого криминала не увидел. Возможно, у меня ещё не такой намётанный взгляд, но выглядит очень прилично.

2021-11-21 18:41 UTC, anecheka commented
@Anastasia-Belik Настя, к нашему обсуждению про кнопку напишу тут, так как пока не знаю, как лучше решить. Иконка в дроплисте скейлится с помощью calc (scale (25px)), поэтому я прописала такой же скейлинг иконки и у кнопки: 

.button > svg {
   width: scale(25px);
   height: scale(25px);
 }

чтобы скейлинг был одинаковый
и для announced-play-card реализую пока такой же вариант. но потенциально вопрос на обсуждение

2021-11-22 08:51 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +    "  .        text";
Это происходит потому что ты для десктопа задаешь ширину колонок, а в мобилке ее не меняешь. Блок navigation вылезает за края экрана, дроплист выравнивается по началу строки и из-за этого получается лишний отступ. 

Предлагаю в целом поправить логику отступов navigation (касается только мобильной версии): 

- убрать margin-right/left у элементов droplistLabel, droplist, button.

блоку navigation 
- добавляем: `grid-template-columns: scale(166px) scale(149px);`, 
- width меняем со 100% на 88.41%, 
- margin-top тут лишний, т.к. верхний отступ задается паддингом заголовка, 
- добавляем `margin: 0 auto ` - блок выравнивается посередине и у всех одниковые отступы сбоку.

После всех манипуляций получается вот так:

![Screenshot from 2021-11-22 11-23-12](https://user-images.githubusercontent.com/79516696/142830370-26871e15-17b8-4fc9-ab0a-4c792dd1ae92.png)

2021-11-22 09:11 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +  const isMobile = useMediaQuery(`(max-width: ${breakpoints['tablet-portrait']})`);
Поскольку ты формируешь дроплист из тех годов, которые нам приходят с бэка вместе с пресс-релизами, ситуация когда нет текста пресс-релиза возможна только если редактор заполнил год, а текст почему-то нет. Надо узнать у бэка, можно ли сохранить пресс-релиз без текста в админке. Если нет, тогда проверка на undefined остается исключительно, чтобы не было ошибок TS и интерфейс на этот случай можно не отрисывывать, кмк. Если окажется, что пресс-релиз можно сохранить без текста, тогда надо спросить у дизайнера, что показывать, но лучше конечно реализовать первый сценарий.

Проверку в button можно записать покороче:
```
<Button
          view='primary'
          className={cx('button')}
          align='center'
          gap='11px'
          size='s'
          border='bottomLeft'
          iconPlace='right'
          icon='arrow-down'
          label={
            pressReleaseSelected === undefined ?
              'Пресс-релиз не найден'
              : isMobile
                ? 'Скачать пресс-релиз в .pdf'
                : `Скачать пресс-релиз ${pressReleaseYearSelected} года в .pdf`}
          isLink={pressReleaseSelected !== undefined}
          disabled={pressReleaseSelected === undefined}
          href={pressReleaseSelected !== undefined ? pressReleaseSelected.downloadLink : ''}
        />
```

2021-11-22 09:13 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +        <Droplist
Я посмотрела, сам компонент дроплиста работает правильно, и у Жени на странице блога точка перемещается с первого раза, видимо проблема все-таки на странице. Подумаю, как ее решить

2021-11-22 09:29 UTC, Anastasia-Belik requested changes
Аня, супер! Все ошибки исправлены. Давай поправим блок navigation, добавим alt и можно мерджить, чтобы у нас в мэйне верстка была уже зафиксирована, а функционал можно поправить на этапе сборки страницы. Надеюсь к тому времени уже будет точно известно в каком виде нам данные приходят. 

Кнопка с иконкой скейлятся, так что можно оставить такое решение.

Остаются два открытых вопроса:
1. может ли с бэка прилететь пресс-релиз с годом и без текста, как его в таком случае отрисовывать
2. некорректно работает дроплист (точка выбора переставляется только со второго клика).

2021-11-22 09:29 UTC, Anastasia-Belik commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +      <img className={cx('cover')} src={data.cover}/>
не хватает обязательного атрибута alt, поскольку картинка смысловой нагрузки не несет, думаю можно туда просто захардкодить "Пресс-релизы"

2021-11-30 19:31 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.module.css
> +    "  .        text";
@Anastasia-Belik Настя, спасибо за комментарий и за action plan! Поправила. В макете кнопка Скачать пресс-релиз находится ближе к левому краю, чем лейбл "Выберите год фестиваля", но это может быть и случайная ошибка.

2021-11-30 19:31 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +        <Droplist
После импорта обновленного дроплиста и фиксов под него все работает корректно

2021-11-30 19:33 UTC, anecheka commented on src/components/for-press-press-releases-view/for-press-press-releases-view.tsx
> +      <img className={cx('cover')} src={data.cover}/>
Добавила `alt`. Но пока не справилась с некстовским Image. Из-за позиционирования абсолютного для обложки на десктопе похоже. Перепробовала все варианты, пока не смогла найти решение.

2021-12-01 07:23 UTC, Anastasia-Belik approved these changes
Привет! 

По верстке все выглядит хорошо. Дроплист теперь работает как надо. Здорово, что ты обратила внимание не необходимость изменения картинки. 

Чтобы ускорить процесс сама немного отрефакторила компонент в [этом коммите](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/142/commits/72dd758e67c35fdca14029b5a76814b12437923a). Что изменилось:

1. Добавила Image. В документации написано, что контейнер, в котором содержится Image, обязательно должен иметь position: relative. Чтобы спозиционировать этот элемент абсолютно, не обойтись без еще одной обертки. Добавила ее.
2. Добавила isMobile в dependencies useEffect, т.к. при изменении вьюпорта не подтягивался выбранный пресс-релиз и на мобилке при перезагрузке было написано, что пресс-релиз не найден.
3. Убрала лишнюю обертку data в интерфейсе
4. Добавила альтернативный мок в формате ts вместо json, по нему удобнее отслеживать корректность типов. Поправила типы, т.к. на них ругался сторибук и проект не собирался. Не знаю насколько это было полезное действие, т.к. когда придет схема от бэка там все может поменяться. Но пока с такими типами и моками все собирается корректно. 

Сейчас все выглядит по макету и билдится. Можно собирать страничку.

2021-12-01 19:51 UTC, merged