Event card
Studio-Yandex-Practicum/lubimovka_frontend pull request #15
Opened 2021-09-18 15:54 UTC by RonWinchester

Карточка задачи в [Notion](https://www.notion.so/4b33530b19c44b1aa1151e3bd16a486a?v=84023778e1024506b75f0af4321bfba2&p=6bded2be618646219265243b1bf79267) 

Компонент "карточка события". Кнопка условная, её не реализовывал.

2021-09-18 21:21 UTC, chechenev commented on src/components/ui/Event-card/event-card.tsx
> +    <>
Кажется, здесь не нужен фрагмент и он лишь лишняя обертка здесь

2021-09-20 12:24 UTC, borodulex reviewed
Все четко, поправить шороховатости и огонь)

И еще, мы договорились для имен файлов компонентов использовать kebab-case. Не нужно в имени папки компонента использовать заглавные буквы)

2021-09-20 12:24 UTC, borodulex commented on src/components/ui/Event-card/event-card.module.css
> +  object-fit: contain;
А так точно лучше, чем cover?

2021-09-20 12:24 UTC, borodulex commented on src/components/ui/Event-card/event-card.module.css
> +  font-family: 'PP Neue Machina', 'Helvetica Neue', Helvetica, Arial, sans-serif;
Уже подвезли миксины для текстов и заголовков в том числе, это относится ко всем текстам дальше

2021-09-20 12:24 UTC, borodulex commented on src/components/ui/Event-card/event-card.module.css
> +  max-width: 127px;
Странно задавать ширину в данном случае, лучше уж всему столбцу задать) Относится ко всем столбцам

2021-09-20 12:24 UTC, borodulex commented on src/components/ui/Event-card/event-card.module.css
> +  height: 31px;
Смущают фиксированные размеры, если представить, что там немного сменится имя кнопки, то получится overflow текста

2021-09-20 12:34 UTC, borodulex commented
И еще, не вижу, чтобы была возможность убрать border-top у первой карточки. Она же будет использоваться как элемент списка, а в макете у первой карточки нет верхней линии.

2021-09-20 12:35 UTC, borodulex commented on src/components/ui/Event-card/event-card.stories.tsx
> +  title: 'Example/EventСard',
Нужно папку UI указать вместо Example

2021-09-22 10:30 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +    <>
Да, фрагмент уберу.

2021-09-22 10:40 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +.event {
Убрал стили и внешний блок

2021-09-22 10:49 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  width: 100%;
убрал width 100%

2021-09-22 11:14 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  border-top: 1px solid #242424;
Вынес цвета в константы

2021-09-22 11:28 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  object-fit: contain;
Конкретно в этом примере для меня различия между свойствами неочевидны.

2021-09-22 12:29 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  font-family: 'PP Neue Machina', 'Helvetica Neue', Helvetica, Arial, sans-serif;
Исправил. Использовал миксины

2021-09-22 12:59 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  max-width: 127px;
Установил общий max-width  для столбцов

2021-09-22 13:29 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  height: 31px;
Кнопка будет отдельным компонентом. У меня просто пример реализации.

2021-09-22 13:29 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.stories.tsx
> +  title: 'Example/EventСard',
Исправлено

2021-09-24 09:15 UTC, borodulex commented on src/components/ui/Event-card/event-card.module.css
> +  object-fit: contain;
Мне глазу больше приятно, когда все изображения в карточках имеют одинаковый размер)

2021-09-26 09:22 UTC, rkostyuchenko requested changes
Стало гораздо лучше 🚀, но есть еще над чем поработать. Важно, чтобы карточка была не просто похожа на то, что в дизайне, а полностью соответствовала макету. Плюс есть пара мелких улучшений по семантике.
btw Если ты не добавлял зависимостей в проект, `package-lock.json` не должен был попасть в PR.

2021-09-26 09:22 UTC, rkostyuchenko commented on src/components/ui/Event-card/event-card.module.css
> +  align-self: center;
В [дизайне](https://www.figma.com/file/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=723%3A10968) блоки выравниваются по одной линии, а не по центру карточки

![image](https://user-images.githubusercontent.com/46530701/134801158-d8246957-698a-4e12-88be-8c0db3c1bedc.png)

2021-09-26 09:22 UTC, rkostyuchenko commented on src/components/ui/Event-card/event-card.tsx
> +    <div className={styles.content}>
Возможно, тут лучше подойдет семантичный тег `article`

2021-09-28 16:49 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +        {props.img && (
Поправил image. Добавил к деструктуризации

2021-09-28 19:24 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  max-width: 1200px;
Убрал ограничения

2021-09-28 19:38 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  font-size: 28px;
Исправлено здесь и дальше по коду

2021-09-28 19:51 UTC, rkostyuchenko commented on src/components/ui/Event-card/event-card.tsx
> +      <Button
https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/main/src/components/critique-card/critique-card.tsx#L36-L42

2021-09-28 20:08 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  border-top: 1px solid var(--coal);
Как убрать границу над контейнером image? Я не могу "выкинуть" его из общего контейнера? (display: none) например.

2021-09-28 20:09 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  width: 100%;
.imgContainer {
  width: 151px;
}

.image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

Например так?

2021-09-28 20:12 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  @media (max-width: 320px) {
Последний медиазапрос здесь явно лишний - убрал.

2021-09-28 20:14 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +    gap: 0;
После внесения всех изменений перепроверю

2021-09-28 20:17 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +    width: 80%;
Исправил значение

2021-09-28 20:27 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  align-self: center;
Чтобы так выровнять блоки, понадобится вытащить блоки на один уровень? 
![image](https://user-images.githubusercontent.com/60516927/135160686-6b0a468e-9455-4a61-be38-acde068dea3a.png)

2021-09-28 20:29 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.stories.tsx
> +  title: 'UI/EventСard',
Поправил

2021-09-28 20:55 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.stories.tsx
> +    <>
Готово

2021-09-28 21:00 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +import { Button } from '../button/button';
Не совсем понятно к чему твой импорт. Могу еще так переписать `import { Button } from 'components/ui/button/button';`

2021-09-28 21:00 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +interface ICardProps {
Выполнено

2021-09-28 21:02 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +  direct: string;
Выполнено

2021-09-28 21:03 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +    <div className={styles.content}>
Выполнено

2021-09-28 21:25 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +      <ul className={styles.creators}>
Хорошо

2021-09-29 06:24 UTC, rkostyuchenko commented on src/components/ui/Event-card/event-card.module.css
> +  align-self: center;
Не обязательно, все зависит от того, как карточка должна вести себя при переносе строк в заголовке события. Сходу кажется, что тут два варианта:
- сдвигать вниз всю нижнюю строку контента. В таком случае, кажется, оптимально будет переверстать карточку с использованием гридов,
- сдвигать вниз только описание события. Тут достаточно будет добавить отступ в секциях без «заголовков», например, с помощью `padding`.

Кажется, что второй вариант предпочтительнее, потому что не ломает динамику чтения, но, возможно, есть смысл уточнить, как это задумал дизайнер.

2021-09-29 06:29 UTC, rkostyuchenko commented on src/components/ui/Event-card/event-card.module.css
> +  border-top: 1px solid var(--coal);
Вариантов много. Например:
- рисовать границу не на блоке, а на секциях,
- рисовать границу с помощью псевдоэлемента,
- рисовать границу с помощью градиента.

2021-09-29 06:44 UTC, rkostyuchenko commented on src/components/ui/Event-card/event-card.module.css
> +  align-self: center;
Сразу не заметил, но в [макете](https://www.figma.com/file/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=723%3A11306) уже описано поведение карточки. Возможно, есть смысл строить верстку так: 
![image](https://user-images.githubusercontent.com/46530701/135216715-6c813c75-0e00-4e04-abd8-22cd542315f5.png)

2021-09-29 06:50 UTC, rkostyuchenko commented on src/components/ui/Event-card/event-card.tsx
> +import { Button } from '../button/button';
Да, так и надо

2021-10-02 09:20 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.tsx
> +      <Button
Вывод кнопки привязал к пропсу button. Если true - кнопка выводится. Так же,добавил атрибут href для передачи ссылки.

2021-10-03 10:22 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  border-top: 1px solid var(--coal);
Границу убрали

2021-10-03 10:23 UTC, RonWinchester commented on src/components/ui/Event-card/event-card.module.css
> +  align-self: center;
Структура изменена

2021-10-04 18:13 UTC, rkostyuchenko approved these changes

2021-10-04 18:59 UTC, borodulex approved these changes

2021-10-04 19:00 UTC, merged