Donation WIP
Studio-Yandex-Practicum/lubimovka_frontend pull request #156
Opened 2021-11-18 14:48 UTC by yar83

# Страница Donation

### Макеты:
* Фигма десктоп: [Donation desk](https://www.figma.com/file/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=660%3A913)
* Фигма планшет: [Donatin table](https://www.figma.com/file/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=1012%3A22588)

### Помимо AppLayout страница содержит три кастомных компонента:
* **Enthusiasm:** верхний пояснительный текст и рекламный баннер.
* **Opportunity:** описание возможностей, _бонусов и бенефитов_ от ваших донатов
* **Report:** пояснение, что каждая копейка народных денег учтена и пошла на пользу

### Данные компонентов
Пока не известно, в каком виде приходят данные, поэтому они пока замоканы. Файл шаблонных данных лежит в ```/pages/donation/assets/mock-donation-data.json```

Соответвенно:

**Enthusiasm** принимает:
* Текст заголовка
* Пояснительный текст в двух абзацах
* Сноску

**Opportunity** принимает:
* Текс заголовка
* URL картинки
* Массив с микротекстами

**Report принимает**:
* Текст

#### TODO:
- [x] Запилить компонент Enthusiasm
- [ ] Запилить компонент Opportunity
- [ ] Запилить компонент Report

2021-11-19 09:52 UTC, Anastasia-Belik requested changes
Ярослав, выглядит хорошо! Оставила пару замечаний и рекомендаций по тексту. 

Компонент Enthusiasm лучше назвать как-нибудь иначе. Во-первых, из его названия вообще непонятно на какой странице и что он делает, что может ввести в заблуждение людей, которые в дальнейшем будут поддерживать сайт. Во-вторых, сейчас название завязано на тексте, но в будущем текст может поменяться. Предлагаю назвать его DonationPageTitle.

UPD 23.11 Посмотрела остальные компоненты, все супер! Классно, что реализована возожность добавлять любое количество блоков c "возможностями" и картинки в них чередуются. Осталось поправить email и один марджин на мобилке.

Вместо белого квадрата будет виджет для донатов, с ним вопрос пока остается открытым.

2021-11-19 09:52 UTC, Anastasia-Belik commented on src/components/donation-page/enthusiasm/enthuasiasm.module.css
> +}
У нас есть переменная --scale, которая отвечает за ширину экрана. Лучше записать через нее, тогда можно избавиться от медиазапроса, потому что его логика прописана в переменной.
```
.asterisk {
  position: absolute;
  top: calc(-25 * var(--scale));
  left: calc(-25 * var(--scale));
  width: scale(25px);
  height: scale(25px);
}
```

2021-11-19 09:52 UTC, Anastasia-Belik commented on src/components/donation-page/enthusiasm/enthusiasm.stories.tsx
> +General.args = mockData.enthusiasm;
Если добавить эти волшебные строчки, можно убрать сторибучный паддинг в 18px, тогда страница будет отображаться корректнее
```
General.parameters = {
  layout: 'fullscreen'
};
```

2021-11-19 09:52 UTC, Anastasia-Belik commented on src/components/donation-page/enthusiasm/enthusiasm.tsx
> +        </div>
Мы не можем гарантировать, что с бэка всегда будет приходить два абзаца, поэтому лучше генерить их через map. Также нужно добавить класс для `<p>`, потому что сейчас у него присутствуют дефолтные марджины.

2021-11-23 08:47 UTC, Anastasia-Belik commented on src/components/donation-page/report/report.tsx
> +        <span className={cx('reportEmail')}>{email}</span>
email лучше реализовать через InfoLink

2021-11-23 09:04 UTC, Anastasia-Belik commented on src/components/donation-page/opportunities/opportunity/opportunity.module.css
> +    margin: scale(46px 0 0 19px);
у загов на мобилке левый отсутуп 24px

2021-11-23 09:07 UTC, Anastasia-Belik commented on src/components/donation-page/opportunities/opportunity/opportunity.module.css
> +    grid-template-columns: repeat(1, 1fr);
кажется здесь достаточно просто 1fr, без repeat

2021-11-23 10:43 UTC, yar83 commented
> Ярослав, выглядит хорошо! Оставила пару замечаний и рекомендаций по тексту.
> 
> Компонент Enthusiasm лучше назвать как-нибудь иначе. Во-первых, из его названия вообще непонятно на какой странице и что он делает, что может ввести в заблуждение людей, которые в дальнейшем будут поддерживать сайт. Во-вторых, сейчас название завязано на тексте, но в будущем текст может поменяться. Предлагаю назвать его DonationPageTitle.
> 
> UPD 23.11 Посмотрела остальные компоненты, все супер! Классно, что реализована возожность добавлять любое количество блоков c "возможностями" и картинки в них чередуются. Осталось поправить email и один марджин на мобилке.
> 
> Вместо белого квадрата будет виджет для донатов, с ним вопрос пока остается открытым.

-[x] Поменять название компонента с Enthusiasm на DonationPageTitle

2021-11-23 10:49 UTC, yar83 commented on src/components/donation-page/enthusiasm/enthuasiasm.module.css
> +}
- [x] Заменил кастомный расчёт на использование переменной --scale. Проверил. Работает.

2021-11-23 10:54 UTC, yar83 commented on src/components/donation-page/enthusiasm/enthusiasm.stories.tsx
> +General.args = mockData.enthusiasm;
- [x] Сделано.

2021-11-23 10:55 UTC, yar83 commented on src/components/donation-page/enthusiasm/enthusiasm.tsx
> +        </div>
- [x] Разрешилось в процессе рефакторинга.

2021-11-23 10:57 UTC, yar83 commented on src/components/donation-page/opportunities/opportunity/opportunity.module.css
> +    grid-template-columns: repeat(1, 1fr);
- [x] Сделано.
Согласен, вполне достаточно 1fr.

2021-11-23 11:00 UTC, yar83 commented on src/components/donation-page/opportunities/opportunity/opportunity.module.css
> +    margin: scale(46px 0 0 19px);
- [x] Сделано.
Рука дрогнула.

2021-11-23 11:19 UTC, yar83 commented on src/components/donation-page/report/report.tsx
> +        <span className={cx('reportEmail')}>{email}</span>
- [x] Сделано.

2021-11-23 11:37 UTC, Anastasia-Belik approved these changes
Все замечания исправлены, выглядит красиво, ошибок нет, можно мерджить :)

2021-11-23 14:22 UTC, merged