Правка верстки компонентов PageOverlay и Navbar в соответствии с макетом
Studio-Yandex-Practicum/lubimovka_frontend pull request #158
Opened 2021-11-19 09:35 UTC by Kerjanoid

## Описание
Добавление компонента Footer в PageOverlay.
Правка верстки компонента Navbar в соответствии с макетом 

## Ссылка на задачу
[Добавить footer в мобильную навигацию + поправить отступы в шапке](https://www.notion.so/footer-b7943032991148f49fa5a92a8307bb43)

2021-11-25 03:29 UTC, naumch1k reviewed
Оставила несколько комментариев, некоторые моменты были еще до тебя, но может заодно поправить? 

min-width - думается, нужно обязательно - это то, что ломает страницы на 728

2021-11-25 03:29 UTC, naumch1k commented on src/components/footer/footer.module.css
> +    margin-top: 0;
[макет](https://www.figma.com/file/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=975%3A29686)

2021-11-25 03:29 UTC, naumch1k commented on src/components/navbar/navbar.module.css
>    padding: 32px 24px 24px;
scale прорущен?

2021-11-25 03:29 UTC, naumch1k commented on src/components/ui/menu/type/main-navigation.module.css
> +  /* &:not(:last-child) {
Это, наверное, стоит убрать, если не нужно

2021-11-25 03:29 UTC, naumch1k commented on src/components/navbar/section/navbar-section.module.css
>    padding-right: 24px;
scale прорущен?

2021-11-25 03:29 UTC, naumch1k commented on src/components/ui/menu/type/main-navigation.module.css
>  .link {
для 
`font-size: scale(16px);
line-height: scale(22px);` 
есть миксин textSmall

2021-11-27 09:45 UTC, Kerjanoid commented on src/components/footer/footer.module.css
> +    margin-top: 0;
Поправил. Спасибо, что приложила макет.

2021-11-27 19:48 UTC, borodulex requested changes
Гуд, только есть парочка небольших, но критичных недочета, которые стоит исправить 💪

2021-11-27 19:48 UTC, borodulex commented on src/api-typings/models/StaticPages.ts
> + * Для того, чтобы загрузить картинку, перетащите её в поле.
Как-то съезал коммент

2021-11-27 19:48 UTC, borodulex commented on src/components/app-layout/app-layout.tsx
> +            <Footer/>
Футер стоит поместить внутрь OverlayNav. Так лучше семантически, так как тег `<footer>` [представляет из себя футер для ближайшего родителя - секционного элемента](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer). OverlayNav как раз секционный элемент из-за использования `<section>`.

2021-11-27 19:48 UTC, borodulex commented on src/components/app-layout/app-layout.tsx
> +            <Footer/>
Плюс сразу тут приложу, отступ не соответсвует макету

![image](https://user-images.githubusercontent.com/72004032/143719805-5e297ca0-d0ac-4b66-8d87-10555ae08eb2.png)

2021-11-27 19:48 UTC, borodulex commented on src/components/footer/footer.module.css
>    }
Сейчас смотрю, что-то на десктопе футер прям отличается от макета сильно, может стоит сразу в этом ПР подправить?
![image](https://user-images.githubusercontent.com/72004032/143720144-68569b53-2679-4477-b312-86ce46066235.png)

2021-11-27 19:48 UTC, borodulex commented on src/api-typings/models/AuthorForPlay.ts
> +}
Такое не должно неожиданно попадать в ПР

2021-11-27 22:52 UTC, naumch1k commented on src/components/app-layout/app-layout.tsx
> +            <Footer/>
это [этот](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/158#discussion_r756534300) отстут. наверное, его как-то по другомку добавить

2021-11-28 13:39 UTC, Kerjanoid commented on src/components/app-layout/app-layout.tsx
> +            <Footer/>
Поправил.

2021-11-28 18:22 UTC, naumch1k commented on src/components/navbar/section/navbar-section.module.css
> -  @media (min-width: $tablet-portrait) {
упси, я сначала не увидела
стиль дублируется, а еще, как будто он и не нужен: на мобилках - только лого. 
можешь оставить так, я в своем ПР уберу

2021-11-28 18:35 UTC, Kerjanoid commented on src/components/navbar/section/navbar-section.module.css
> -  @media (min-width: $tablet-portrait) {
Спасибо, что заметила. Сейчас поправлю и запушу

2021-11-28 18:40 UTC, Kerjanoid commented on src/components/navbar/section/navbar-section.module.css
> -  @media (min-width: $tablet-portrait) {
Сделано

2021-11-28 18:41 UTC, Kerjanoid commented on src/api-typings/models/AuthorForPlay.ts
> +}
Коммит с этими правками удален. Не имеет отношения к ПР

2021-11-28 18:41 UTC, Kerjanoid commented on src/components/footer/footer.module.css
>    }
Сделано

2021-11-28 18:41 UTC, Kerjanoid commented on src/api-typings/models/StaticPages.ts
> + * Для того, чтобы загрузить картинку, перетащите её в поле.
Коммит с этими правками удален. Не имеет отношения к ПР

2021-11-28 18:47 UTC, borodulex approved these changes
LTGM 🦾

2021-11-28 19:21 UTC, naumch1k approved these changes

2021-11-28 19:28 UTC, rkostyuchenko reviewed
Сча мерджим, но нужен рефакторинг, задачу сделаю завтра, если что пинай в чате.  Лучше вместо добавления лишних элементов футера вынести в отдельный компонент только его нижнюю полосу с копирайтами и прочим. И вот ее использовать и в футере и в мобильном меню.

2021-11-28 19:29 UTC, merged