feat: добавить карточки персон
Studio-Yandex-Practicum/lubimovka_frontend pull request #16
Opened 2021-09-19 16:43 UTC by Anastasia-Belik

Реализовать компонент карточек персон
[Задача в Notion ](https://www.notion.so/Person-s-card-4ef4a140987f44b58bf265cdeb005959)

2021-09-19 17:09 UTC, SkaJazz requested changes
Очень круто! И сторибук, и переменные и всё-всё-всё =)) Посмотри, плз, комментарии, и давай переименуем файлы в kebab-case (persons-card.tsx и т.д.) для унификации

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/persons-card.tsx
> +      <p className={styles.about}>{about}</p>}
Если этот текст может обрезаться - давай добавим сюда атрибут title, чтобы пользователь мог увидеть полный текст в любом случае

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.stories.tsx
> +import { ComponentStory, ComponentMeta } from '@storybook/react';
Очень здорово, что сама разобралась со сторибуком =))

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.module.css
> +  text-overflow: ellipsis;
Эллипсис, к сожалению, не сработает на нескольких строчках - если хочешь его оставить, то нужно воспользоваться решением с line-clamp

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.module.css
> +  background-repeat: no-repeat;
Нужны ли эти значения?

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.module.css
> +  justify-content: center;
Кажется, содержимое кнопки само выровняется по центру

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/persons-card.tsx
> +      <div className={cn(styles[`img_container_${mode}`])}>
Попробуем избавиться тут от обёртки картинки? Например, задать размер самой картинке, а кнопку смещать от её исходного места в контейнере. 

_На всякий случай - это не  обязательно, с контейнером - тоже подойдёт_

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/persons-card.tsx
> +  const mode = participant ? 'participant' : 'volunteer';
Если тут только две опции, то, мб, оставим только свойство participant? А текст "volunteer" добавить только там, где он требуется - в имени класса

2021-09-19 17:09 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.module.css
> +.comment {
Давай попробуем по hover добавить какую-нибудь анимацию. Например, ту же, что и в картинке (.6, 0, .5, 1, 400ms)

2021-09-19 17:18 UTC, Anastasia-Belik commented on src/shared/styles/palette.css
> +  --coal: #242424;
Поправила

2021-09-19 17:24 UTC, Anastasia-Belik commented on src/components/ui/percons-card/persons-card.tsx
> +      <p className={styles.about}>{about}</p>}
Добавила

2021-09-19 17:31 UTC, Anastasia-Belik commented on src/components/ui/percons-card/PersonsCard.module.css
> +  text-overflow: ellipsis;
У меня был план использовать ellipsis, если слово (например, имя) настолько длинное, что не влезает в одну строку. Если одно слово помещается, но целиком имя и фамилия не помещаются, фамилия переносится на следующую строку. В макете видела оба варианта (ФИО в одну или две строки). 

С line-clamp получается оно не будет переноситься на следующую строку, и всегда будет в одну с точками, если не влезает?

2021-09-19 17:34 UTC, Anastasia-Belik commented on src/components/ui/percons-card/PersonsCard.module.css
> +  background-repeat: no-repeat;
Нет, не нужны) Забыла удалить с тех пор, как иконка была background-img (до появления компонента)
Поправила

2021-09-19 17:35 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.module.css
> +  text-overflow: ellipsis;
[Line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) это как раз для ограничения текста количеством строк. 
Для эбаута это точно надо (там много строк предполагается), для имени-фамилии - тоже пойдёт (если там допустимы две строчки)

2021-09-19 17:39 UTC, Anastasia-Belik commented on src/components/ui/percons-card/PersonsCard.module.css
> +  justify-content: center;
![Screenshot from 2021-09-19 20-37-53](https://user-images.githubusercontent.com/79516696/133937307-0820cb20-ef66-41ef-9a63-be21e6376c3d.png)
само не выравнивается, чуть-чуть задрано вверх

2021-09-19 18:05 UTC, Anastasia-Belik commented on src/components/ui/percons-card/PersonsCard.module.css
> +.comment {
Добавила анимацию. На мой взгляд выглядит странненько немного) Либо так и задумано, либо я что-то сделала не так.

2021-09-19 18:11 UTC, Anastasia-Belik commented on src/components/ui/percons-card/persons-card.tsx
> +  const mode = participant ? 'participant' : 'volunteer';
Не совсем поняла, что ты имеешь в виду. От свойства mode еще зависит какие элементы показывать на странице. Плюс, мне кажется, так код будет более понятен тем, кто будет с ним дальше работать.

2021-09-19 18:29 UTC, Anastasia-Belik commented on src/components/ui/percons-card/persons-card.tsx
> +      <div className={cn(styles[`img_container_${mode}`])}>
Избавилась

2021-09-19 19:01 UTC, Anastasia-Belik commented on src/components/ui/percons-card/PersonsCard.module.css
> +  text-overflow: ellipsis;
Сделала

2021-09-20 15:24 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.module.css
> +  text-overflow: ellipsis;
Давай попробуем добавить 3-4 строчки для эбаута. Боюсь, двух для многих случаев может не хватить.

2021-09-20 15:27 UTC, SkaJazz commented on src/components/ui/percons-card/PersonsCard.module.css
> +.comment {
Ага, это из-за того, что не анимированы свойства top и left - давай им тоже добавим анимацию

2021-09-20 15:37 UTC, SkaJazz commented on src/components/ui/percons-card/persons-card.tsx
> +      <div className={cn(styles[`img_container_${mode}`])}>
Кажется, кнопка теперь сильно задрана вверх на мобилках. Посмотри, пожалуйста

2021-09-20 15:37 UTC, SkaJazz reviewed
Добавил комментариев к некоторым изменениям. Про именование классов напишу отдельно

2021-09-20 16:19 UTC, Anastasia-Belik commented on src/components/ui/percons-card/PersonsCard.module.css
> +  text-overflow: ellipsis;
Добавила

2021-09-20 16:29 UTC, Anastasia-Belik commented on src/components/ui/percons-card/persons-card.tsx
> +      <div className={cn(styles[`img_container_${mode}`])}>
Поправила

2021-09-20 16:35 UTC, Anastasia-Belik commented on src/components/ui/percons-card/PersonsCard.module.css
> +.comment {
Поправила, теперь хорошо выглядит)

2021-09-20 17:18 UTC, Anastasia-Belik commented on src/components/ui/percons-card/persons-card.tsx
> +  const mode = participant ? 'participant' : 'volunteer';
Сделала

2021-09-22 04:11 UTC, SkaJazz commented on src/components/ui/percons-card/persons-card.module.css
> +  background-color: #fff; /* var(--beige); */
Вот тут, кажется, нужен именно --beige

2021-09-22 04:13 UTC, SkaJazz submitted a review, later dismissed
Супер! Особенно здорово получился перенос - кучу сложных кейсов учли =)) Исправь, пожалуйста, последнюю переменную (см. коммент) и можно мёрджить

2021-09-22 04:30 UTC, Anastasia-Belik commented on src/components/ui/percons-card/persons-card.module.css
> +  background-color: #fff; /* var(--beige); */
Да, это было временное решение, пока не было переменных цветов.
Поставила правильный

2021-09-22 05:32 UTC, SkaJazz approved these changes
Отлично, можно мёрджить =))

2021-09-22 13:54 UTC, proehavshiy approved these changes
approved

2021-09-22 14:45 UTC, merged