Making News component
Studio-Yandex-Practicum/lubimovka_frontend pull request #166
Opened 2021-11-22 12:55 UTC by PavelEremeev

## Описание
Что делает этот Pull Request?
Сделал компонент News, отвечающий за раздел Новости

## Ссылка на задачу
[Название задачи](ссылка_на_задачу)

2021-11-22 15:25 UTC, Anastasia-Belik requested changes
Паша, супер, что удалось разобраться во всех новых технологиях! Страничка красивая и аккуратная получилась. Давай поправим архитектуру компонента newsList и верстку на мобилке. 

Также из пул-реквеста надо удалить файл package-lock.json

2021-11-22 15:25 UTC, Anastasia-Belik commented on src/components/news-page/news-title/news-title.module.css
> +  padding: scale(59px 287px 16px 720px);
В макете между заголовком и дроплистом на десктопе расстояние в 16px, у тебя есть паддинги по 16px и у заголовка, и у дроплиста, из-за чего в сумме расстояние получается 32px, надо оставить какой-нибудь один. При этом на мобилке, он все-таки 32px, не забудь это поменять в медиазапросе.

2021-11-22 15:25 UTC, Anastasia-Belik commented on src/components/news-page/news-page.tsx
> +import MookNewsData from './assets/mock-data-news.json';
кажется здесь закралась очепятка (Mock)

2021-11-22 15:25 UTC, Anastasia-Belik commented on src/components/news-page/news-page.tsx
> +  const [year, setYear] = useState('2021');
Хорошей практикой является передавать в стейт дефолтным значение текущий год и месяц. Это можно сделать через new Date().getMonth() / new Date().getFullYear(), однако сейчас будет конфликт с дроплистом, т.к. он принимает и возвращает строки, а Date - числа. Дроплист еще в разработке, поэтому пока оставь как есть, но запомни на будущее.

2021-11-22 15:25 UTC, Anastasia-Belik commented on src/components/news-page/news-page.module.css
> +    margin-right: scale(15px);
в макете вроде бы расстояние между кнопками не меняется в зависимости от вьюпорта

2021-11-23 17:02 UTC, PavelEremeev commented on src/components/news-page/news-list/news-list.module.css
> +  }
Ок, поправлю. Спасибо!

2021-11-23 17:10 UTC, PavelEremeev commented on src/components/news-page/news-title/news-title.tsx
> +};
Да на самом деле сделал ради того, чтобы если в будущем решат как-то сделать шапку более нагруженной (как у других разделов) то это уже будет сидеть в отдельном компоненте. )

2021-11-23 17:10 UTC, PavelEremeev commented on src/components/news-page/news-title/news-title.module.css
> +  padding: scale(59px 287px 16px 720px);
Ок поправлю! Спасибо)

2021-11-23 17:11 UTC, PavelEremeev commented on src/components/news-page/news-page.tsx
> +import MookNewsData from './assets/mock-data-news.json';
Дааааа! 😁

2021-11-23 17:11 UTC, PavelEremeev commented on src/components/news-page/news-page.tsx
> +  const [year, setYear] = useState('2021');
Спасибо, Насть!

2021-11-23 17:11 UTC, PavelEremeev commented on src/components/news-page/news-page.module.css
> +    margin-right: scale(15px);
Да, это я упустил (

2021-11-23 19:34 UTC, PavelEremeev commented on src/components/news-page/news-page.tsx
> +      <NewsList newsCardData={MookNewsData}/>
Ну в моем понимании компонент NewsList как и любой самостоятельный компонент - вроде DropList и того же NewCard - должен придерживаться инкапсуляции. То-есть хранить всю логику и архитектуру в себе. А ты непосредственно можешь его вставить на той или иной странице с нужными параметрами.  Просто сейчас получается что сам компонент NewsList по сути и не нужен потому что логика вынесена наверх. Получается компонент ради компонента. В моем варианте NewsList компонент который ты можешь вставить куда угодно просто прокинув его параметры className и length (реализую в ближайшее время) - и ни разметка ни какие другие обертки тебя не волнует).

2021-11-23 19:35 UTC, PavelEremeev commented on src/components/news-page/news-list/news-list.tsx
> +};
Да, сделаю с использованием cx, ты права!

2021-12-02 05:53 UTC, Anastasia-Belik approved these changes

2021-12-02 05:53 UTC, merged