Tags
Studio-Yandex-Practicum/lubimovka_frontend pull request #18
Opened 2021-09-19 20:20 UTC by gremwiz1

2021-09-20 07:08 UTC, PyotrGrogorchenko approved these changes

2021-09-20 07:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.tsx
> +export const Tags: FC<ITagsProps> = (props) => {
Подозрительно, компонент называется `Tags`, а рендерит один тэг 🤔

2021-09-20 07:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.tsx
> +      {...restTagsProps}
Не уверен, что в этом спреде есть смысл, ведь в интерфейсе компонента только один проп `label`

2021-09-20 07:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.tsx
> +    <div
Может есть смысл подумать о семантике и заменить `div` на что-либо?

2021-09-20 07:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.stories.tsx
> +  title: 'Example/Tags',
`Example` -> `UI`

2021-09-20 07:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.stories.tsx
> +import React from 'react';
Лишний импорт

2021-09-20 07:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.module.css
> +  border: none;
Сейчас при наведении меняется размер блока, не уверен, что это правильное поведение

2021-09-20 07:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.module.css
> +.tags:active {
Стили состояний `hover` и `active` одинаковые, их можно объединить. Но по логике [дизайна](https://www.figma.com/file/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=609%3A1216), кажется, что `active` это на самом деле состояние «выбранности», то есть в компоненте должна быть возможность указать, что тэг выбран, например, с помощью пропа `selected`. Я бы этот момент уточнил

2021-09-20 17:15 UTC, gremwiz1 commented on src/components/ui/tags/tags.tsx
> +    <div
А на что его можно заменить? Просто мне на ум приходит только еще один вариант - <span> - на него поменять?

2021-09-20 17:16 UTC, gremwiz1 commented on src/components/ui/tags/tags.module.css
> +.tags:active {
А у кого можно уточнить?

2021-09-20 17:31 UTC, gremwiz1 commented on src/components/ui/tags/tags.module.css
> +  border: none;
Не смог увидеть изменения размера компонента - смотрел через инструменты разработчика - высота и ширина компонента до наведения и после наведения остаются одинаковыми. Может просто визуально кажется, что меняется размер, так как исчезает border?

2021-09-20 17:42 UTC, gremwiz1 commented on src/components/ui/tags/tags.tsx
> +export const Tags: FC<ITagsProps> = (props) => {
Поправил

2021-09-20 17:43 UTC, gremwiz1 commented on src/components/ui/tags/tags.tsx
> +      {...restTagsProps}
Убрал лишние пропсы

2021-09-20 17:43 UTC, gremwiz1 commented on src/components/ui/tags/tags.stories.tsx
> +  title: 'Example/Tags',
Заменил

2021-09-20 17:43 UTC, gremwiz1 commented on src/components/ui/tags/tags.stories.tsx
> +import React from 'react';
Убрал импорт

2021-09-21 06:58 UTC, PyotrGrogorchenko commented on src/components/ui/tags/tags.module.css
> +.tags:active {
уточню

2021-09-23 12:27 UTC, gremwiz1 commented on src/components/ui/tags/tags.module.css
> +.tags:active {
Добавил пропс selected

2021-09-23 16:08 UTC, brovan-rus requested changes

2021-09-23 16:08 UTC, brovan-rus commented on src/components/ui/tag/tag.module.css
> +  padding: 4px 8px 8px 8px;
Вот здесь скачет размер - у тебя паддинги  4px 7px 7px 7px, а при ховере становятся  4px 8px 8px 8px;, а должны быть одинаковыми.

2021-09-23 17:52 UTC, gremwiz1 commented on src/components/ui/tag/tag.module.css
> +  font-weight: 300;
Добавил миксины

2021-09-23 17:52 UTC, gremwiz1 commented on src/components/ui/tag/tag.module.css
> +  padding: 4px 8px 8px 8px;
Исправил

2021-09-23 17:57 UTC, gremwiz1 commented on src/components/ui/tags/tags.module.css
> +  border: none;
Исправил это поведение

2021-09-23 18:18 UTC, PyotrGrogorchenko commented
Последний коммит странный, много файлов изменено?

2021-09-23 18:35 UTC, gremwiz1 commented
> Последний коммит странный, много файлов изменено?

Нет - для того чтобы применить миксины пришлось подтянуть изменения с главной ветки - поэтому изменилось много файлов.

2021-09-24 15:50 UTC, rkostyuchenko commented on src/components/ui/tags/tags.tsx
> +    <div
Можно и `div` оставить, но, например, если список тегов будет рендериться как `ul`, то логично один тег превратить в `li`. А если тег должен быть интерактивным элементом, то в `button` или `a`. В общем, нужно смотреть в макет и понимать, как компонент будет использоваться.

2021-09-24 16:51 UTC, brovan-rus approved these changes

2021-09-24 16:52 UTC, brovan-rus commented
Единственное что не совсем понятно, почему ругается на конфликт с палитрой?

2021-09-24 17:04 UTC, gremwiz1 commented
> Единственное что не совсем понятно, почему ругается на конфликт с палитрой?

После того как я сделал свою ветку - там меняли что-то в главной ветке в этом файле.

2021-09-25 10:03 UTC, PyotrGrogorchenko reviewed
Почти готово, пара замечаний)

2021-09-25 10:03 UTC, PyotrGrogorchenko commented on src/components/ui/tag/tag.module.css
> +  background: var(--beige);
`background` не нужен, д.б. прозрачным

2021-09-25 10:03 UTC, PyotrGrogorchenko commented on src/components/ui/tag/tag.module.css
> +  @mixin text;
Миксины лучше сверху

2021-09-25 10:03 UTC, PyotrGrogorchenko commented on src/components/ui/tag/tag.module.css
> +.tag:hover {
`.tag:hover` и `.tag_active` нужно объединить и вложить в  `.tag` - `&:hover, &.active{`

2021-09-26 20:16 UTC, gremwiz1 commented on src/components/ui/tag/tag.module.css
> +  background: var(--beige);
Сделал прозрачным

2021-09-26 20:17 UTC, gremwiz1 commented on src/components/ui/tag/tag.module.css
> +  @mixin text;
Сделал миксины сверху

2021-09-26 20:17 UTC, gremwiz1 commented on src/components/ui/tag/tag.module.css
> +.tag:hover {
Сделал вложенность

2021-09-26 20:54 UTC, PyotrGrogorchenko commented on src/components/ui/tag/tag.module.css
> +  &:hover {
В двух блоках одно и тоже почему не объединить?
```
  &:hover, &.active{
    border: 1px solid transparent;
    border-top: none;
    background: var(--coal);
    color: var(--white);
  }
```
и
`className={selected ? cn(styles.tag, styles.active) : cn(styles.tag)}`

2021-09-26 20:54 UTC, PyotrGrogorchenko commented on src/components/ui/tag/tag.module.css
> +  background: transparent;
Можно удалить `background: transparent;` по умолчанию

2021-09-26 22:05 UTC, gremwiz1 commented on src/components/ui/tag/tag.module.css
> +  &:hover {
Исправил

2021-09-26 22:05 UTC, gremwiz1 commented on src/components/ui/tag/tag.module.css
> +  background: transparent;
Убрал

2021-09-26 22:55 UTC, PyotrGrogorchenko approved these changes
Отлично!

2021-09-27 13:57 UTC, brovan-rus submitted a review, later dismissed

2021-09-27 17:07 UTC, PyotrGrogorchenko approved these changes

2021-09-27 17:26 UTC, brovan-rus approved these changes

2021-09-27 17:27 UTC, merged