feat: added fetcher to page blogs
Studio-Yandex-Practicum/lubimovka_frontend pull request #188
Opened 2021-12-01 11:17 UTC by EvgenII2

## Описание
Добавляет запрос к апи на страницу Блог. Отправляет запрос к апи при фильтрации (изменении значений дроплиста - месяц и год).

2021-12-02 06:30 UTC, Anastasia-Belik requested changes
Привет! В целом ты выбрал правильное направление, только надо добавить еще [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering), в next.js при SSR запросы делаются  через него.

2021-12-02 06:30 UTC, Anastasia-Belik commented on src/components/section-title-for-blog/section-title-for-blog.tsx
> +};
Лучше назвать функцию fetchBlogList, т.к. мы запрашиваем список блогов

К месяцу можно не прибавлять +1, я поправила фильтр, теперь он возвращает месяцы от 1 до 12

2021-12-02 06:30 UTC, Anastasia-Belik commented on src/shared/fetcher.ts
> +
console.log(options) надо удалить, он противоречит линтеру

2021-12-02 19:58 UTC, rkostyuchenko commented on src/pages/blog/index.tsx
> +  useEffect(() => {
Я мимо проходил, но расскажите, пожалуйста, почему мы хотим получать данные на клиенте при том что у нас Next.js и SSR из коробки? Дока: https://nextjs.org/docs/basic-features/data-fetching

2021-12-05 07:19 UTC, Anastasia-Belik commented on src/pages/blog/index.tsx
> +  useEffect(() => {
Привет! На страницах со списком блога и новостей есть фильтр по месяцам и годам, эти данные мы и запрашиваем на клиенте с сервера. Вот тут как раз об этом https://yandex-students.slack.com/archives/C02EPRPJ34N/p1638616659016800?thread_ts=1638616214.016600&cid=C02EPRPJ34N

2021-12-08 18:12 UTC, PavelEremeev commented on src/pages/blog/index.tsx
> +      if (blogs !== undefined && blogs?.length >= limit)
Женя, прости ,пожалуйста, что не сделал скролл раньше, чтоб ты его заюзал. Закопался сильно с ним.  Посмотрел твой, работает здорово).

2021-12-09 17:24 UTC, Anastasia-Belik reviewed
Скролл и фильтр работают отлично.

С дизайнером договаривались, что первоначально на странице появлется 12 карточек, затем догружаем еще по 12.

В запросе мы можем отправлять не только limit, но и offset - позицию с которой нам надо отсчитать limit карточек. Сейчас у тебя при каждом запросе приходят в том числе и те карточки, которые мы уже запрашивали ранее. Если будет очень много карточек и юзер будет долго скроллить, карточек в запросе будет приходить все больше и больше, что создает излишнюю нагрузку.

Первоначально страница со всеми карточками должна рендериться на сервере, для этого мы используем getServerSideProps.

запрос будет выглядеть примерно так: 
```
export const getServerSideProps: GetServerSideProps<PaginatedBlogItemListList> = async () => {

  const blogList = await fetchBlogList(12, 0);

  if (!blogList) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      ...blogList
    },
  };
};
```

где 12 - это первоначальное кол-во карточек, а 0 - с какой их начинать отсчитывать. Эти карточки мы передаем в пропс Blog и сразу в 
`const [blogs, setBlogs] = useState<Array<BlogItem>>(props.results);`

Таким образом, когда страница приходит с сервера на ней уже есть 12 карточек.

В фетче, который происходит при скролле, полученные карточки мы добавляем к уже имеющемуся у нас массиву  `setBlogs([...blogs, ...data.results]);`

2021-12-25 15:04 UTC, rkostyuchenko requested changes
Сча непонятно, как увидеть подгрузку записей блога. Добавь, пожалуйста, соответствующие моки.

btw Рекомендую посмотреть на реализацию страниц и работу с данными на страницах ребят из команды. Обычно ждешь всю БЛ во вьюхе, а сча она размазана по нескольких компонентам и понять, что происходит довольно сложно, особенно будучи не в контексте. Плюс нейминг часто сбивает с толку, некоторые места подсветил в комментариях.

2021-12-26 14:52 UTC, PavelEremeev commented on src/pages/blog/index.tsx
> +    const heightFooter = document.querySelector('footer')?.offsetHeight;
В своё время я довольно явно спросил: как должен быть реализован infinite scroll в рамках данного проекта. Ответ был что-то вроде - как угодно. Сейчас вопросики появились к реализации )).

2021-12-26 19:38 UTC, rkostyuchenko commented on src/pages/blog/index.tsx
> +    const heightFooter = document.querySelector('footer')?.offsetHeight;
Хм. А есть пруф со словами «как угодно»? Я предлагал на выбор готовое решение или собственную реализацию с примером. Не оч понятно, почему свобода выбора способа решения задачи === можно написать любой плохой код

2021-12-27 11:10 UTC, PavelEremeev commented on src/pages/blog/index.tsx
> +    const heightFooter = document.querySelector('footer')?.offsetHeight;
Родион, под "как угодно" я подразумевал "хотите пишите сами - хотите берите готовый" )

2022-03-28 12:24 UTC, closed without merging