fix: box-sizing для AnnouncedPlayCard
Studio-Yandex-Practicum/lubimovka_frontend pull request #216
Opened 2021-12-25 15:57 UTC by anecheka

фикс стиля для AnnouncedPlayCard

2022-01-09 11:54 UTC, andpigge commented
Есть предложение.
Интерфейс:
```
export interface IAnnouncedPlayCardProps extends DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement> {
  isPerformance?: boolean;
  date: string;
  title: string;
  team?: TeamEntry[];
  description?: string;
  buttonLink: string;
  imageUrl?: string;
  projectText?: string | null;
  paid?: boolean;
}
```

Наследоваться от интерфейса `DetailedHTMLProps`. В нем уже есть много свойств интерфейса которые можно использовать.
Есть так же другой способ по ссылке, он не подходит, нужен key
https://coderoad.ru/58418950/%D0%92-%D1%87%D0%B5%D0%BC-%D1%80%D0%B0%D0%B7%D0%BD%D0%B8%D1%86%D0%B0-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-DetailedHTMLProps-%D0%B8-HTMLAttributes

Использовать тэг `<time>` вместо `<p>`:
```
 <time dateTime={date} className={cx('date')}>{new Date(date).toLocaleDateString('ru-Ru', { timeZone: 'Europe/Moscow', month: 'long', day:'numeric' })}</time>
<time dateTime={date} className={cx('date')}>{new Date(date).toLocaleTimeString('ru-Ru', { timeZone: 'Europe/Moscow', hour:'numeric', minute:'numeric' })}</time>
```

В `cx `не нужно заворачивать класс в массив, это нужно иногда в `cn `
`<article className={cx('card', className)}>`

2022-01-09 11:59 UTC, andpigge approved these changes
Молодец))

2022-01-12 11:04 UTC, rkostyuchenko commented on src/components/ui/announced-play-card/announced-play-card.tsx
>    buttonLink: string;
JFYI сча ничо править не нужно.
На мой взгляд логичнее было построить верстку таким образом, чтобы первая кнопка всегда отвечала за описание спектакля, а вторая — за условное действие: регистрацию или покупку билетов.
btw Не очень понял из дизайна, что будет, если у спектакля вернется `paid: false`, как в таком случае пользователю понять, как попасть на этот спектакль? Просто куда-то (куда?) прийти ко времени? 🤷‍♂️

2022-01-12 11:04 UTC, rkostyuchenko commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +        {projectText !== null &&
Кажется, `projectText && (...)` достаточно

2022-01-24 18:25 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
>    const creditsRendered = (
Спасибо за комментарии! 
Поправила в этом коммите https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/216/commits/aeb780028530860044a35394ca9aeaaead43a74d

2022-01-24 18:25 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +  projectText?: string | null;
поправила в этом коммите https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/216/commits/aeb780028530860044a35394ca9aeaaead43a74d

2022-01-24 18:27 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +        <div className={cx('description', imageUrl && 'descriptionCoverExists')}>
Вот здесь видимо наивный вопрос будет. Я поняла, что речь только о синтаксисе, самой форме записи, но такой синтаксис не работает, да и не похожий на рабочий: 
cx('description', { imageUrl: 'descriptionCoverExists' })

можешь пояснить?

2022-01-24 18:27 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +          <time dateTime={date} className={cx('date')}>{new Date(date).toLocaleDateString('ru-Ru', { timeZone: 'Europe/Moscow', month: 'long', day:'numeric' })}</time>
готово в новом коммите https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/216/commits/aeb780028530860044a35394ca9aeaaead43a74d

2022-01-24 18:30 UTC, anecheka commented on src/components/afishe-page/regular-events/afishe-regular-events.tsx
>          <AnnouncedPlayCard key={event.id} date={event.date} title={event.title}
готово вот тут https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/216/commits/aeb780028530860044a35394ca9aeaaead43a74d

2022-01-24 18:32 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
>    buttonLink: string;
Свойство` paid `рендерит / не рендерит кнопку Билеты. Если событие не платное, то это читка или мастер-класс, и скорее всего бесплатное мероприятие (билеты не нужны, только регистрация, paid: false).
Ага, тут пока ничего не меняю

2022-01-24 18:32 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +        {projectText !== null &&
исправлено https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/216/commits/aeb780028530860044a35394ca9aeaaead43a74d

2022-01-29 21:59 UTC, rkostyuchenko requested changes

2022-01-29 21:59 UTC, rkostyuchenko commented on src/components/ui/announced-play-card/announced-play-card.module.css
>      width: scale(414px);
На блоке не должно быть размеров и прочей внешней геометрии, за это должен отвечать родитель или микс. Давай уберем фиксированную ширину карточки

2022-01-30 14:48 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.module.css
>      width: scale(414px);
@rkostyuchenko Готово в этом коммите https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/216/commits/d5139d78f608fd9e16f704ab1b2060622e941d58

2022-01-30 14:50 UTC, anecheka commented
@andpigge Рустам, посмотри плиз этот PR. В нем я внесла правки не только в AnnouncedPlayCard, но и в main-events и afishe-regular-events в связи с обновлением свойств AnnouncedPlayCard

2022-02-04 20:51 UTC, merged