Feature/component form input
Studio-Yandex-Practicum/lubimovka_frontend pull request #22
Opened 2021-09-20 15:16 UTC by whodef

2021-09-21 00:05 UTC, brovan-rus commented
Приветствую! 
Конечно хорошо бы хотя бы небольшое описание к pull request видеть. Из того, что увидел:

- Насколько я помню мы договорились файлы / папки с маленькой буквы называть
- Не подключен storybook, поэтому не посмотреть состояние компонента, он точно работает и отображается так, как нужно?
- В интерфейсе прописаны типы String для InputProps, но label нигде не используется, хотя прописан как обязательный. 
- Цвета необходимо сделать через CSS переменные.
- В форме вижу в макете 2 ширины - 360px и 270px, в стилях только max-width 359px
- Вендорные префиксы ставит автопрефиксер, думаю логично пользоваться псевдоэлементом ::placeholder
- На проекте установлен PostCSS Nested, с ним можно удобно сделать вложенные классы
- inputError всегда скрыт
- placeholder всегда прозрачный и в фокусе и без
- по-моему красный цвет ошибки не тот, что в макете

Сделай примеры в storybook разных состояний компонента, тогда можно будет детальнее посмотреть на соответствие макету.

2021-09-21 05:10 UTC, whodef commented
> Приветствую!
> Конечно хорошо бы хотя бы небольшое описание к pull request видеть. Из того, что увидел:
> 
> * Насколько я помню мы договорились файлы / папки с маленькой буквы называть
> * Не подключен storybook, поэтому не посмотреть состояние компонента, он точно работает и отображается так, как нужно?
> * В интерфейсе прописаны типы String для InputProps, но label нигде не используется, хотя прописан как обязательный.
> * Цвета необходимо сделать через CSS переменные.
> * В форме вижу в макете 2 ширины - 360px и 270px, в стилях только max-width 359px
> * Вендорные префиксы ставит автопрефиксер, думаю логично пользоваться псевдоэлементом ::placeholder
> * На проекте установлен PostCSS Nested, с ним можно удобно сделать вложенные классы
> * inputError всегда скрыт
> * placeholder всегда прозрачный и в фокусе и без
> * по-моему красный цвет ошибки не тот, что в макете
> 
> Сделай примеры в storybook разных состояний компонента, тогда можно будет детальнее посмотреть на соответствие макету.

Спасибо за ревью, займусь этим сегодня же. Компонент да, отображается как надо, просто я его не так подключила к проекту. Storybook вообще из внимания выпал.
Красный цвет ошибки действительно не тот, хотя я искала в цветовой палитре. То ли надо подобрать близкий к нему, то ли не внимательно искала и необходимо пересмотреть.

2021-09-23 15:39 UTC, brovan-rus requested changes

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.tsx
> +  formNoValidate?: boolean | undefined;
Насколько я понимаю знак вопроса итак допускает undefined в значение.

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.tsx
> +      <label />
Пустой <label>, так и нужно?

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.tsx
> +      <input onClick={props.onClick} className={cn(styles.input)} name={props.name} type={props.type} placeholder={props.placeholder} minLength={props.minLength} maxLength={props.maxLength} required/
Мы обсуждали, что будем объединять input и textarea в один компонент в зависимости от условий. В свойм [компоненте кнопки](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/button/src/components/ui/button/button.tsx) я сделал вариант, что кнопка может быть button или link.

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.stories.tsx
> +
Круто будет продемонстрировать также состояния инпута, когда форма не валидирована и заполнен placeholder

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.tsx
> +      <span className="inputError">{props.formNoValidate}</span>
Получается, что inputError класс всегда у элемента, а props.formNoValidate, который принимает значения true / false и undefined - текст ошибки. Если текст ошибки в пропсе - то он должен быть, видимо, строкой.

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +
Комментарий лишний?

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +  font-family: "Formular", SansSerif, serif;
Для текста теперь есть миксин @text

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +  border-bottom: 1px solid #242424;
Цвета - css переменные

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +  color: rgba(235, 87, 87, 1);
Этот красный - по макету цвет?

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +  visibility: hidden;
Ошибка всегда скрыта, так как на её элементе всегда висит этот класс. Кроме того, обрати внимание, что для скрытия тоже есть миксин, может быть он в данном случае будет уместен.

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +  top: calc(100% + 5px);
Отступ зависит о размера элемента с ошибкой + 5pх? По макету, вроде просто 4px отступ.

2021-09-23 15:39 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +  margin: 0 0 4px;
margin при таком объявлении 4 числа же должен иметь, а не 3

2021-09-23 15:41 UTC, brovan-rus commented
И у тебя почему то целых 26! файлов изменяется в пул ревесте. Плюс - очень круто было бы прочитать название пул реквеста и информацию о компоненте, как писал Максим https://yandex-students.slack.com/archives/C02EPRPJ34N/p1632318319064400

2021-09-23 15:45 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +}
Ты хочешь спозиционировать .inputError абсолютно относительно этого компонента? Если так, то ему нужен position: relative

2021-09-23 16:37 UTC, whodef commented on src/components/ui/input/input.tsx
> +      <label />
Да, задел на будущее. Может пригодится именно для связывания for и id, но попозже. Я сейчас сомневаюсь, что он нужен.

2021-09-23 16:37 UTC, whodef commented on src/components/ui/input/input.tsx
> +  formNoValidate?: boolean | undefined;
Думаешь? Исправлю тогда.

2021-09-23 16:39 UTC, whodef commented on src/components/ui/input/input.tsx
> +      <input onClick={props.onClick} className={cn(styles.input)} name={props.name} type={props.type} placeholder={props.placeholder} minLength={props.minLength} maxLength={props.maxLength} required/
Да. Здесь сорри за то что не заглянула. Но я учитываю обсуждение ранее (просто руки не добрались сегодня).

2021-09-23 16:41 UTC, whodef commented on src/components/ui/input/input.module.css
> +
Пока не лишний)

2021-09-23 16:42 UTC, whodef commented on src/components/ui/input/input.tsx
> +      <span className="inputError">{props.formNoValidate}</span>
Я только начала заниматься валидацией и есть идеи как это сделать для компонента. Надо будет ещё крепко над этим подумать.

2021-09-23 16:43 UTC, whodef commented on src/components/ui/input/input.module.css
> +  border-bottom: 1px solid #242424;
Кстати, это мне можно идти в палитру цветов, чтобы создать нужные мне цвета в css-еременных? Для валидации надо.

2021-09-23 16:43 UTC, whodef commented on src/components/ui/input/input.module.css
> +  color: rgba(235, 87, 87, 1);
Да.

2021-09-23 16:45 UTC, whodef commented on src/components/ui/input/input.module.css
> +  top: calc(100% + 5px);
Вот я смотрела, там по макету мне попадалось именно 5px. Сдвиг в 1px вряд ли играет роль вселенского масштаба))

2021-09-23 16:45 UTC, whodef commented on src/components/ui/input/input.module.css
> +  margin: 0 0 4px;
Надо глянуть)

2021-09-23 16:47 UTC, whodef commented on src/components/ui/input/input.module.css
> +}
У меня в принципе есть вопрос, что я в storybook не вижу css-стили. И сегодня потратила прилично времени на то, чтобы понять что не так.

2021-09-23 16:49 UTC, whodef commented on src/components/ui/input/input.module.css
> +}
насчёт 26 файлов я в шоке! Я прямо старалась ничего лишнего не задевать и исправляла ТОЛЬКО в своём компоненте. Точно 26??

2021-09-23 18:21 UTC, brovan-rus commented on src/components/ui/input/input.tsx
> +      <label />
Если у тебя ПР ещё в работе, то поставь статус WIP, я делал комменты исходя из того, что ты уже запрашиваешь мердж в main

2021-09-23 18:40 UTC, brovan-rus commented on src/components/ui/input/input.tsx
> +      <span className="inputError">{props.formNoValidate}</span>
Насколько я понимаю, тебе не нужно заниматься непосредственно валидацией, так как это не задача компонента input, а самой формы. Просто предусмотри состояние, когда необходимо показывать ошибку, а уже из формы это состояние будут активировать.

2021-09-23 18:42 UTC, brovan-rus commented on src/components/ui/input/input.module.css
> +  border-bottom: 1px solid #242424;
Не знаю точно, думаю, что можно вводить новые элементы, поставив всех в известность, но это скорее к Петру вопрос. 
А #242424 - это --coal

2021-09-23 19:28 UTC, whodef commented on src/components/ui/input/input.module.css
> +}
В общем, это глюк гитхаба в отображении из-за rebase во время открытого ПР. На самом деле, если будем мержить, то выйдет вот что:
![screenshot-github com-2021 09 23-22_22_58](https://user-images.githubusercontent.com/7266512/134571072-f8b1f579-b020-44d3-be42-de4f24502181.png)

```
$ git diff origin/main | cat
diff --git a/src/components/ui/input/index.ts b/src/components/ui/input/index.ts
new file mode 100644
index 0000000..e3365cb
--- /dev/null
+++ b/src/components/ui/input/index.ts
@@ -0,0 +1 @@
+export * from './input';
diff --git a/src/components/ui/input/input.module.css b/src/components/ui/input/input.module.css
new file mode 100644
index 0000000..470552a
--- /dev/null
+++ b/src/components/ui/input/input.module.css
@@ -0,0 +1,41 @@
+.inputComponent {
+  max-width: 360px;
+}
+
+/* @media (min-width: $mobile-landscape) {
+  max-width: 365px;
+} */
+
+.input {
+  width: 100%;
+  padding: 0 0 8px 0;
+  border: none;
+  border-bottom: 1px solid #242424;
+  margin: 0;
+  background: var(--beige);
+  font-family: "Formular", SansSerif, serif;
+  font-size: 16px;
+  line-height: 22px;
+  outline: none;
+}
+
+/* Атрибут placeholder выводит текст внутри поля формы, который исчезает при получении фокуса */
+.input:focus::placeholder {
+  color: transparent;
+}
+
+.inputError {
+  position: absolute;
+  top: calc(100% + 5px);
+  left: 0;
+  margin: 0 0 4px;
+  background: var(--beige);
+  color: rgba(235, 87, 87, 1);
+  font-size: 12px;
+  line-height: 22px;
+  visibility: hidden;
+}
+
+.inputError:last-of-type {
+  margin-bottom: 0;
+}
diff --git a/src/components/ui/input/input.stories.tsx b/src/components/ui/input/input.stories.tsx
new file mode 100644
index 0000000..79f7d60
--- /dev/null
+++ b/src/components/ui/input/input.stories.tsx
@@ -0,0 +1,37 @@
+import { ComponentStory, ComponentMeta } from '@storybook/react';
+
+import Input from './input';
+
+export default {
+  title: 'UI/Input',
+  component: Input,
+  argTypes: {
+    value: {
+      control: {
+        disable: true,
+      }
+    }
+  }
+} as ComponentMeta<typeof Input>;
+
+const Template: ComponentStory<typeof Input> = (args) => <Input {...args} />;
+
+export const Default = Template.bind({});
+Default.args = {
+  type: 'text',
+};
+
+export const Email = Template.bind({});
+Email.args = {
+  type: 'email',
+};
+
+export const Password = Template.bind({});
+Password.args = {
+  type: 'password',
+};
+
+export const Number = Template.bind({});
+Number.args = {
+  value: 'number',
+};
diff --git a/src/components/ui/input/input.tsx b/src/components/ui/input/input.tsx
new file mode 100644
index 0000000..04ac638
--- /dev/null
+++ b/src/components/ui/input/input.tsx
@@ -0,0 +1,27 @@
+import {FC, InputHTMLAttributes} from 'react';
+
+import cn from 'classnames';
+
+import styles from './input.module.css';
+
+interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
+  name: string;
+  type: string;
+  placeholder: string;
+  formNoValidate?: boolean | undefined;
+  minLength: number;
+  maxLength: number;
+  onClick?: () => void;
+}
+
+const Input: FC<InputProps> = (props) => {
+  return (
+    <div className={cn(styles.inputComponent)}>
+      <label />
+      <input onClick={props.onClick} className={cn(styles.input)} name={props.name} type={props.type} placeholder={props.placeholder} minLength={props.minLength} maxLength={props.maxLength} required/>
+      <span className="inputError">{props.formNoValidate}</span>
+    </div>
+  );
+};
+
+export default Input;

```

2021-09-23 19:32 UTC, whodef commented on src/components/ui/input/input.module.css
> +}
```
$ git diff --name-only origin/main
src/components/ui/input/index.ts
src/components/ui/input/input.module.css
src/components/ui/input/input.stories.tsx
src/components/ui/input/input.tsx

```

2021-09-24 12:51 UTC, whodef commented on src/components/ui/input/input.module.css
> +  margin: 0 0 4px;
При объявлении 3-х чисел, а не четырёх, среднее число будет отвечать за лево-право.
Таким написанием я обозначила только bottom.

2021-09-25 19:54 UTC, PyotrGrogorchenko reviewed
В целом зорошо, но есть над чем поработать)

Объединить в один компонент `input` и `textarea` полхая идея, у них разные пропсы. Лучше экспортировать 2 компонента, которые используют один css. Компонент переименоватть в `text-field`.
Все использыемые свойства можно не указывать вручную, они есть в `InputHTMLAttributes<HTMLInputElement>`
В компоненте можно заполнить их с помощью `...restProps`

2021-09-25 19:54 UTC, PyotrGrogorchenko commented on src/components/ui/input/input.tsx
> +      <label />
Думаю пока не нужен, нужно удалить

2021-09-25 19:54 UTC, PyotrGrogorchenko commented on src/shared/styles/palette.css
> +  --validate-color: rgba(235, 87, 87, 1);
Лучше по аналогии `--red` назвать)

2021-09-25 19:54 UTC, PyotrGrogorchenko commented on src/components/ui/input/input.module.css
> +  background: var(--beige);
`background` не нужен, прозрачный должен быть

2021-09-25 19:54 UTC, PyotrGrogorchenko commented on src/components/ui/input/input.module.css
> +  @mixin text;
миксины лучше в начале

2021-09-25 19:54 UTC, PyotrGrogorchenko commented on src/components/ui/input/input.tsx
> +      <span className="inputError">{props.formNoValidate}</span>
`"inputError"` нужно одинарные кавычки

2021-09-25 19:54 UTC, PyotrGrogorchenko commented on src/components/ui/input/input.tsx
> +interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
Все пропсы можно убрать, они есть в `InputHTMLAttributes<HTMLInputElement>`
Сделать `const { ...restButtonProps } = props;`
В инпуте `{...restButtonProps}` и оставить только `className`

2021-09-29 19:36 UTC, PyotrGrogorchenko reviewed
Есть над чем поработать)
В компоненты `input` и `textarea` нужно добавить свойства для отображения ошибки и добавить их в storybook
В css textFieldComponent у меня получилось выстроить в колонку с помощью flex, без этого отображение было не корректным

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.module.css
> +.textFieldComponent {
Думаю стоит с помощью flex выстроить в колнку, у меня только так получилось

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.module.css
> +  margin: 0;
Строка лишняя

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.module.css
> +  position: absolute;
Это не нужно
```
  position: absolute;
  top: 4px;
  left: 0;
  margin-bottom: 4px;
```
Это нужно 
`margin-top: 4px;`

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.module.css
> +  background: var(--beige);
Не нужен, должен быть прозрачным

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.module.css
> +  &:last-of-type {
Зачем это? мне кажется это не нужно
```
  &:last-of-type {
    margin-bottom: 0;
  }
```

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +  formNoValidate?: boolean;
Не нужно
`formNoValidate?: boolean;`
Нужно
```
  valid?: boolean
  errorMessage?: string
```

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +  const {...restProps} = props;
Нужно получить `valid` и `errorMessage`

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +      <span className='error'>{props.formNoValidate}</span>
Здесь так
```
      <input className={cn(styles.textField)} formNoValidate {...restProps}/>
      {!valid && errorMessage && <span className={cn(styles.error)}>{errorMessage}</span>}
```

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +  formNoValidate?: boolean;
Не нужно
`formNoValidate?: boolean;`
Нужно
```
  valid?: boolean
  errorMessage?: string
```

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +  const {...restProps} = props;
Нужно получить `valid` и `errorMessage`

2021-09-29 19:36 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +      <span className='error'>{props.formNoValidate}</span>
Здесь так
```
      <textarea className={cn(styles.textField)} {...restProps} />
      {!valid && errorMessage && <span className={cn(styles.error)}>{errorMessage}</span>}
```

2021-09-29 20:00 UTC, whodef commented on src/components/ui/text-field/text-field.module.css
> +  margin: 0;
какая строка?

2021-09-29 20:05 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.module.css
> +  margin: 0;
margin: 0;

2021-09-29 20:26 UTC, whodef commented on src/components/ui/text-field/text-field.module.css
> +  &:last-of-type {
Даже спорить не буду, но почему-то необходимо было, уже не помню почему. В любом случае, дописать что-либо когда-либо не будет проблемой.

2021-09-29 20:35 UTC, whodef commented
А, в сторибук не добавила для отображения ошибки...

2021-09-29 20:43 UTC, PyotrGrogorchenko reviewed
Почти готово)
В storybook новые свойства нужно добавить

2021-09-29 20:43 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/input.stories.tsx
> +  placeholder: 'Введите e-mail'
Для демонстрации
```
  valid: false,
  errorMessage: 'Проверьте правильность e-mail'
```

2021-09-29 20:43 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/input.stories.tsx
> +export const Default = Template.bind({});
Думаю можно оставить один пример Email, его достаточно

2021-09-29 20:43 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/textarea.stories.tsx
> +  placeholder: 'Введите описание пьесы'
Для демострации
```
  valid: false,
  errorMessage: 'Описание пьессы не ввдено'
```

2021-09-29 20:45 UTC, whodef commented on src/components/ui/text-field/input.stories.tsx
> +export const Default = Template.bind({});
Да не, пусть будет все три) Это же в конце концов просто демонстрация)

2021-09-29 20:46 UTC, whodef commented on src/components/ui/text-field/input.stories.tsx
> +  placeholder: 'Введите e-mail'
ага, я уже сделала, только запушить осталось, спасибо))

2021-09-29 20:51 UTC, PyotrGrogorchenko reviewed
Комментарии не нужны)

2021-09-29 20:51 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/textarea.stories.tsx
> +  //errorMessage: 'Описание пьессы не ввдено'
Комментарии не нужны

2021-09-29 20:57 UTC, PyotrGrogorchenko submitted a review, later dismissed
Готово! Поздравляю!

2021-09-30 08:57 UTC, brovan-rus commented on src/components/ui/text-field/text-field.module.css
> +
У тебя максимальная ширина задана как 360px, в макете также, но почему то в storybook на десктопе выходит 365px. Скрины прилагаю. 
![image](https://user-images.githubusercontent.com/75038221/135419379-8c41dcef-a187-4ace-8a3d-0351a5e3d785.png)
![image](https://user-images.githubusercontent.com/75038221/135419458-5848740f-ca66-4e92-a403-10af1a1d1102.png)

Также высота по макету должна быть 30px, а у тебя 38.6px, проверь отступы. Скрины прилагаю.
![image](https://user-images.githubusercontent.com/75038221/135419886-6b3d55bb-d6a5-4756-a828-5575a58cc08f.png)
![image](https://user-images.githubusercontent.com/75038221/135419948-d3c4f2eb-f021-4c2b-88e8-4e13d1f96548.png)

2021-09-30 08:57 UTC, brovan-rus commented on src/components/ui/text-field/text-field.module.css
> +  }
Также увидел реализацию только широкого инпута, реализацию узкого инпута не увидел. В макете 2 варианта, насколько я понимаю
- шириной 360px (как у тебя, только тут почему то максимальная ширина у мобильных 365px
- шириной 270px (реализации не увидел, возможно необходимо дать пользователю выбрать ширину или вообще самому её задавать).
Скрин макета прилагаю. 
![image](https://user-images.githubusercontent.com/75038221/135420612-80b9d58f-a765-404e-9737-d15968a36460.png)

2021-09-30 09:04 UTC, whodef commented on src/components/ui/text-field/text-field.module.css
> +  }
Правильно понимаю, что это значение 270px по стайлгайду, а не по макет? По макету 360 и 365.
Стайлгайд нужен для стилей, показывает поведение, а не его параметры. Или нет???

2021-09-30 19:15 UTC, PyotrGrogorchenko reviewed
Наверное лучше пропсы добавить и управлять шириной/высотой контейнера?

2021-09-30 19:15 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/input.stories.tsx
> +  errorMessage: 'Введите имя и фамилию',
стоит добавить `width: '300px'`, а то не красиво

2021-09-30 19:15 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +    <div className={cn(styles.textFieldComponent)}>
Наверное лучше пропсы добавить и управлять шириной/высотой контейнера
`<div className={cn(styles.textFieldComponent)} style={{ height: 13, width: 300 }}>`

2021-09-30 19:47 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +    <div className={cn(styles.textFieldComponent)}>
И здесь
```
    <div className={cn(styles.textFieldComponent)} style={{ width }}>
      <textarea className={cn(styles.textField)} {...restProps} style={{ height, ...restProps}}/>
```

2021-09-30 19:49 UTC, PyotrGrogorchenko reviewed
Наверное стоит управлять шириной контейнера и высотой input/textarea

2021-09-30 19:49 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +    <div className={cn(styles.textFieldComponent)}>
Наверное стоит управлять шириной контейнера и высотой инпута
    <div className={cn(styles.textFieldComponent)} style={{ width }}>
      <input className={cn(styles.textField)} formNoValidate {...restProps} style={{ height: 13, ...restProps }}/>

2021-09-30 20:00 UTC, whodef commented on src/components/ui/text-field/text-field.tsx
> +    <div className={cn(styles.textFieldComponent)}>
c textarea этот номер не проходит)

2021-09-30 20:01 UTC, whodef commented on src/components/ui/text-field/text-field.tsx
> +    <div className={cn(styles.textFieldComponent)}>
с инпутом проходит ок, когда в пропсы прописываешь

2021-09-30 20:06 UTC, whodef commented on src/components/ui/text-field/text-field.tsx
> +    <div className={cn(styles.textFieldComponent)}>
могу ...restProps для textarea прописать, и можно делать что хочешь потом
```
    <div className={cn(styles.textFieldComponent)} style={{ ...restProps }}>
      <textarea className={cn(styles.textField)} {...restProps} style={{ height, ...restProps}}/>
```

2021-09-30 20:06 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +    <div className={cn(styles.textFieldComponent)}>
Нужно свойства добавить
```
  width?: string;
  height?: string;
```
и получить их
```
  const {
    valid,
    errorMessage,
    width,
    height,
    ...restProps
  } = props;

```

2021-09-30 20:11 UTC, whodef commented
Ребята, давайте определимся с milestone и definition of done для этого PR и поехали далее.

2021-09-30 20:30 UTC, PyotrGrogorchenko reviewed
Остталось сделать возможным управлять шириной и высотой компонентов пропсами и продемонстрировать это в storybook)

2021-09-30 20:30 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/input.stories.tsx
> +  width: '360px',
Здесь и ниже нужно дабавить `height: '14px'`

2021-09-30 20:30 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +  errorMessage?: string;
Здесь нужно добавить
```
  height?: string;
  width?: string;
```

2021-09-30 20:30 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +  const { valid, errorMessage, ...restProps} = props;
Здесь так
`const { valid, errorMessage, height = 71, width, ...restProps} = props;`

2021-09-30 20:30 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.tsx
> +      <textarea className={cn(styles.textField)} {...restProps} style={{ height: 71, ...restProps}}/>
Здесь так
`<textarea className={cn(styles.textField)} {...restProps} style={{ height, ...restProps}}/>`

2021-09-30 20:30 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/textarea.stories.tsx
> +  errorMessage: 'Описание пьесы не введено',
Здесь нужно добавить
```
  width: '300px',
  height: '100px'
```

2021-09-30 21:15 UTC, PyotrGrogorchenko commented on src/components/ui/text-field/text-field.module.css
> +
`background-color: transparent;` нужно

2021-10-01 09:33 UTC, brovan-rus approved these changes
По-моему всё хорошо )

2021-10-01 09:35 UTC, chechenev approved these changes

2021-10-01 09:36 UTC, merged