Page main api
Studio-Yandex-Practicum/lubimovka_frontend pull request #225
Opened 2022-01-11 14:53 UTC by andpigge

## Описание
api для страницы main.
Некоторые компоненты были отрефакторины

## Ссылка на задачу
[main api](https://www.notion.so/main-api-6a0e245eae4f47bf92233f5cad87e74f)

2022-01-11 17:31 UTC, whodef reviewed
Большая работа проделана, но у меня возникла ошибка при переключении на твою ветку. При запуске без моков.

![Screenshot from 2022-01-11 19-26-21](https://user-images.githubusercontent.com/7266512/148992280-8230822d-f41a-42a2-abf0-97a7d8042084.png)

2022-01-11 17:38 UTC, PyotrGrogorchenko requested changes

2022-01-11 17:38 UTC, PyotrGrogorchenko commented on src/pages/index.tsx
> +  // if (!data || !partners) {
Комментарии не нужны

2022-01-11 17:38 UTC, PyotrGrogorchenko commented on src/pages/index.tsx
> +/* eslint-disable import/order */
Эти строки не нужны, можно без них

2022-01-11 17:38 UTC, PyotrGrogorchenko commented on src/components/partners/partners.tsx
> +/* eslint-disable import/no-unresolved */
Эти строки не нужны, можно без них

2022-01-13 17:40 UTC, whodef requested changes

2022-01-13 17:40 UTC, whodef commented on src/components/main-page/title/main-title.module.css
> +    padding: scale(18px 24px 0);
Необходимо оставить отступ вниз на мобильной версии:
`padding: scale(18px 24px);`

2022-01-13 17:40 UTC, whodef commented on src/components/main-page/banners/banner/banner-item.module.css
> +.banner {
В этом компоненте нужно будет предусмотреть, если будет много текста, то наверное таки задать `overflow: hidden;` чтобы можно было прочитать текст уже нажав на кнопку.

2022-01-13 17:40 UTC, whodef commented on src/components/main-page/banners/banner/banner-item.module.css
> +.banner {
А с отступами внизу, когда не сильно прилипает картинка к границе, то выглядит и правда лучше. Это нужно оставить. :)

2022-01-14 11:37 UTC, andpigge commented on src/components/main-page/archive/main-archive.module.css
>    overflow: hidden;
а в чем проблема? я же исправил баг про который ты говорила

2022-01-15 14:01 UTC, andpigge commented on src/components/main-page/banners/banner/banner-item.module.css
> +.banner {
точно, спасибо.
Увеличу до 500px и добавлю overflow
![image](https://user-images.githubusercontent.com/54473049/149624400-d41f1af8-dc81-4b0e-a850-ee18dbe19b09.png)
![image](https://user-images.githubusercontent.com/54473049/149624412-977cf0ac-6fcd-43de-9c7e-b95c7f3568f9.png)

2022-01-15 14:04 UTC, andpigge commented on src/components/main-page/archive/main-archive.module.css
>    overflow: hidden;
можешь попробовать сделать как хочется

2022-01-15 14:06 UTC, andpigge commented on src/components/main-page/title/main-title.module.css
> +    padding: scale(18px 24px 0);
там еще будут события.
Надо подумать. Сетку неправильно сделал.

2022-01-16 15:12 UTC, whodef requested changes

2022-01-16 15:12 UTC, whodef commented on src/components/main-page/banners/banner/banner-item.module.css
> +  max-hight: scale(384px);
Здесь закралась синтаксическая ошибка. Попробовала ещё со значением 165, вроде так лучше, но на твоё усмотрение. По крайней мере кнопка не выходит за границы картинки и не создаёт визуально беспорядок.
   ` max-height: calc(var(--scale) * 165);`

2022-01-26 14:16 UTC, PyotrGrogorchenko submitted a review, later dismissed

2022-01-26 14:27 UTC, whodef approved these changes
Вроде норм! Если уж будет что подправить, то это можно сделать попозже.

2022-01-26 14:53 UTC, merged