fix/переписал droplist по замечаниям
Studio-Yandex-Practicum/lubimovka_frontend pull request #236
Opened 2022-01-24 19:47 UTC by andpigge

## Описание
Что делает этот Pull Request?

## Ссылка на задачу
[Название задачи](ссылка_на_задачу)

2022-01-25 07:12 UTC, rkostyuchenko reviewed
1. Расскажи, пожалуйста, зачем нужны два коллбека? В моем мире достаточно одного более очевидного – onChange, в который будут передаваться значения выбранных элементов.
2. Мб `selectList` лучше назвать более очевидно, например, `selectedOptions` или `value`?
3. Сча не очень понятно, как без костылей реализовать сброс выбранного значения для списка с модификатором `single`
4. Проблема с тем, что нужно постоянно матчить текст элемента меню с его значением при передаче в дроплист, а потом обратно в коллбеке никуда не делась, а раз мы готовы глобально менять интерфейс компонента, хочется сразу ее решить. Другими словами компонент может иметь примерно такой интерфейс:
```
type DroplistOption = {
  value: string | number,
  text: string,
}

interface IDroplistProps {
  type: 'single' | 'multiple'
  options: DroplistOption[]
  selectedOptions: DroplistOption[]
  onChange: ((selectedOptions: DroplistOption[]) => void)
  placeholder: string
}
```

2022-01-25 07:12 UTC, rkostyuchenko commented on src/components/ui/droplist/list/list.tsx
> +export const List: FC<IDroplistItemsProps> = ({ type, selectList, item, handlerClick }): JSX.Element => {
Нейминг не оч. От компонента с именем `list` ждешь, что он отрендерит список

2022-01-25 07:12 UTC, rkostyuchenko commented on src/components/ui/droplist/container-button/container-button.tsx
> +        className={cx('iconArrowDown', { 'rotateUp': activeDropdown })}
Кавычки в именах полей здесь не нужны

2022-01-25 13:21 UTC, andpigge commented on src/pages/index.tsx
> +  // const [selectList, setSelectList] = useState<string>('Декабрь');
Для тестирования

2022-01-25 13:23 UTC, andpigge commented on src/components/ui/droplist/list-selected/list-selected.tsx
> +      {Array.isArray(selectList) && selectList.map((item, i) => (
Мне он не нужен)

2022-01-26 18:29 UTC, rkostyuchenko commented on src/components/ui/droplist/droplist.tsx
> +  options: string[]
Хм, а норм, что `options` это массив строк, а `selectedOptions` – `DroplistOption[]`?

2022-01-26 18:52 UTC, rkostyuchenko commented on src/components/ui/droplist/list-selected/list-selected.tsx
> +      {Array.isArray(selectList) && selectList.map((item, i) => (
Теперь мы разрешаем передавать в проп только массив, кажется, проверка `Array.isArray()` лишняя

2022-01-26 18:58 UTC, rkostyuchenko commented on src/pages/index.tsx
> +  // const [selectList, setSelectList] = useState<string>('Декабрь');
Не оч понимаю, как комментарии в коде основной ветки помогут тебе с тестированием? А вот то что бесполезный код (а все комменты в ПР именно такие), мерджить не стоит — очевидно.
https://parpalak.com/blog/2008/01/07/Commented_code

2022-01-27 12:42 UTC, andpigge commented on src/components/ui/droplist/droplist.tsx
> +  options: string[]
не норма. исправил

2022-02-05 12:33 UTC, rkostyuchenko commented on src/components/ui/droplist/droplist.tsx
> +        value={type === 'single' && selectedOptions[0].text || placeholder || 'Все'}
Сейчас, если в selectedOptions придет пустой массив, компонент сломается

2022-02-05 12:33 UTC, rkostyuchenko commented on src/components/ui/droplist/list-selected/list-selected.tsx
> +      {Array.isArray(selectList) && selectList.map((item, i) => (
Уберем из кода?

2022-02-05 12:33 UTC, rkostyuchenko commented on src/components/ui/droplist/container-button/container-button.tsx
> +        className={cx('iconArrowDown', { 'rotateUp': activeDropdown })}
Поправим?

2022-02-05 12:34 UTC, rkostyuchenko requested changes
Нужны правки и ребейз

2022-02-05 12:37 UTC, rkostyuchenko commented
btw Давай постараемся избегать бесполезных коммит-месседжей и будем готовить ПР к ревью. Вот так не норм:
![изображение](https://user-images.githubusercontent.com/46530701/152642396-fdd7288f-87e1-4af5-9bdc-86cc6dff5744.png)

2022-02-07 13:01 UTC, andpigge commented on src/pages/index.tsx
> +  // const [selectList, setSelectList] = useState<string>('Декабрь');
это не окончательная версия.
В окончательной как ты видишь я все удалил

2022-02-07 13:05 UTC, andpigge commented on src/components/ui/droplist/list-selected/list-selected.tsx
> +      {Array.isArray(selectList) && selectList.map((item, i) => (
![image](https://user-images.githubusercontent.com/54473049/152793297-c42fbdc9-a2c6-4c3b-a700-a5522537c1d5.png)
Убрал же

2022-02-07 13:07 UTC, andpigge commented on src/pages/index.tsx
> +  // const [selectList, setSelectList] = useState<string>('Декабрь');
И никто никогда не мержил закомментированный код.

Участки кода в комментариях — удобный прием при отладке. В окончательной версии в комментариях должны оставаться только пояснения.

2022-02-07 13:18 UTC, andpigge commented on src/components/ui/droplist/container-button/container-button.tsx
> +        className={cx('iconArrowDown', { 'rotateUp': activeDropdown })}
Какие имена полей?

2022-02-08 20:00 UTC, rkostyuchenko commented on src/components/ui/droplist/droplist.tsx
> +        value={type === 'single' && selectedOptions[0].text || placeholder || 'Все'}
Проблема актуальна

2022-02-08 20:07 UTC, rkostyuchenko commented on src/pages/index.tsx
> +  // const [selectList, setSelectList] = useState<string>('Декабрь');
Не понимаю, что помешает комментариям из этого PR попасть в основную ветку кода. Открытый ПР означает готовность кода к мерджу (на твой взгляд) или как ты говоришь, окончательную версию. Если это не так, ПР следует перевести в черновик (Draft).

2022-02-11 18:48 UTC, rkostyuchenko submitted a review, later dismissed

2022-02-11 19:38 UTC, merged