Рефакторинг страница History
Studio-Yandex-Practicum/lubimovka_frontend pull request #238
Opened 2022-01-26 23:06 UTC by gremwiz1

## Описание
Отрефакторил страницу. Сейчас данные погружаются в основном с бэка (за исключением статических данных, которые бэк пока для этой страницы не реализовал)

## Ссылка на задачу
[Интеграция с бэкендом - страница History](https://www.notion.so/Frontech-52aae4efcc1743f58f4abf64bf7357ff?p=b1e70a3359754dad85c6ad90585c5c2c)

2022-01-29 11:29 UTC, whodef requested changes

2022-01-29 11:29 UTC, whodef commented on src/components/history-page/history-page.tsx
> +const fetchStatistics = async (year: number) => {
Привет, 
это всё надо поднять на уровень выше. А то страница не работает, невозможно перейти из меню.

2022-01-29 15:16 UTC, PyotrGrogorchenko commented on src/components/history-page/history-page.tsx
> +const fetchStatistics = async (year: number) => {
У меня все нормально работает)

2022-01-29 15:17 UTC, PyotrGrogorchenko submitted a review, later dismissed

2022-01-29 15:44 UTC, gremwiz1 commented on src/components/history-page/history-page.tsx
> +const fetchStatistics = async (year: number) => {
> Привет, это всё надо поднять на уровень выше. А то страница не работает, невозможно перейти из меню.

У меня все нормально запускается

2022-01-29 17:16 UTC, whodef commented on src/components/history-page/history-page.tsx
> +const fetchStatistics = async (year: number) => {
Странно, заработало, всё норм тогда.
Просто не подгружалось... видимо, по каким-то внешним причинам.

2022-01-29 17:16 UTC, whodef approved these changes

2022-01-30 12:51 UTC, andpigge approved these changes
Петр уже проверял. Сделал апрув.

2022-01-30 12:52 UTC, merged