Blog card
Studio-Yandex-Practicum/lubimovka_frontend pull request #24
Opened 2021-09-20 20:44 UTC by proehavshiy

компонент карточки со страницы blog

задача: https://www.notion.so/Blog-card-d4db10307c384084879b29a4cf61051e

* Я все-таки задал максимальное ограничение по высоте изображения в 343px как в макете. Хоть и при фиксированной ширине карточки в сетке изображение и будет сохранять пропорции, но мы не можем предугадать, какого качества и разрешения будут картинки. Соответственно, могут быть непрезентабельные карточки. Что посоветуете здесь? 
* Добавил общий onClick на всю карточку пока, не знаю, какие части карточки должны быть кликабельными. Из макета это не очевидно.
* Добавил в текстовую часть карточки свойства переполнения hyphens: auto; overflow-wrap: break-word; на всякий случай. Если есть еще какие советы в эту сторону, то напишите, пожалуйста.
* Тк карточка не имеет своей ширины, в storybook добавил 3 варианта: дефолтное - без внешней сетки, в сетке и первая по счету карточка (которая должна занимать 2 колонки), много карточек в сетке (сетка - пример, не финальная)

2021-09-21 07:11 UTC, Anastasia-Belik commented
Привет! 

1. Если в текстовой части написать очень длинное слово, оно выходит за границы карточки. Перенос с hyphens у меня не сработал(( Я бы добавила еще `word-break: break-word;` на всякий случай. https://files.slack.com/files-pri/TPV9DP0N4-F02F9E15R8U/image.png

2. Поле description у тебя выровнено по середине. В макете же, ИМХО, оно занимает 100% ширины и имеет `padding-left: 31px;` . Или там есть какие-то нюансы? https://files.slack.com/files-pri/TPV9DP0N4-F02F381ERGB/image.png

3. У первой карточки, между фото и заголовком есть лишняя пустота. У меня тоже была такая проблема, я ее решала `line-height: 0;` у родительского элемента https://files.slack.com/files-pri/TPV9DP0N4-F02ENGP6CDV/image.png

4. С максимально возможной высотой для изображения поддерживаю

P.S. Имена классов в css пишем в camelCase

2021-09-21 17:49 UTC, proehavshiy commented
@Anastasia-Belik, спасибо за комментарии! 
Возвращаюсь со своими правками:

1. Я читал, что hyphens замена устаревшему word-break. Хотя сейчас внимательнее почитал, и хром, например, hyphens: auto; не поддерживает. Заменил на word-break: break-word;
2. Да, я специально выровнял по середине, тк, если присмотреться, текст в этом блоке так и выровнен, в макете просто это не отображено. Мой способ учитывает отступы слева и справа через width: calc(100% - 31px * 2); align-self: center; Это альтернатива твоему, поведение такое же. Предлагаю оставить так.
3. действительно есть полоса, не заметил ее, спасибо. Чтобы убрать пустоту под картинкой, добавил ей display: block;
4. ок, тогда оставлю ограничение по макс высоте

PS твой не понял, Максим писал, что имена классов же мы пишем, как хотим. У меня через нижнее подчеркивание, например. У других, вижу, тоже нет обязательного camelCase в css. Название папок и файлов в kebab-case. Править в итоге нужно что-то в css? @SkaJazz

2021-09-22 04:54 UTC, Anastasia-Belik commented
Про именование css классов написано в [Проектных решениях](https://www.notion.so/eb5b3d893cbf4e7ab581a65a3c099dfc). Вставляла ссылку в слаке, а сюда она не скопировалась, сорян) И Миша мне писал об этом в моей PR)

По поводу текста. Не могу, к сожалению поменять текст в макете, чтобы показать, попробую описать словами. 
В макете действительно текст выглядит так, будто бы он находится по центру. Но это происходит из-за того, что длинные слова переносятся на новую строку. Плохо, что во всех карточках в макете одинаковый текст и нельзя посмотреть разницу. Если поменять текст в макете, слова будут доходить до правого края (потому что сам блок доходит до конца). Такая логика (с левым отступом у текста) есть по всему макету у разных элементов, в том числе у меня в карточках персон. И там видно, что текст доходит до конца. Мне кажется дизайнер закладывал единую логику по всем сайту. @SkaJazz что думаешь?

2021-09-22 16:48 UTC, proehavshiy commented
@Anastasia-Belik , @SkaJazz , привет! внес правки

- переписал сторибук через декораторы. Ошибок линтера нет
- css в camelCase исправил
- блок description выровнял через padding, как в макете
- колбэк onClick чуть переписал, ошибок линтера теперь нет. Но я еще плаваю в типизации, поэтому не уверен, что правильно сделал. Пропс onClick необязательный, и, если в handleCardClick не выставить условие `onClick ? onClick(evt) : null;`, TS ругается на возможное значение undefined. Возможно, это не лучшая конструкция, как прописать необязательный обработчик клика. Просьба подсказать, как лучше сделать.

2021-09-23 04:39 UTC, Anastasia-Belik approved these changes
Привет! С TS я, к сожалению, не подскажу, т.к. плаваю где-то рядом с тобой) В остальном по компоненту вроде все ок. Единственное, что можно еще сделать, в Сторибуке перенести компонент в раздел "UI", чтобы все компоненты были в одном месте.
```
export default {
  component: BlogCard,
  title: 'UI/Blog Card',
```

2021-09-23 08:43 UTC, proehavshiy commented
@Anastasia-Belik , @SkaJazz , ребята, привет! 

- добавил в storybook `title: 'UI/Blog Card',`, как Настя подсказала
- вернул package-lock.json в изначальное состояние [этим способом](https://stackoverflow.com/questions/39459467/remove-a-modified-file-from-pull-request/44355701#44355701). Вроде, все получилось, предупреждение о конфликте в реквесте пропало. 
- @SkaJazz , жду только проверки/советов по handleCardClick в компоненте, посмотри, пожалуйста, как будет время

2021-09-23 13:20 UTC, SkaJazz requested changes
Очень хорошо! Почти нет замечаний, добавил пару комментариев. 
Но расскажи, пожалуйста, как обрабатываются картинки к постам? Сейчас при любой приходящей картинке иллюстрация горизонтальная. Как получить квадратную и вертикальную?

2021-09-23 13:20 UTC, SkaJazz commented on src/components/ui/blog-card/blog-card.tsx
> +        <img className={styles.img} src={image} alt="изображение пьесы" />
Здесь в альт можно добавлять название пьесы, например "Иллюстрация к пьесе ${title}"

2021-09-23 13:20 UTC, SkaJazz commented on src/components/ui/blog-card/blog-card.tsx
> +  onClick?: (evt: React.MouseEvent) => React.MouseEvent;
Если я правильно понимаю твою идею, то тут достаточно написать

`onClick?: React.MouseEventHandler<HTMLLIElement>;`

А в строке 20: `onClick={onClick}>`

Строки 15-17 можно убрать.
Передача функции работает, эвент доступен

2021-09-23 14:21 UTC, proehavshiy commented on src/components/ui/blog-card/blog-card.tsx
> +        <img className={styles.img} src={image} alt="изображение пьесы" />
вертикальная, горизонтальная или квадратная версии получаются из разрешения конкретной карточки, пропорции сохраняются. Максимум - ограничена высота в 343px, чтобы подстраховаться от слишком некрасивых карточек( мы не знаем, какого разрешения будут приходить картинки). Я добавил в сторибуке отображения карточек с различными разрешениями картинок (Я пока не до конца освоил сторибук, поэтому в одну стори 3 разных картинки поместить пока не могу)

2021-09-23 14:21 UTC, proehavshiy commented on src/components/ui/blog-card/blog-card.tsx
> +  onClick?: (evt: React.MouseEvent) => React.MouseEvent;
супер, спасибо! Скорректировал

2021-09-23 14:21 UTC, proehavshiy commented on src/components/ui/blog-card/blog-card.tsx
> +        <img className={styles.img} src={image} alt="изображение пьесы" />
альт тоже скорректировал

2021-09-25 09:22 UTC, SkaJazz commented on src/components/ui/blog-card/blog-card.tsx
> +        <img className={styles.img} src={image} alt="изображение пьесы" />
Да, всё работает, супер!

2021-09-25 09:24 UTC, SkaJazz reviewed
[Задал вопрос дизайнеру в Ноушене](https://www.notion.so/f2f5c791a32945efb90a7e7c94b5722e?v=435c1b772c4e421bb06467c862a7a798) насчёт заголовка - должен ли он быть ссылкой. Давай дождёмся ответа - на всякий случай, элемент ссылки в [соседнем PR](rontend/pull/21)

2021-10-01 18:22 UTC, SkaJazz reviewed
Собственно, как я писал в группе, давай обернём в ссылки (пока некстовские) картинку и заголовок

2021-10-03 10:08 UTC, proehavshiy commented
1. добавил поддержку миксинов текста и заголовков. Конфликтов в пулреквесте не возникло, все ок
2. переписал кликабельную область со всей карточки через обработчик на кликабельную картинку и заголовок через компонент Link некста. Пришлось пока добавить в css на 43 строке сброс дефолтного подчеркивания ссылке через обращение к тегу. Потом удалю, когда будет готов  [компонент ссылок](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/21) 

В целом мое мнение по кликабельности карточки: [в блоге любимовки в карточках сейчас](https://lubimovka.ru/blog) кликабельны как раз только картинка и заголовок, но ведут они на одну и ту же страницу. Автор у нее не кликабелен. Если логика клика карточки не изменяется (любой клик будет просто вести на статью блога), то предлагаю сделать кликабельной всю карточку целиком, как и было в предыдущей итерации. Это намного удобнее + на мобилках заметно повысит юзабилити. Что скажете, @Anastasia-Belik , @SkaJazz ?

2021-10-04 09:12 UTC, proehavshiy commented
@Anastasia-Belik , @SkaJazz , привет, 
внес финальные правки, посмотрите, пожалуйста, и аппрувните, если все ок

- кликабельная область теперь вся карточка. вся карточка обернута в Link некста
- по ховеру всей карточки срабатывает анимация картинки

компонента [link](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/21) здесь не будет

2021-10-04 12:44 UTC, proehavshiy commented
- поправил css-баг с первой карточкой
- добавил возможность выбирать режим первой карточке (одну колонку `firstCardSizeMode = 'regular'` ей занимать или 2 `firstCardSizeMode = 'big'`). По умолчанию занимает 1

2021-10-05 06:11 UTC, Anastasia-Belik reviewed
Привет! в css еще пару кусочков можно заменить на миксины, отметила в коде. Все остальное супер)

2021-10-05 06:11 UTC, Anastasia-Belik commented on src/components/ui/blog-card/blog-card.module.css
> +  font-weight: 300;
можно заменить на `@mixin headline`

2021-10-05 06:11 UTC, Anastasia-Belik commented on src/components/ui/blog-card/blog-card.module.css
> +  font-weight: 300;
можно заменить на `@mixin text`

2021-10-06 06:58 UTC, SkaJazz reviewed
Согласен с Настей - только проверь, плз, что у тебя последние мэйновские версии миксинов. И отправляем

2021-10-31 12:12 UTC, SkaJazz approved these changes

2021-10-31 14:35 UTC, Anastasia-Belik approved these changes

2021-10-31 14:35 UTC, merged