Button
Studio-Yandex-Practicum/lubimovka_frontend pull request #25
Opened 2021-09-20 22:06 UTC by brovan-rus

Соединил в один компонент все варианты кнопок, образ каждой есть в storybook. 
###Изменения в общих компонентах ###
Переименовал компонент **Button**, используемый для примера в **Button-example**
В компоненте **Icon** добавил экспорт к интерфейсу **IIconProps** для использования типа glyph в интерфейсе своего компонента, думал сделать красивее, буду благодарен за совет. 
###Используемые параметры###:
- **size** Размер кнопки - есть 3 варианта фиксированного размера s, m, l, а также нефиксированный размер, если этот параметр не указывать.
- **iconPlace**  Иконки могут располагаться как слева, так и справа
- **border** есть разные настройки видимых границ - параметр border
- **icon**  название иконки
- **label**  текст кнопки 
- **accent** акцентированный цвет кнопки

2021-09-21 19:42 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +import {FC, MouseEventHandler, ButtonHTMLAttributes} from 'react';
Принято, убрал, заменил на импорт MouseEvent

2021-09-21 19:45 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +  border: 'borderNone' | 'borderTopLeft' | 'borderTopRight' | 'borderBottomLeft' | 'borderBottomRight' | 'borderTop' | 'borderFull';
Принято. сократил, сделал параметры необязательными, а дефолтный добавил только border = 'none', так как остальные параметры могут быть undefined. В случае отсутствия параметра icon или iconPlace иконка не отобразится.

2021-09-21 19:45 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +export default Button;
Поменял дефолтный экспорт на именованный

2021-09-21 19:46 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +  onClick?: () => void;
Добавил, спасибо

2021-09-22 08:29 UTC, rkostyuchenko requested changes

2021-09-22 08:29 UTC, rkostyuchenko commented on src/components/ui/button/button.module.css
> +  width: 240px;
❗️Кроме того, сейчас размеры `s` и `m` отличаются только шириной, один из них лишний. Ширину кнопки должен определять контент, родитель или модификатор, который растянет ее на всю ширину родителя. Сча если текст окажется длинее кнопки, получится не очень 👀

2021-09-22 08:29 UTC, rkostyuchenko commented on src/components/ui/button/button.stories.tsx
> +export const Download = Template.bind({});
Лайк за демо разных состояний кнопки.
btw. Не уверен, что, например, у кнопки «Скачать» должен быть фон.

2021-09-22 08:29 UTC, rkostyuchenko commented on src/components/ui/button/button.tsx
> +  icon?: IIconProps['glyph'];
Возможно, имеет смысл прокидывать сюда компонент вместо строки. Так кнопке не придется знать о внутреннем устройстве компонента иконки, а в кнопку получится положить все, что угодно. Но это тоже, к слову

2021-09-22 08:29 UTC, rkostyuchenko commented on src/components/ui/button/button.tsx
> +    <button
Судя по дизайну, то, что выглядит как кнопка, иногда на самом деле ссылка. Я бы добавил возможность рендерить [next/link](https://nextjs.org/docs/api-reference/next/link) или `button` в зависимости от пропсов.
 btw. [вот](https://github.com/praktikum-beta-team/catcher/blob/develop/src/components/UI/Button/Button.tsx) еще способ реализовать такое.

2021-09-22 08:29 UTC, rkostyuchenko commented on src/components/ui/button/button.module.css
> +.icon {
Сейчас непонятно, зачем позицировать иконку абсолютно. Кроме того, в [макете](https://www.figma.com/file/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=822%3A26082) у иконки есть отступ.

2021-09-22 11:41 UTC, PyotrGrogorchenko commented on src/components/ui/button/button.tsx
> +import styles from './button.module.css';
Такое проавило eslint есть

2021-09-22 11:42 UTC, PyotrGrogorchenko commented on src/components/ui/button/button.tsx
> +  icon?: IIconProps['glyph'];
Не согласен. Зачем предку кнопки знать как рисуется иконка?

2021-09-22 11:54 UTC, rkostyuchenko commented on src/components/ui/button/button.tsx
> +  icon?: IIconProps['glyph'];
А почему он начнет знать? Мы можем передавать в кнопку компонент, который нужно отрендерить на месте иконки, при этом про то, как он рендерится никто снаружи не знает.
В текущем виде мы завязываем кнопку на реализацию компонента Icon, и если она поменяется, все кнопки сломаются, что, кажется, не очень хорошо, как и знание одним компонентом внутреннего устройства другого. [Пример реализации](https://github.com/alfa-laboratory/core-components/blob/master/packages/button/src/Component.tsx#L30-L38) 👀

2021-09-22 12:05 UTC, rkostyuchenko commented on src/components/ui/button/button.tsx
> +import styles from './button.module.css';
#19

2021-09-22 18:24 UTC, brovan-rus commented on src/components/ui/Button-example/Button-example.tsx
> +export const ButtonExample: FC<IButtonProps> = (props) => {
Принято, пример кнопки удалил )

2021-09-22 18:25 UTC, brovan-rus commented on src/components/ui/button/button.module.css
> +  width: 240px;
Принято, вывел отдельно параметр width и className, чтобы можно было задавать извне ширину, когда она фиксированная.

2021-09-22 18:25 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +  accent?: boolean,
Принято, поменял и добавил также view: 'transparent'

2021-09-22 18:26 UTC, brovan-rus commented on src/components/ui/button/button.stories.tsx
> +export const Download = Template.bind({});
Для кнопки «Скачать» теперь использую прозрачный фон

2021-09-22 18:28 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +    <button
Не разобрался с примером - cloneElement, сделал параметр isLink на который возвращается ссылка и параметр href

2021-09-23 12:12 UTC, PyotrGrogorchenko commented on src/components/ui/button/button.tsx
> +  rightAddon?: React.ReactNode;
По прежнему не согласен с такой реализацией. Потомок знает компанент иконки и может передать что угодно. Кнопка должна сама определять свойства иконки в зависимости от пропсов.
Не удалось ограничить тип `leftAddon/rightAddon`. Даже если тип `React.ReactElement<IIconProps, typeof Icon>` можно любой компонент передать, в том числе себя.

2021-09-23 12:45 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +  disabled?: boolean,
Принято, убрал)

2021-09-23 12:46 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +  rightAddon?: React.ReactNode;
Тогда возвращаюсь к изначальной реализации, тем более, что, насколько я понимаю в макете нет случаев, когда необходимо в кнопку включать что-либо не являющееся иконкой.

2021-09-23 13:05 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +  rightAddon?: React.ReactNode;
Вернул изначальную реализацию.

2021-09-23 18:09 UTC, PyotrGrogorchenko commented on src/components/ui/button/button.tsx
> +      <button
Лучше `&&` использовать, лучше читается

2021-09-23 18:27 UTC, brovan-rus commented on src/components/ui/button/button.tsx
> +      <button
Принято, изменил этот момент.

2021-09-23 18:34 UTC, PyotrGrogorchenko approved these changes
Отлично!

2021-09-24 14:10 UTC, andpigge reviewed
Все хорошо. Молодец.

2021-09-24 14:13 UTC, andpigge approved these changes
Все круто. Молодец)

2021-09-24 14:21 UTC, gremwiz1 commented
Все отлично

2021-09-24 14:22 UTC, whodef approved these changes
Пример качественно проделанной работы. Классно!

2021-09-24 14:34 UTC, gremwiz1 approved these changes
Отлично все сделано.

2021-09-24 16:39 UTC, rkostyuchenko approved these changes

2021-09-24 16:39 UTC, merged