Play card
Studio-Yandex-Practicum/lubimovka_frontend pull request #28
Opened 2021-09-22 12:47 UTC by anecheka

## Описание
Реализация компонента карточка пьесы.

Карточка реализована в двух состояниях: 

**basic-play-card**  базовый тип, без фотографии обложки, который присутствует в том числе на странице библиотеки и странице автора;

**announced-play-card** тип карточки в анонсах, который в свою очередь имеет два состояния: анонс на странице событий и анонс на странице фестиваля. Для переключения состояния нужно передать true/false пропсу **festival**. 

В карточке на странице анонса предполагается в зависимости от количества людей, указанных в кредитсах, выводим заголовок '_Драматург/Драматурги_', '_Режиссёр/Режиссёры_'. Пока предполагаю, что данные прилетают ввиде строки, разделенной запятыми без пробела. 

В карточке на странице анонсов также реализован рендеринг одной и более кнопки. Пропс **buttonData** представлен (допущение) как массив объектов, каждый из которых содержит два поля с ключами **buttonLink** и **buttonName**. По этому массиву и прохожусь с помощью map-а. 

## Ссылка на задачу
[Ссылка](https://www.notion.so/Play-s-card-eab9e1ce1aa04978aa4c9c832577a28e) на задачу в Notion

## NB: Над чем работаю
Компонент еще находится в работе. На данном этапе не нужно обращать внимание на анимации. 
Также не реализованы: 
переходы по Link, 
переход по руту при клике на имя автора в базовом типе карточки, 
отображение фотообложки в карточке анонса в каждом втором руте, 
рефакторинг кода, чтобы убрать повторы функций, 
не сверилась полностью с макетом (необходимо перепроверить верстку), 
не протестирован разного рода контент (разный объем текста и разные изображения).

2021-09-22 14:41 UTC, Anastasia-Belik reviewed
Привет! Классное описание PR, возьму себе на заметку :)
По компонентам комментарии написала ниже. 
Еще в мобильной версии карточек анонсов фестивалей у меня все разъехалось.

2021-09-22 14:41 UTC, Anastasia-Belik commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +          return <Link key={i} href={i.buttonLink}>
Хорошо, что ты не забыла про key, но насколько я знаю, туда должны передоваться число или строка, а i  - это объект (т.к. в нем содержится buttonLink и buttonName), надо туда поставить какой-то уникальный идентификатор.

2021-09-23 07:39 UTC, SkaJazz requested changes
Аня, хорошая работа! Посмотри, пожалуйста, комментарии Насти, ну и я тоже отметил некоторые направления доработок. 

Ещё одна важная вещь: попробуй, пожалуйста, убрать из PR package-lock.json. [Вот тут](https://stackoverflow.com/a/44355701) можно посмотреть, как это сделать

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/basic-play-card/images/arrow-external.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
После добавления компонента кнопки этот файл (и соседний) можно будет удалить

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +        <div className={cn(styles.smalltext, styles.year)}>{year}</div>
Предлагаю немного поправить семантику: эти два дива похожи на обычные параграфы, давай запишем их так

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +      <div className={cn(styles.info)}>
Если будет время - посмотри, пожалуйста, все ли эти обёртки нужны, или от некоторых из них можно безболезненно избавиться

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +            <button className={cn(styles.button)}>
Предлагаю здесь и в других местах с кнопками использовать компонент кнопки - он уже есть в мейне. Там и анимация, и иконки, нужно только разобраться, какие пропсы туда передавать

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +import ButtonIconDownload from './images/arrow-download.svg';
После добавления компонента кнопки нужно будет не забыть удалить эти импорты

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +      <div className={cn(styles.container)}>
Попробуй, если будет время, избавиться от лишни оберток в компоненте - кажется, одной li может хватить тут

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +          playwrightArray.length > 1 ?
Классное решение! Но могу предположить, что имена режиссёров и вообще любые другие имена, которых может быть больше одного в блоке, будут приходить в массиве. 

Можем попробовать переписать код, исходя из этого:

Определение драматурги/драматург можем вынести в отдельный элемент и выбирать так, как он выбирается сейчас. 
А вот перечисление сделать на месте, примерно так:

`['Ира', 'Лена', 'Женя', 'Толя'].join(', ').replace(/, ([^,]*)$/, ' и $1') `

Аналогичное решение и выше

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +        <p className={cn(styles.h6, styles.timeFestival)}>{time}</p>
Давай здесь и далее в файлах заменим в заголовках теги параграфов на теги соответствующих заголовков

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +.coverFestival {
Кажется, здесь и в других местах, картинке можно добавить и высоту, т.к. она фиксированного размера

2021-09-23 07:39 UTC, SkaJazz commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +.cardFestival {
Давай попробуем эту карточку точнее подогнать под макет: я оставлю заметку здесь, хотя поправить надо бы именно стили вложенных элементов. Сейчас содержимое контейнера не растягивается по всей ширине на десктопной версии и выходит за рамки контейнера в мобильной версии

2021-09-24 06:10 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +          return <Link key={i} href={i.buttonLink}>
Настя, привет! Запушила фикс по этому пункту на ветку. Спасибо!

2021-09-24 06:12 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +.button:active::before {
Миша, привет! Этот фикс пока не сделан, но доделаны оставшиеся анимации, пока внутри моего компонента. 
Посмотри, пожалуйста, внутри basic-play-card три варианта: horizontal-move, vertical-move, fade-in - для анимации появления кнопок.

2021-09-24 06:13 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +          playwrightArray.length > 1 ?
Миша, в текущем состоянии на ветке реализована часть по типу данных - строка переделена в массив. Но пока сложности с созданием отдельного элемента внутри компонента.

2021-09-24 21:32 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +.cardFestival {
У карточки пьесы в афише фестиваля в макете сейчас два состояния - 1200px и 414px. На момент комментария я реализовала переключение на мобильную версию с tablet-landscape брейкпойнта, так как иначе все было крайне плотно. Сейчас доделала реализацию для переключения на мобильное состояния с tablet-portrait. Подуменьшили пэддинги, ширину блока с названием и блока с обложкой в промежутке. Посмотрите! @Anastasia-Belik @SkaJazz  Было бы здорово запросить предложение дизайнера. Добавила вопрос в наш campfire.

2021-09-24 22:43 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +        <p className={cn(styles.h7, styles.title)}>{title}</p>
Настя, c h7 не выходит, так как html-тега не существует, а в компоненте такого у меня нет. Ошибка: Property 'h7' does not exist on type 'JSX.IntrinsicElements'. Поэтому делаю обычным <p>. Подскажи, как поправить, чтобы был более правильный тег по семантике?

2021-09-24 22:49 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +          <div className={cn(styles.h7)}>{authorFirstName}</div>
Вот тут у меня сложность h7, так как нет такого в компоненте. Как тут правильнее по семантике поступить? Имя и фамилия специально завертываю всегда в столбик - чтобы имя и фамилия находились на разных строках при разной ширине имени и фамилии. Или лучше в классе попробовать прописать без флекса?

2021-09-24 22:51 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +  margin: 24px auto 67px 24px;
Добавляю! Меня немного смущает его возможный случайный характер в макете, но действительно как без него.

2021-09-24 23:10 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +  margin: 24px auto 67px 24px;
Ага, отличный комментарий! Правлю на 6 строк, чтобы всегда оставалось место для кнопок и они не перекрывали текст.

2021-09-24 23:12 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +        <div className={cn(styles.smalltext, styles.year)}>{year}</div>
исправляю

2021-09-24 23:17 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +      <div className={cn(styles.info)}>
div со стилем 'container' организует в столбик все элементы на карточке (title и две кнопки), а обёртка двух кнопок собирает их в один элемент, чтобы можно было использовать space-between для столбика и прижать обе кнопки к низу. подумаю еще, как тут можно переверстать.

2021-09-24 23:20 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +      <div className={cn(styles.container)}>
Да, тут подумаю еще, пока не пришел в голову вариант. Li на организацию всех элементов компонента, а container мне нужен, чтобы расположить тайтл и кнопки внутри контейнера с обложкой.

2021-09-24 23:20 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +        <p className={cn(styles.h6, styles.timeFestival)}>{time}</p>
Фиксы по семантике готовы

2021-09-24 23:30 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +.coverFestival {
ага, готово!

2021-09-24 23:46 UTC, anecheka commented
Всем привет! Запушила изменения по части комментариев. 
В работе: 

1. использование готового компонента button из ветки main 
2. переделка логики для карточки в афише событий

Тут прокомментирую: все же я слишком сложное придумала, по сути по макетам тут может быть только два состояния: 1) с фотографией и двумя кнопками (постановка), 2) без фотографии и с одной кнопкой. 

3. переделка рендеринга кредитсов в функцию в компоненте 
4. избавиться от лишних оберток 
5. отображение на 320px (им пока совсем не занималась)

2021-09-25 05:15 UTC, Anastasia-Belik commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +        <p className={cn(styles.h7, styles.title)}>{title}</p>
Хмм, не знаю даже как будет правильнее. Наверно тут остается два варианта: 
1. как ты сделала (p c классом h7)
2. h6 с классом h7(т.к. это все-таки заголовок).

Мне кажется правильнее, как ты сделала, @SkaJazz как будет лучше?

2021-09-25 05:24 UTC, Anastasia-Belik commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +          <div className={cn(styles.h7)}>{authorFirstName}</div>
По поводу h7 написала выше (наверно подойдет твой вариант с p и классами h7). По сути в этом теге надо писать каждое слово с новой строки. Когда-то я это делала с помощью `word-spacing: 9999px;` - это свойство добавляет огромное расстояние между словами, и из-за этого слова переносятся на следующую строку. Тогда можно будет имя и фамилию прописать в одном теге и избавиться от лишней обертки.

2021-09-25 12:15 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +          <div className={cn(styles.h7)}>{authorFirstName}</div>
О! Любопытное решение! Спасибо большое! Почитаю тут немного

2021-09-26 14:22 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +.button:active::before {
Миша, добавила вопрос к дизайнеру про эффект при нажатии.

2021-09-26 14:24 UTC, anecheka commented on src/components/ui/basic-play-card/images/arrow-external.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Компонент кнопки испортировала и использую, теперь ненужные картинки удалила.

2021-09-26 14:25 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +            <button className={cn(styles.button)}>
Компонент кнопки импортировала и использую

2021-09-26 14:26 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +          playwrightArray.length > 1 ?
Вынесла определение драматург/друматурги в отдельную функцию внутри компонента. Посмотри плиз

2021-09-27 17:02 UTC, Anastasia-Belik requested changes
Привет! TS выдал ошибку, отметила место в коде (у параметра функции не указан тип).
Еще заметила, что в карточке анонса фестиваля кнопка регистрации должна быть прижата к правому краю. А в карточке события блок с драматургами выехали за границы карточки.
![Screenshot from 2021-09-27 19-55-12](https://user-images.githubusercontent.com/79516696/134953615-5f4f4760-6ddf-4c1b-a087-7e8c911917a1.png)

2021-09-27 20:50 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +  const creditsArrayToString = (array) => {
@Anastasia-Belik Настя, привет! Спасибо за комментарии! можешь подсказать с ошибкой ts? я вот не могу с ней справиться. пробовала вот так - закомментировано в коммите https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/28/commits/da269125eefc926f3ddf75bb84976bd6cc820086, согласно "Определению методов" вот отсюда https://metanit.com/web/typescript/3.3.php. Но похоже, это неверный способ, ошибка сохраняется

2021-09-28 04:28 UTC, Anastasia-Belik commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +  const creditsArrayToString = (array) => {
я бы написала вот так:
```
const creditsArrayToString = (array: string[]) => {
    return array.join(', ').replace(/, ([^,]*)$/, ' и $1');
  };
```
При такой записи ошибки нет. Но я сама еще неуверенно разбираюсь в TS, @SkaJazz поправь, пожалуйста, если я не права.

2021-09-28 16:04 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +  const creditsArrayToString = (array) => {
@Anastasia-Belik Настя, правки по расположению элементов внесла в этом коммите: https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/28/commits/1267ad5657150989006cc7d67ae22328e0b328ec 
Про функцию смотрю!

2021-09-28 19:51 UTC, SkaJazz reviewed
Аня, спасибо, очень много исправила! И здорово разобралась с анимацией =)) Я прокомментировал места, про которые ты раньше спрашивала. 

И несколько глобальных комментариев:

1. Давай попробуем у всех карточек установить внешние границы в виде границ контента, т.е. не делать внешние и внутренние отступы снаружи. Это нужно потому, что скорее всего их будут использовать в сетке, в которой уже есть отступы.
2. Продублирую первый коммент - давай уберём логи из PR. Можно просто удалить папку с логами локально

2021-09-28 19:51 UTC, SkaJazz commented on --ext/_logs/2021-09-24T06_07_21_291Z-debug.log
> +0 verbose cli [
Кажется, у нас .log-файлы не падают в гитигнор. Давай удалим его локально

2021-09-28 19:51 UTC, SkaJazz commented on src/components/ui/button/button.module.css
> +  width: min-content;
Вот из-за этого правила (`width: min-content;`) кнопка выезжает за пределы блока. Посмотри, пожалуйста, можем ли избавиться от него, не поедут ли остальные блоки?

2021-09-28 19:51 UTC, SkaJazz commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +    padding-right: 8px;
Кажется, здесь лучше пэддинг 0 - тогда блоки прижмутся к правому краю

2021-09-30 06:01 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +        <p className={cn(styles.h7, styles.title)}>{title}</p>
@Anastasia-Belik Тут готова! Прописала h6, как обсудили на звонке

2021-09-30 06:03 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +.button:active::before {
@SkaJazz Как обсудили, оставила fade-in. Но fade-out на убирание курсора у меня пока не получается реализовать.

2021-09-30 06:05 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +.cardFestival {
Вариант для viewport tablet-portrait пока не получается реализовать. Добавила вопрос в campfire

2021-09-30 06:06 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.tsx
> +  const creditsArrayToString = (array) => {
@Anastasia-Belik Внесла правку в функцию по твоему предложению. Спасибо!

2021-09-30 06:10 UTC, anecheka commented on --ext/_logs/2021-09-24T06_07_21_291Z-debug.log
> +0 verbose cli [
@SkaJazz Удалила локально и запушила, но не уверена, что это верное. Вот этот коммит: https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/28/commits/56f8f31b8468c334a11ba094fde18abd8b8b8ebf. Готова ревертнуть :)

2021-09-30 06:11 UTC, anecheka commented on src/components/ui/button/button.module.css
> +  width: min-content;
@SkaJazz Правило в button.css не решилась править. По расположению кнопок в карточках пьесы пофиксила. Посмотри плиз со своей стороны.

2021-09-30 06:28 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +    padding-right: 8px;
@SkaJazz здесь готово, запушено

2021-10-01 22:10 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.tsx
> +          <div className={cn(styles.h7)}>{authorFirstName}</div>
@Anastasia-Belik Поправила с помощью <br>: теперь один блок h6, и два слова (имя и фамилия) разносятся по строкам с <br>. Надеюсь, что решение норм!

2021-10-01 22:12 UTC, anecheka commented on src/components/ui/basic-play-card/basic-play-card.module.css
> +.button:active::before {
Реализация fade-out анимации готова.

2021-10-01 22:13 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +.cardFestival {
Поправила респонсив мод для карточки в афише фестиваля с учетом разных планшетов, переверстала на грид.

2021-10-02 06:14 UTC, Anastasia-Belik submitted a review, later dismissed
Привет! Мне кажется все ок, карточки выглядят хорошо, ошибок нет. Остался только вопрос с Линками.

2021-10-03 19:02 UTC, SkaJazz reviewed
Класс, последняя правка - и можно отправлять =))

2021-10-03 19:02 UTC, SkaJazz commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +  margin-top: 16px;
Кажется, в этом тайтле избыточный отступ - посмотри, пожалуйста, в дизайне не меньше?

2021-10-04 23:00 UTC, anecheka commented on src/components/ui/announced-play-card/announced-play-card.module.css
> +  margin-top: 16px;
@SkaJazz Поправила в коммите: 00b5e72b4f8544b7d4397730a665dc32440d9b32
Для десктопа нужно меньше, чем в mobile-landscape варианте

2021-10-05 06:13 UTC, Anastasia-Belik approved these changes
Re-approve)

2021-10-06 19:06 UTC, anecheka commented
@SkaJazz Миша, спасибо! Не знаю, правильно ли делаю, но затянув последние апдейты main, я сравниваю две папки с помощью  `git diff`, и мне не возвращается результат со сравнением. Означает ли это, что папки идентичны? 
https://disk.yandex.ru/i/mpl6uleLUvj07w

Папку с логами снова удалила. Запушила в этом коммите: acc58457c35b78eeb9189206f9386ee139533dc0

2021-10-07 10:33 UTC, merged