Slider controls
Studio-Yandex-Practicum/lubimovka_frontend pull request #33
Opened 2021-09-23 20:43 UTC by k-ermolova

## Описание
Реализация кнопок слайдера, которые используются для [этого компонента](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/23/)

## Ссылка на задачу
[Slider Controls](https://www.notion.so/Slider-controls-0ea5b4207d8f4f8aa98e198510bcbe34)

2021-09-24 08:44 UTC, borodulex requested changes
Оставил комментарии по реализации, визуал отличный, осталось сам компонент немножко отрефакторить)

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.tsx
> +import styles from './slider-controls.module.css';
Импорты лучше группировать в таком порядке и отбивать пробелами:
1. Внешние
2. Внутренние
3. Стили

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.tsx
> +  type?: string;
Этот пропс нигде не используется

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.tsx
> +  className?: string;
И этот тоже

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.tsx
> +    <button className={cn(styles.sliderControl, disabled ? styles.disabled : '')} type='button' onClick={() => onClick}>
`disabled ? styles.disabled : ''` можно заменить на `styles[disabled]`
Так же не обязательно onClick оборачивать в анонимную функцию, достаточно `onClick={onClick}`

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.tsx
> +  onClick?: (index: number) => void;
Не понимаю, зачем тут `index: number`

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.tsx
> +    <RightSlider/>
Что-то мне не нравится такая реализация, ниже происходит нарушение принципа DRY. 

Давай компонент `SliderControls` переименуем в `SliderControl` и будем возвращать только один элемент стрелки, а не две сразу. А направление стрелки укажем как пропс direction: 'left' | 'right'. И в зависимости от этого пропса будем применять соответствующие стили, которые будут менять направление.
Таким образом избавимся от второго интерфейса и дублирования кода.

Ну и не забудь пропс className подрубить, чтобы я мог его спозиционировать при использовании.

[Вот пример](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/23/files#diff-a386bd242e626efa2efc306eb19ce4c1dee0266acbb2cda785f8e396107303e8R12-R28)

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +    background-color: #242424;
Цвета нужно использовать через миксины var(--coal). В других местах тоже

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +  max-width: 50px;
Тут можно просто `width` задать, тогда можно убрать `width: 100%`. А то путанница небольшая

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +  min-height: 50px;
И высоту тоже можно фиксированно оставить. Если не прав, пиши возражения)

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +  outline: none;
Так часто делают, но это не самая лучшая практика отключать outline. Можно оставить так, но есть способы сделать лучше не в ущерб accessibility.

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +}
Еще можно ненужные паддинги убрать, но это не обязательно

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +@keyframes BackgroundColor {
`backgroundColor` у нас camelCase

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +.sliderControl:hover {
У нас подключены вложенные селекторы, так что ты можешь вложить его в `sliderControl` как `&:hover { ... }`

2021-09-24 08:44 UTC, borodulex commented on src/components/ui/slider-controls/slider-controls.module.css
> +}
Еще хотелось бы чуть увеличить скорость анимации, но это как посчитаешь нужным.

2021-09-24 09:12 UTC, borodulex commented
И добавь еще WIP в заголовок ПР

2021-09-24 09:28 UTC, borodulex commented
Еще рекомендую вот так байндить стили:
https://github.com/JedWatson/classnames#alternate-bind-version-for-css-modules

2021-09-24 10:56 UTC, rkostyuchenko requested changes

2021-09-24 10:56 UTC, rkostyuchenko commented on src/components/ui/slider-controls/slider-controls.tsx
> +    <RightSlider/>
++

2021-09-24 10:58 UTC, rkostyuchenko commented on src/components/ui/slider-controls/slider-controls.tsx
> +    <RightSlider/>
++

2021-09-24 21:16 UTC, PyotrGrogorchenko reviewed
Выглядет хорошо, но есть что улучшить)

2021-09-24 21:16 UTC, PyotrGrogorchenko commented on src/components/ui/slider-controls/slider-controls.tsx
> +    <RightSlider/>
И тогда буден один компонент, и этот нужно удалить, все сделать в storybook

2021-09-25 20:57 UTC, PyotrGrogorchenko reviewed
Почти готово!

2021-09-25 20:57 UTC, PyotrGrogorchenko commented on src/components/ui/slider-control/slider-control.tsx
> +interface ISliderControlProps {
можно унаследовать свойства `extends ButtonHTMLAttributes<HTMLButtonElement>`, тогда `disabled` и `onClick` можно удалить, ниже заполнить с помощью {...restProps}
`disabled?: true | false;` - это `boolean`
Не понятно наличие свойства `className`?

2021-09-25 20:57 UTC, PyotrGrogorchenko commented on src/components/ui/slider-control/slider-control.tsx
> +  const {className, direction, disabled, onClick } = props;
здесь `const {className, direction, ...restProps } = props;`

2021-09-25 20:57 UTC, PyotrGrogorchenko commented on src/components/ui/slider-control/slider-control.tsx
> +    <button className={`${sliderControlStyles} ${className}`} type='button' onClick={onClick} disabled={disabled}>
И здесь <button className={`${sliderControlStyles} ${className}`} type='button' {...restProps}>

2021-09-26 06:38 UTC, k-ermolova commented on src/components/ui/slider-control/slider-control.tsx
> +interface ISliderControlProps {
`className` необходимо для того, чтобы была возможность позиционировать слайдер извне

2021-09-26 09:28 UTC, k-ermolova commented on src/components/ui/slider-control/slider-control.tsx
> +    <button className={`${sliderControlStyles} ${className}`} type='button' onClick={onClick} disabled={disabled}>
так как `className` имеет тип `string`, то отсутствие шаблонной строки приведет к ошибке

2021-09-26 10:37 UTC, PyotrGrogorchenko reviewed
Думаю WIP можно убрать)
Компонент наверное правильнее назвать `slider-button`

2021-09-26 10:37 UTC, PyotrGrogorchenko commented on src/components/ui/slider-control/slider-control.stories.tsx
> +const Template: ComponentStory<typeof SliderControl> = (args) => <SliderControl {...args} />;
Нужно `disabled` добавить, чтобы можно было посмотреть

2021-09-26 10:57 UTC, PyotrGrogorchenko commented on src/components/ui/slider-control/slider-control.tsx
> +    <button className={`${sliderControlStyles} ${className}`} type='button' onClick={onClick} disabled={disabled}>
Попробовал, не увидел ошибки, можно так сделать
`${className || ''}`

2021-09-26 21:05 UTC, PyotrGrogorchenko submitted a review, later dismissed
Отлично!

2021-09-26 21:05 UTC, PyotrGrogorchenko commented on src/components/ui/slider-dots/slider-dots.module.css
> +  background: transparent;
Можно удалить по умолчанию `transparent`

2021-09-27 11:06 UTC, borodulex reviewed
Все хорошо, оставил немного рекомендашек)

2021-09-27 11:14 UTC, k-ermolova commented on src/components/ui/slider-dots/slider-dots.module.css
> +  background: transparent;
по умолчанию кнопки имеют серый фон

2021-09-27 16:50 UTC, PyotrGrogorchenko submitted a review, later dismissed

2021-09-27 20:32 UTC, borodulex approved these changes
LGTM 🎉

2021-09-27 20:55 UTC, merged