Fix/donation advise
Studio-Yandex-Practicum/lubimovka_frontend pull request #399
Opened 2022-06-30 14:01 UTC by yar83

## QA фикс тикета
Решить проблему с отрисовкой виджета донатов.

## Ссылка на задачу
[На странице "Поддержать" не отображается панель регистрации поддержки](https://www.notion.so/Mob-web-817f025d1958449793e83b6bc6f8bd1f)

#### Внесены изменения
Компонент переработан в части, касающейся формы ввода данных пользователя для перечисления доната. Теперь форма видна на всех разрешениях, масштабируется в соответствии с текушей шириной экрана.

2022-07-01 04:42 UTC, rkostyuchenko commented
Давай попробуем решить проблему. Кажется, не ок, что какая-то функциональность недоступна с мобилы. Какие варианты сходу приходят в голову:
1. Показывать на мобильных вместо iframe ссылку на него
2. Использовать transform: scale() для масштабирования фрейма. Можно докинуть calc() и вычислять нужный коэффициент в зависимости от ширины вьюпорта.

2022-07-01 04:48 UTC, rkostyuchenko commented
btw Сча в PR попали лишние коммиты.
btw2 Префикс hotfix в коммит-месседже здесь не совсем к месту. Хотфикс — это все, что мерджится в мастер, остальное, просто fix. [Почитать по теме.](https://habr.com/ru/post/106912/)

2022-07-01 08:48 UTC, yar83 commented
> Давай попробуем решить проблему. Кажется, не ок, что какая-то функциональность недоступна с мобилы. Какие варианты сходу приходят в голову:
> 
> 1. Показывать на мобильных вместо iframe ссылку на него
> 2. Использовать transform: scale() для масштабирования фрейма. Можно докинуть calc() и вычислять нужный коэффициент в зависимости от ширины вьюпорта.

Ок, попробую что-то сделать с этим фреймом. Помню, что ещё в прошлом году консультировался с Чеченёвым по этому поводу, но приличного решения так и не нашли.

> btw Сча в PR попали лишние коммиты.
🤔, странно, что-то значит я сделал не так. Действовал по проверенной схеме: пулл из мэйна, ветка с фиксом, коммит и пуш в новую ветку. Ща поразбираюсь, что не так.

Аааа, надо было ветвить из девелоп, похоже.

> btw2 Префикс hotfix в коммит-месседже здесь не совсем к месту. Хотфикс — это все, что мерджится в мастер, 
остальное, просто fix. [Почитать по теме.](https://habr.com/ru/post/106912/)

Да, спасибо, я сначала ветку называл hotfix, переименовал в просто fix, но по инерции закооммитил как hotfix.

2022-07-03 05:40 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.module.css
> +  transform: scale(min(calc(var(--vw-donat) / 1440), 1));
А разве мы не можем просто использовать 100vw внутри calc вместо js-кода?

2022-07-03 08:10 UTC, yar83 commented
#### Настройки PostCSS(postcss-pxtorem):
- Добавлено исключение для селектора `iframe`

2022-07-04 14:22 UTC, yar83 commented
#### Настройки PostCSS(postcss-pxtorem):
- Добавлено исключение для селекторов `paymentFormContainer, iframe`

#### Deboucer
Добавлен код дебаунсера на событие ресайза экрана.

2022-07-08 15:02 UTC, yar83 commented
Компонент переработан в части, касающейся формы ввода данных пользователя для перечисления доната. Теперь форма видна на всех разрешениях, масштабируется в соответствии с текушей шириной экрана.

2022-07-11 19:55 UTC, rkostyuchenko commented
> ## QA фикс тикета
> 
> Убрать комментарий под звёздочкой для мобильного разрешения
> ## Ссылка на задачу
> 
> [На странице "Поддержать" не отображается панель регистрации поддержки](https://www.notion.so/Mob-web-817f025d1958449793e83b6bc6f8bd1f)
> #### Внесены изменения
> 
> При мобильном разрешении в стиле соответствующего элемента добавлена свойство `display: none`

Кажется, описание устарело)

2022-07-11 20:15 UTC, rkostyuchenko requested changes
Го пофиксим мелочи и мерджим

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.module.css
> +  transform: scale(var(--donation-appropriate-scale-factor));
Может `--donation-widget-zoom`?)

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
>  export const DonationPageTitle: FC<IDonationPageTitleProps> = (props) => {
Не имеет отношения к ПР, просто JFYI:
Нейминг компонента не оч удачный. От компонента ждешь, что он отрендерит заголовок, а вместо этого получаешь пачку разных блоков.
Тут хорошо бы отрефакторить все. Возможно, унести виджет пожертвования в отдельный компонент и инкапсулировать логику масштабирования в нем.

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +        vw >= 729
Магическое число. Если это точка останова, то мы можем импортировать ее из констант.

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +  const resizeDebounce = debounce(setCurVWProperty, 100);
Тут лучше переименовать функцию в `resizeWidgetDebounced`, например.

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +  useEffect(() => {
А не хотим сбросить эффект?)

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +            src="https://goody.im/form/9bc4b4afb926640f7ef3fa8f/frame"
Вот этот url хорошо бы унести в константы.

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +    window.addEventListener('resize', () => {
Тут не нужна стрелочная функция: `window.addEventListener('resize', resizeDebounce)`

2022-07-11 20:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +  const defaultDesktopScreenWidth = 1440;
Давай заменим `default` на `reference`, чтобы лучше отразить смысл? А можно даже унести эти значения в константы, кажется, они еще где-то используются в коде.

2022-07-12 08:48 UTC, yar83 commented on postcss.config.js
> +      selectorBlackList: ['iframe'],
Класс `.iframe` переименован в `.paymentFormIframe`. В исключения добавлен regexp-шаблон для исключения указанного класса из селекторов на которые оказывает влияние плагин `postcss-pxtorem`. Поиск по шаблону применяется для исключения одного конкретного селектора. Остальные селекторы, включающие в своё название строку `paymentFormIframe` под действие исключения не попадают.

2022-07-12 14:42 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.module.css
> +$iframe-intrinsic-width: 520px;
Переименовал согласно комментарию.

2022-07-12 14:45 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.module.css
> +  transform: scale(var(--donation-appropriate-scale-factor));
Не возражаю. ))

2022-07-12 14:58 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +  const defaultDesktopScreenWidth = 1440;
Заменил `default` на `reference`, вынес эти переменные в констаны: `/src/shared/constants/screenSizes`.

2022-07-12 14:59 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +        vw >= 729
Дал ей говорящее название `donationWidgetZoomBreakpoint` и вынес в константы `/src/shared/constants/screenSizes`.

2022-07-12 15:27 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +  const resizeDebounce = debounce(setCurVWProperty, 100);
Переименовал.

2022-07-12 16:01 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +    window.addEventListener('resize', () => {
Факт, не нужна. Исправил.

2022-07-12 16:16 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +  useEffect(() => {
Хотим. Теперь сбрасываем.

2022-07-12 17:22 UTC, yar83 commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
>  export const DonationPageTitle: FC<IDonationPageTitleProps> = (props) => {
Отрефакторил примерно в описанном ключе. Возможно, есть некоторые моменты с неймингом. Говорят, приходит с опытом.

2022-07-13 22:13 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
>  export const DonationPageTitle: FC<IDonationPageTitleProps> = (props) => {
> Не имеет отношения к ПР, просто JFYI
Рефакторинг в этом ПР не нужен. В чатике уже писал, почему

2022-07-13 22:15 UTC, rkostyuchenko commented on src/components/donation-page/donationPageTitle/donationPageTitle.tsx
> +        vw >= 729
https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/develop/src/shared/breakpoints.js#L3 но у нас уже есть такая константа)

2022-07-13 22:19 UTC, rkostyuchenko approved these changes

2022-07-13 22:20 UTC, rkostyuchenko commented
Сча мерджу как есть, чтобы сохранить правки виджета в истории.

2022-07-13 22:21 UTC, merged