fix(library-authors-page): исправить затенение ссылок 'нависающим' ко…
Studio-Yandex-Practicum/lubimovka_frontend pull request #406
Opened 2022-07-09 16:42 UTC by yar83

## Описание
Все ссылки до последней затенялись "нависающим" компонентом. Исправил уменьшением высоты этого компонента. Для трёх авторов (макс. возм. замоканный случай) всё работает, вёрстка не поломалась.

## Ссылка на задачу
[Моб. Библиотека, Авторы. При клике на авторов, кроме последнего в списке, не открывается страница автора](https://www.notion.so/0e0a12ebae98440aacddc972c7e44beb)

2022-07-11 19:53 UTC, rkostyuchenko requested changes

2022-07-11 19:53 UTC, rkostyuchenko commented on src/components/library-authors-page/index.module.css
> +    height: calc(100% - 280px);
А это правило вообще нужно? Кажется, если его убрать, ничего не меняется

2022-07-11 19:53 UTC, rkostyuchenko commented on src/components/library-pagination/library-pagination.tsx
> +import alphabet from '../../shared/constants/alphabet';
Сейчас в один коммит попали разные по смыслу изменения, хорошо бы переоформить ПР.
Получается чутка странно — поставленную задачу решает одна строчка кода, а зачем нужно все остальное непонятно 🤷‍♂️.

Хорошей практикой будет попробовать поставить себя на место ревьюера. Представить, какие вопросы могут возникнуть и постараться сразу дать на них ответы в виде комментариев. Вот здесь: «Исправил уменьшением высоты этого компонента» — круть, как надо. Остальные правки (если они вообще нужны) хочется видеть отдельным коммитом с описанием, зачем они понадобились.

btw Здесь импорт лучше заменить на абсолютный.

2022-07-12 17:51 UTC, yar83 commented on src/components/library-authors-page/index.module.css
> +    height: calc(100% - 280px);
Убрал это правило для мобилы. Честно говоря, так и не понял в чём его смысл. Но без него, _кажется_, всё работает как надо.

2022-07-13 22:35 UTC, rkostyuchenko approved these changes
LGTM
Но нужен аппрув @SidorovN

2022-07-14 22:00 UTC, AntonZelinsky approved these changes
Удалил эти стилив инспекторе, ссылки заработали, поэтому апрувлю и мержу

2022-07-14 22:01 UTC, merged

2022-07-15 07:45 UTC, rkostyuchenko commented
> Удалил эти стилив инспекторе, ссылки заработали, поэтому апрувлю и мержу

Дизлайк