feat: Добавлена зависимость от статуса фестиваля для кнопки Подать пьесу на страницах 404 и в мобильном меню
Studio-Yandex-Practicum/lubimovka_frontend pull request #434
Opened 2022-10-18 06:29 UTC by SilentVampR

## Описание
Добавлена зависимость от статуса фестиваля для кнопки "Подать пьесу" на страницах 404 и в мобильном меню (layout-menu)

## Ссылка на задачу
[Важно! Кнопка Подать пьесу на странице 404 не нужна в то время, когда прием пьес закрыт](https://www.notion.so/404-2f93524d060e45708f81fa34f5383eee)

2022-10-18 08:25 UTC, Karmyshkov commented on src/components/404/NotFoundError.tsx
> +import { participationFormPath } from 'shared/constants/participation-form-path';
Предлагаю настроить экспорты и импорты в проекте, тогда это позволит код существенно сократить.
c:
import { useMediaQuery } from 'shared/hooks/use-media-query';
import * as breakpoints from 'shared/breakpoints';
import { usePersistentData } from 'providers/persistent-data-provider';
import { participationFormPath } from 'shared/constants/participation-form-path';

до:
import { useMediaQuery, participationFormPath, breakpoints } from 'shared';

2022-10-18 08:25 UTC, Karmyshkov commented on src/components/404/NotFoundError.tsx
> +  const isFestivalRuns = settings?.canProposePlay || false;
`|| false` можно убрать, undefined тоже falsy значение по этому код можно сократить :)

2022-10-18 08:25 UTC, Karmyshkov commented on src/components/app-layout/app-layout.tsx
> +  const isFestivalRuns = settings?.canProposePlay || false;
Тут тоже можно сократить до: `const isFestivalRuns = settings?.canProposePlay;`

2022-10-18 08:50 UTC, Karmyshkov commented on src/components/404/NotFoundError.tsx
> +import { participationFormPath } from 'shared/constants/participation-form-path';
Пример:
https://github.com/Karmyshkov/middle.messenger.praktikum.yandex/tree/main/src/services

2022-10-18 11:07 UTC, SilentVampR commented on src/components/404/NotFoundError.tsx
> +import { participationFormPath } from 'shared/constants/participation-form-path';
Это интересное решение, но тогда его надо применять вообще во всем проекте и вносить правки данного типа в каждый файл или как?

2022-10-18 11:10 UTC, Karmyshkov commented on src/components/404/NotFoundError.tsx
> +import { participationFormPath } from 'shared/constants/participation-form-path';
В каждом файле не думаю что стоит это делать, придется сильно много рефакторить кода. Для начала нужно заложить основу, а со временим все перепишем. Пока лучше переписать тот код который твой ПР затронул.

2022-10-18 13:06 UTC, rkostyuchenko commented on src/components/app-layout/app-layout.tsx
> +  const isFestivalRuns = settings?.canProposePlay || false;
А зачем переназывать переменную? 🙂

2022-10-18 13:26 UTC, SilentVampR commented on src/components/app-layout/app-layout.tsx
> +  const isFestivalRuns = settings?.canProposePlay || false;
Ну в задаче было "Когда не проходит фестиваль". В настройках переменная называется "Можно подавать пьесу"... И получилась вот такая беда :)

На проверку же не обязательно в данном случае создавать переменную? Можно же просто нарисовать проверку
`settings?.canProposePlay && (`
Так?

2022-10-19 03:13 UTC, SilentVampR commented
Перезалил новые изменения. Можно смотреть

2022-10-19 06:40 UTC, rkostyuchenko requested changes
Все классно, но нужно убрать изменения `package-lock.json` из PR, поскольку тут зависимости не изменялись.

2022-10-19 07:13 UTC, SilentVampR commented
Так, вроде убрал :)

2022-10-24 07:56 UTC, rkostyuchenko approved these changes

2022-10-24 07:57 UTC, merged