Проверить демки Storybook
Studio-Yandex-Practicum/lubimovka_frontend pull request #435
Opened 2022-10-18 10:28 UTC by Karmyshkov

## Описание
- Поднял StoryBook
- Удалил не пере используемые StoryBook:
    Donation-DonationPageTitle
    Donation-Opportunity
    Donation-Report
    ForPressHeroDescription
    ForPressHeroTitle
    PlayProposalSuccess

## Ссылка на задачу
[Проверить демки Storybook](https://www.notion.so/Storybook-42e09ab5528e4733a0a9b6b20ca68e6f)

2022-10-18 11:02 UTC, SilentVampR submitted a review, later dismissed
Мне сложно оценить работу более высокого уровня (тем более это мое первое ревью). В общем и целом изменения выглядят логичными и рефакторинг тоже уместный. Не совсем ясна только замена id из индекса на randomId (в теории вероятностей randomId может вернуть идентичный id, что приведет к ошибке или там все в порядке?:)

2022-10-18 11:07 UTC, Karmyshkov commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
В качестве значения для key не стоит использовать index: https://sacret.medium.com/%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%BA%D0%BB%D1%8E%D1%87%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8-%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD-56bab8ada309

2022-10-18 11:11 UTC, SilentVampR commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
Ну то, что сам индекс не надо использовать - тут понятно. В самих данных получается нет уникального id, а функция генерации рандомного id точно не вернет идентичный id никогда? Так? :)

2022-10-18 11:14 UTC, Karmyshkov commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
За все время использования такого подхода ни разу не столкнулся с такой проблемой. Тут лучше уточнить у @rkostyuchenko

2022-10-18 11:32 UTC, rkostyuchenko commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
А разве `randomId` не будет возвращать уникальное значение каждый рендер?

> Ключи помогают React определять, какие элементы были изменены, добавлены или удалены. 

https://ru.reactjs.org/docs/lists-and-keys.html

2022-10-18 11:37 UTC, rkostyuchenko commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
То есть рандомизировать ключ можно (только не оч понятно, зачем), но если ты готовишь данные заранее. 
```
const itemsWithId = items.map((item) => ({
   ...item,
   id: randomId(),
}))
...
itemsWithId.map(({ id }) => { ....
```

Но вообще, в демке и индекс использовать норм

2022-10-18 11:42 UTC, rkostyuchenko commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
Я не уверен, что переменная `process.env.STORYBOOK` определена в проекте, хорошо бы проверить.
Если нет, то лучше проп `unoptimized` убрать.

2022-10-18 14:31 UTC, Karmyshkov commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
На счет `process.env.STORYBOOK`, StoryBook сам добавляет переменную окружения.

`{"NODE_ENV":"development","NODE_PATH":[],"STORYBOOK":"true","PUBLIC_URL":".","NEXT_PUBLIC_BASE_URL":"http://localhost:3000","NEXT_PUBLIC_API_BASE_URL":"https://stage.dev.lubimovka.ru/api/v1"}`

Вообще все это добавлено чтобы next/image работали с StoryBook. Next под капотом как-то оптимизирует изображения и StoryBook с ними не может работать

2022-10-18 16:12 UTC, rkostyuchenko commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
> Вообще все это добавлено чтобы next/image работали с StoryBook. Next под капотом как-то оптимизирует изображения и StoryBook с ними не может работать

Выгляди как очень спорное решение. Непонятно, почему компонент должен что-то знать про окружение. Давай попробуем избавиться от такой реализации, но в отдельной задаче.

2022-10-18 19:56 UTC, Karmyshkov commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
@rkostyuchenko в рамках этой задачи какие-то доработки или правки нужно внести (удалить randomId из историй к примеру)?

2022-10-18 20:58 UTC, rkostyuchenko requested changes

2022-10-18 20:58 UTC, rkostyuchenko commented on src/components/ui/blog-card/blog-card.stories.tsx
> +export const onlyFirstBlogCard = Template.bind({});
Если я ничего не путаю, в реализации сейчас нет отдельного вида для первой карточки записи блога, если так, хорошо бы сразу ее выпилить

2022-10-18 20:58 UTC, rkostyuchenko commented on src/components/ui/person-card/person-card.tsx
> +            unoptimized={Boolean(process.env.STORYBOOK)}
> Давай попробуем избавиться от такой реализации, но в отдельной задаче.

Так, тут мой косяк, я не смотрел PR, когда писал этот коммент. Давай сразу избавимся от нового пропса `unoptimized` в компонентах — сейчас не очень понятно, почему вдруг он понадобился.

>  удалить randomId из историй к примеру

Да, этот хелпер пользы не несет, лучше убрать его

2022-10-18 20:58 UTC, rkostyuchenko commented on src/components/library-filter/library-filter.stories.tsx
>  export default {
Вот эта демка тоже выглядит бесполезной

2022-10-18 20:58 UTC, rkostyuchenko commented on src/components/ui/blog-card/blog-card.stories.tsx
> +export const onlyFirstBlogCard = Template.bind({});
btw Сейчас все демки карточки записи блога выглядят одинаково. Предлагаю оставить одну.

2022-10-18 20:58 UTC, rkostyuchenko commented on src/components/ui/button/button.stories.tsx
>  export default {
Го удалим, а для нормальной реализации кнопки сделаем новую хорошую демку?

2022-10-19 11:02 UTC, SilentVampR reviewed
А что не так с картинками? Их теперь генерит что-то другое?

2022-10-19 11:06 UTC, Karmyshkov commented
> А что не так с картинками? Их теперь генерит что-то другое?
Из-за того что убрали prop unoptimized, STORYBOOK не может работать с оптимизированными картинками next/image, теперь это просто заглушка

2022-10-20 13:47 UTC, SilentVampR approved these changes

2022-10-29 20:32 UTC, rkostyuchenko reviewed
Чтобы не затягивать, я сразу докинул правки по комментариям

2022-10-29 20:36 UTC, merged

2022-10-29 20:53 UTC, rkostyuchenko commented
> А что не так с картинками? Их теперь генерит что-то другое?

@Karmyshkov @SilentVampR Чтобы использовать в Next.js оптимизацию внешних изображений, нужно докинуть в конфиг список доступных для этого доменов (из соображений безопасности). Несмотря на то, что `source.unsplash.com` в проекте разрешен в окружении разработки, NextImage внутри Storybook ничего про конфигурацию Next.js не знает и падает. [Решается](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/develop/.storybook/next-image-stub.js) все плюс-минус просто — патчим NextImage на уровне Storybook, докидывая проп unoptimized, чтобы отключить оптимизацию. Такое решение, кажется, универсальнее, чем докидывание дополнительного неочевидного пропа в каждый компонент.

Помимо проблем с доменами, были еще картинки, которые хранились в /public. Их удалили ранее, потому что все, что лежит в /public попадает в боевую сборку, а ассеты демок там точно не нужны.