Изменение отображения спектакля на странице в десктопной версии
Studio-Yandex-Practicum/lubimovka_frontend pull request #438
Opened 2022-10-20 13:36 UTC by SilentVampR

## Описание
- Добавлено css свойство grid-template-columns к основному контейнеру спектакля для равной ширины столбцов контента
- Исправлен баг, связанный с изменением свойства url в api, который используется в формировании ссылки на покупку билетов

## Ссылка на задачу
[О спектакле. Разная ширина у блоков изображение, описание, видео, пьеса](https://www.notion.so/94b2ae96a6614ddeb13610a93822c2a9)

2022-10-20 13:42 UTC, Karmyshkov submitted a review, later dismissed

2022-10-26 20:41 UTC, rkostyuchenko requested changes
Чот fixup-коммит остался незасквошенным, го причешем?

2022-10-26 20:41 UTC, rkostyuchenko commented on src/components/performance-layout/performance-layout.module.css
> +  grid-column-gap: 5rem;
Кажется, использовать `rem` здесь не нужно. Можно задать размер в `px`, он [конвертируется](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/develop/postcss.config.js#L25) в `rem` на этапе сборки.

2022-10-26 20:41 UTC, rkostyuchenko commented on src/api-typings/models/LocalEvent.ts
> +    readonly action_url: string;
Вот это незаконная правка. Типы в каталоге `api-typings` генерируются автоматически на основе схемы API бекенда. Их нельзя править руками, потому что такие изменения внесут путаницу и ошибки в обработку ответов API.

2022-10-26 20:41 UTC, rkostyuchenko commented on src/pages/performances/[id].tsx
> +    ticketsUrl: action_url,
Лучше переименовать `ticketsUrl` везде, а не только на входе, чтобы все было консистентно и верно по смыслу.

2022-10-27 04:00 UTC, SilentVampR commented on src/pages/performances/[id].tsx
> +    ticketsUrl: action_url,
Не совсем понял. Переименовать ticketsURL в actionUrl или как?

2022-10-27 04:10 UTC, SilentVampR commented on src/api-typings/models/LocalEvent.ts
> +    readonly action_url: string;
Тут такой момент. Линтер ругается, что action_url нет в данном типе... Хотя все работает (если вернуть как было - url), просто игнорить ошибку и все?

Просто api возвращает как раз свойство action_url, а раньше возвращал свойство url

2022-10-27 07:18 UTC, rkostyuchenko commented on src/pages/performances/[id].tsx
> +    ticketsUrl: action_url,
Да. Смотри, в API поле `action_url`, называется так потому что ссылка может вести не только на покупку билетов, но и на трансляцию (в слаке есть обсуждение). А сейчас компонент, который непосредственно использует данные API [принимает](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/develop/src/components/performance-event-list/item/performance-event-list-item.tsx#L13) проп `ticketsUrl`, что сбивает с толку. В том же компоненте можно заметить, что текст ссылки [захардкожен](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/develop/src/components/performance-event-list/item/performance-event-list-item.tsx#L45). Это повод уточнить у бекендеров в слаке, может ли вернуться в ответе на запрос спектакля в событиях ссылка на трансляцию. И если да, то попросить докинуть поле с текстом ссылки.

2022-10-27 07:26 UTC, rkostyuchenko commented on src/api-typings/models/LocalEvent.ts
> +    readonly action_url: string;
Если изменилось API, не нужно правки делать руками. Лучше:
- выполнить `npm run update-typings`. Новые типы сами сгенерятся и будут точно соответствовать тому, что возвращает бекенд.
- закоммитить изменения типов, чтобы явно было видно, что происходит. Вот прям в коммит-месседже написать «обновление типов API»
- внести правки в код руками там, где изменились ответы API, закоммитить

Игнорировать ошибки линтера не нужно (и не получится). Он для того и существует, чтобы бить по рукам, когда надо.

2022-11-09 01:45 UTC, SilentVampR commented
Правки внес. Текст для кнопки добавил. Сперва хотел указать, что в случае пустого ответа от сервера писать "Билеты", но не стал, с виду избыточно...

2022-11-09 11:52 UTC, rkostyuchenko approved these changes
1. Го писать ответы на вопросы/замечания/предложения прям в соответствующих тредах, а не отдельным комментарием 🙏. Так всем будет проще следить за прогрессом задачи.
2. Твоя реализация была нормыч, все круто. но я не удержался и чутка ее улучшил, переверстав раскладку на float. Стало чуть дальше от дизайна, но на мой взгляд универсальнее и опрятнее — теперь высота блоков в левом столбце не зависят от высоты блоков в правом 👀.
3. Привел историю коммитов в порядок, но с гитом хорошо бы разобраться) Если есть конкретные вопросы — насыпай в чатик. В ветке твоей задачи откуда-то появились мерджи себя в себя, такого быть не должно. Вообще не должно быть мердж-коммитов других веток в твоей.

2022-11-09 11:52 UTC, merged