Использовать новую реализацию кнопки
Studio-Yandex-Practicum/lubimovka_frontend pull request #444
Opened 2022-11-05 09:42 UTC by Karmyshkov

## Описание
- Дополнил логику компонента Button2
- Заменил все компоненты Button на Button2
- Удалил компонент Button

## Ссылка на задачу
[Использовать новую реализацию кнопки](https://www.notion.so/Frontend-52aae4efcc1743f58f4abf64bf7357ff?p=2603e88474614731b0194f8b8f1342f7&pm=s)

2022-11-07 13:36 UTC, BorodkinaViktoriya submitted a review, later dismissed

2022-11-07 18:11 UTC, rkostyuchenko requested changes
В коммит-месседжах закрались опечатки, хорошо бы поправить. Ну и я бы бахнул все замены компонента в один коммит, они же общие по смыслу.

2022-11-07 18:11 UTC, rkostyuchenko commented on src/components/library-form/library-form.tsx
>          href={`/library/search-result${urlQuery}`}
Если не обернуть `button` в `next/link`, ссылки будут работать как внешние: страница будет полностью перезагружаться.

https://nextjs.org/docs/api-reference/next/link

2022-11-07 18:11 UTC, rkostyuchenko commented on src/components/ui/button2/button.tsx
> +  style?: Record<string, string>
https://htmlacademy.ru/blog/html/inline

2022-11-09 07:02 UTC, Karmyshkov commented
> В коммит-месседжах закрались опечатки, хорошо бы поправить. Ну и я бы бахнул все замены компонента в один коммит, они же общие по смыслу.

Опечатки поправил, коммиты объединил

2022-11-09 07:37 UTC, Karmyshkov commented on src/components/ui/button2/button.tsx
> +  style?: Record<string, string>
От prop 'style' избавился. Код исправил с соответствием с предложением :)

2022-11-09 07:44 UTC, Karmyshkov commented on src/components/library-form/library-form.tsx
>          href={`/library/search-result${urlQuery}`}
Поправил

2022-11-10 08:27 UTC, rkostyuchenko requested changes

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/500/server-error.module.css
> +  padding-left: 0;
Компоненты не должны знать ничего про внутренний мир друг-друга. Для изменения вида кнопки должен использоваться ее модификатор. Микс (дополнительный класс) может отвечать только за внешнее поведение.

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/500/server-error.tsx
> +            href="https://t.me/lubimovka"
Лишний проп

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/500/server-error.tsx
>              onClick={()=>document.location.reload()}
Тут, кстати, не обязательно оборачивать вызов `document.location.reload` в стрелочную функцию, можно сразу упростить

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/author-page/overview/overview.module.css
> +  padding-right: 0;
См. коммент про управление внешним видом компонента через микс выше

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/author-page/overview/overview.module.css
> +  padding-right: 0;
См. коммент про управление внешним видом компонента через микс выше

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/author-page/overview/overview.tsx
> +        <Button
Нужно обернуть в `next/link`

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/for-press-hero/for-press-hero-description/for-press-hero-description.module.css
> +  padding-left: 0;
См. коммент про управление внешним видом компонента через микс выше

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/history-page/title/history-title.module.css
> +    font-family: inherit;
Подозрительные стили, расскажи, пожалуйста, для чего они?

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/history-page/title/history-title.tsx
>                <Button
У кнопки должен быть обработчик, иначе это не кнопка. Скорее всего, кнопка здесь вообще не нужна, и лучше или сразу зарефакторить или поставить отдельную задачу.

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/library-filter/library-filter.module.css
> +  button {
В проекте у нас CSS-модули с налетом БЭМ, поэтому селекторы по тегам мы не используем, только классы. Но вообще этого стиля не должно быть, потому что он лезет во внутренний мир другого компонента, см коммент выше.

Справедливости ради в классическом понимании CSS-модулей норм использовать теги.

2022-11-10 08:27 UTC, rkostyuchenko commented on src/components/library-filter/library-filter.tsx
> +              Очистить
К задаче не относится, так, на заметку. Семантика верстки здесь не оч — две одинаковые по смыслу кнопки, лучше такие места сразу помечать: писать в чат, ставить задачу, писать коммент в коде с префиксом TODO

2022-11-10 08:27 UTC, rkostyuchenko commented on src/pages/library/search-no-result/index.tsx
> +                {isMobile ? 'БИБЛИОТЕКА':'ВЕРНУТЬСЯ В БИБЛИОТЕКУ'}
Го заменим текст транслитом на обычный регистр. У нас же есть модификатор `upperCase` для этого. Если завтра дизайн изменится и верхний регистр станет не нужен, эта кнопки станет багом.

2022-11-10 08:27 UTC, rkostyuchenko commented on src/pages/library/search-no-result/index.tsx
>                <Button
Нужно обернуть в `next/link`

2022-11-10 08:27 UTC, rkostyuchenko commented on src/pages/library/search-result/index.module.css
> +  a {
См. коммент про селекторы по тегам

2022-11-10 08:27 UTC, rkostyuchenko commented on src/pages/library/search-result/index.tsx
> +                {isMobile ? 'БИБЛИОТЕКА':'ВЕРНУТЬСЯ В БИБЛИОТЕКУ'}
Го текст в обычный регистр

2022-11-10 08:27 UTC, rkostyuchenko commented on src/pages/library/search-result/index.tsx
>                <Button
Нужно обернуть в `next/link`

2022-11-10 08:28 UTC, rkostyuchenko commented on src/components/library-form/library-form.tsx
>          href={`/library/search-result${urlQuery}`}
Но не везде 😉

2022-12-23 16:02 UTC, closed without merging