Исправление размера карточки пьесы
Studio-Yandex-Practicum/lubimovka_frontend pull request #445
Opened 2022-11-16 07:46 UTC by BorodkinaViktoriya

## Описание
Исправkztn размер карточки пьесы на странице спектакля 

## Ссылка на задачу
[Исправить размер карточки пьесы на странице спектакля ](Исправить размер карточки пьесы на странице спектакля )

2022-11-20 08:42 UTC, rkostyuchenko requested changes
Изменения `package-lock.json` не должны были попасть в коммит, потому что зависимости в проекте не менялись.

2022-11-20 08:42 UTC, rkostyuchenko commented on src/components/play-card/play-card.module.css
> +    margin: 0 auto;
Давай лучше унесем все стили, касающиеся внешнего поведения в элемент родительского блока или микс, оставив сам блок карточки универсальным.

Например: 
```
<PlayCard className={b('play')} ... />

.play {
  max-width: 240px;
}
```
Или
```
<div className={b('play')}>
  <PlayCard ... />
</div>

.play {
  max-width: 240px;
}
```
Так карточку можно будет легко переиспользовать, а внешние отступы не сломают неожиданно где-нибудь верстку

2022-11-21 15:40 UTC, BorodkinaViktoriya commented
> Изменения `package-lock.json` не должны были попасть в коммит, потому что зависимости в проекте не менялись.

в прошлый раз в другой ветке с ошибкой в коммитах ты писал что что то исправил в json и надо переустановить. я видимо не так установку сделала и что то там лишнее обновилось
Как мне теперь это все исправить?
можно ли так:
-беру json из девелоп, копирую вместо своего - переустанавливаю зависимости - пушу в новом коммите. 
 Только не пойму в какойветке теперь мне это делать. потому что я сначала спулила все  с develop  и потом переустановила и создала ветку. значит и в моей develop  так.
или все просто удалить и начать заново проще будет?

2022-11-21 16:14 UTC, rkostyuchenko commented
> Как мне теперь это все исправить?

Поскольку у тебя в PR всего один коммит, можно просто раскоммитить его `git reset --soft HEAD~1`, отменить изменения в `package-lock.json` (можно прямо в интерфейсе твоего редактора кода) и закоммитить снова.

Вообще изменения появляются, потому что в проекте package-lock.json первой версии, а у тебя локально нода посвежее и генерирует лок-файл второй версии после установки зависимостей. Проблем с этим быть не должно, но на CI и в бою все работает [Node.js версии 16](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/blob/develop/config/docker/Dockerfile#L1), поэтому локально для проекта лучше использовать ее же. Но не критично, можешь просто отменять изменения лок-файла после установки зависимостей. Или установить несколько версий ноды с помощью [nvm](https://github.com/nvm-sh/nvm))

2022-11-30 10:11 UTC, closed without merging