fix: исправление поля текст сообщения на странице контакты
Studio-Yandex-Practicum/lubimovka_frontend pull request #487
Opened 2023-09-10 06:37 UTC by Aleksey-dev-crt

## Описание
На странице контакты. Поле "Текст сообщение" можно сильно растянуть или сузить. Добавлены пропсы в компонент TextArea ограничивающие высоту и ширину поля.

## Ссылка на задачу
[На странице контакты. Поле "Текст сообщение" можно сильно растянуть или сузить](https://www.notion.so/241711121ba54c1a981cd37820d39596)

2023-09-12 10:49 UTC, AleksandrDronov reviewed
Привет. В макете размер поля 360х100px. И в макете не нашел максимально возможную высоту поля, возможно оно вообще не должно растягиваться. Возможно смотрю не тот макет. Я бы адресовал этот вопрос Александру и дизайнерам.
<img width="419" alt="image" src="https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/assets/93670312/e6ee39f2-d4f6-4f65-85d1-01c93f6b19d1">

2023-09-13 15:48 UTC, AlMkin commented on src/components/ui/text-area/text-area.module.css
>    max-width: 100%;
max-width: 100% избыточно и его можно удалить. Тут уже есть width

2023-09-13 15:48 UTC, AlMkin commented on src/components/ui/text-area/text-area.module.css
>    height: auto;
height: auto стандартное значение, кажется, тоже не обязательно

2023-09-14 08:29 UTC, AleksandrDronov requested changes

2023-09-14 08:29 UTC, AleksandrDronov commented on src/components/ui/text-area/text-area.module.css
> +  max-height: 100px;
Тут лучше тогда просто `height: 100px`

2023-09-14 08:36 UTC, AleksandrDronov commented
У тебя почему-то в этом ПРе оказался мой коммит, что не есть гуд.  Вводит в заблуждение. На будущее лучше так не делать.

2023-09-14 08:37 UTC, Aleksey-dev-crt commented on src/components/ui/text-area/text-area.module.css
> +  max-height: 100px;
так не будет работать, я проверял, свойства width и height для textarea инлайновые и они динамические, ограничить их можно свойствами min-width, max-width, min-height, max-height

2023-09-14 08:42 UTC, Aleksey-dev-crt commented
Это потому что я rebase делал, я про это спрашивал и так как раз делать рекомендутся в CONTRIBUTING.md

2023-09-14 08:43 UTC, AleksandrDronov commented on src/components/ui/text-area/text-area.module.css
> +  max-height: 100px;
Согласен. Я не прав

2023-09-14 08:45 UTC, AleksandrDronov commented
> Это потому что я rebase делал, я про это спрашивал и так как раз делать рекомендутся в CONTRIBUTING.md

Ага. Луче его делать перед мерджем.

2023-09-14 08:46 UTC, AleksandrDronov submitted a review, later dismissed

2023-09-14 13:54 UTC, AlMkin approved these changes

2023-09-14 13:56 UTC, AlMkin approved these changes

2023-09-14 13:59 UTC, merged