Open to cooperation
Studio-Yandex-Practicum/lubimovka_frontend pull request #92
Opened 2021-10-28 20:17 UTC by Kerjanoid

## Описание
Добавляет компонент OpenToCooperation

## Ссылка на задачу
[Сверстать блок «Проект открыт к сотрудничеству»](https://www.notion.so/6ee538eb49af4ff7a93e235f98c81179)

2021-10-30 16:46 UTC, Kerjanoid commented
Замечания учтены. Прошу провести повторное ревью

2021-10-30 17:25 UTC, borodulex requested changes
Есть вопросы к внешней геометрии и еще по мелочи 👇 А так хорошо, аккуратно)

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.module.css
> +  width: scale(553px);
Мы придерживаемся компонентного подхода. Блок не должен влиять на свое окружение, другими словами, не следует задавать "внешнюю геометрию": явные width и height; margin; position: absolute/fixed; top, left, bottom и right. Это все можно будет задать через родителя, когда для него этот компонент станет элементом.

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.module.css
> +  margin: scale(92px auto 169px 665px);
К этому тоже относится

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.module.css
> +.container {
Наверное стоит класс назвать как компонент, чтобы лучше читалось

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.module.css
> +  @media screen and (max-width: $tablet-portrait) {
Я думаю screen не нужно уточнять, так как пока не планируется другие типов устройств

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.module.css
> +  color: unset;
Думаю тут лучше читается inherit

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.module.css
> +  width: scale(553px);
А в сторибуке спозиционируй декоратором

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.tsx
> +      <div className={cx('asterisk')}></div>
Лучше использовать наш компонент `Icon`

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.tsx
> +      <h5 className={cx('header')}>Проект открыт к&nbsp;сотрудничеству</h5>
А почему тут именно `h5`?

2021-10-30 17:25 UTC, borodulex commented on src/shared/icons/asterisk.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#242424" viewBox="0 0 25 25">
Хардкодить цвет не очень хорошо, лучше отказаться от этого, либо currentColor использовать

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.tsx
> +export const OpenToCooperation: FC<IOpenToCoopProps> = (props) => {
Обычно ожидается, что компонент называется так же как и его файл

2021-10-30 17:25 UTC, borodulex commented on src/components/open-to-cooperation/project-page-cooperation.tsx
> +export const OpenToCooperation: FC<IOpenToCoopProps> = (props) => {
И в сторибуке не забудь

2021-10-30 20:30 UTC, Kerjanoid commented on src/components/open-to-cooperation/project-page-cooperation.tsx
> +      <h5 className={cx('header')}>Проект открыт к&nbsp;сотрудничеству</h5>
Изменил на h3 исходя из важности заголовка и его размера в макете

2021-10-31 04:23 UTC, naumch1k reviewed
уже почти-совсем)
оставила несколько комментариев, больше ничего не нашла

2021-10-31 04:23 UTC, naumch1k commented on src/components/project-page-cooperation/project-page-cooperation.tsx
> +    <div className={cx('project-page-cooperation')}>
заметила, что в нашем проекте классы из 2+ слов пишут в camelCase
@Kerjanoid @borodulex @RonWinchester поправьте, если не права

2021-10-31 04:23 UTC, naumch1k commented on src/components/project-page-cooperation/project-page-cooperation.module.css
> +.project-page-cooperation {
соответственно и тут поменять

2021-10-31 04:23 UTC, naumch1k commented on src/components/project-page-cooperation/index.ts
> +export * from './project-page-cooperation';
я бы 'page' убрала, оставила бы project-cooperation, чтобы в проекте все однотипно было
если так, не забудь директорию, имена файлов, имя компонента поменять

2021-10-31 13:05 UTC, Kerjanoid commented on src/components/project-page-cooperation/project-page-cooperation.tsx
> +    <div className={cx('project-page-cooperation')}>
Да, ты права. https://www.notion.so/eb5b3d893cbf4e7ab581a65a3c099dfc

2021-10-31 13:14 UTC, Kerjanoid commented on src/components/project-page-cooperation/index.ts
> +export * from './project-page-cooperation';
![image](https://user-images.githubusercontent.com/76227328/139585104-4c2f97b0-5c82-4fc9-b980-ff161d83a9e1.png)
просто есть 2 схожих по названию страницы: projects и project-page, и если оставить имена project и projects есть вариант запутаться...

2021-10-31 13:20 UTC, Kerjanoid commented on src/components/project-page-cooperation/index.ts
> +export * from './project-page-cooperation';
Исправлю project-page на project, поскольку уже есть другие компоненты именование которые начинается с project, а не project-page...

2021-11-02 08:06 UTC, borodulex approved these changes

2021-11-02 20:08 UTC, rkostyuchenko approved these changes

2021-11-02 20:08 UTC, merged